//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface _WANoBlurNavigationBar : UINavigationBar
{
    UIView *_grayBackgroundView;
    int _lastStateDuringLayout;
}

+ (void)initialize;

- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

