//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAShareContactTableViewCell.h"

__attribute__((visibility("hidden")))
@interface _WAShareContactTableViewCelliOS7 : WAShareContactTableViewCell
{
}

+ (float)heightForSharingUnit:(id)arg1 displayWidth:(float)arg2;
+ (id)bodyFont;
+ (id)titleFont;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

