//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAShapeView.h"

__attribute__((visibility("hidden")))
@interface _WAWaterWave : WAShapeView
{
    id _animationCompletionBlock;
    float _noisiness;
    float _noiseAmplitude;
    float _waveAmplitude;
    float _waveSpeed;
    float _waveFrequency;
    float _verticalScale;
    double _time;
}

@property(nonatomic) float verticalScale; // @synthesize verticalScale=_verticalScale;
@property(nonatomic) double time; // @synthesize time=_time;
@property(nonatomic) float waveFrequency; // @synthesize waveFrequency=_waveFrequency;
@property(nonatomic) float waveSpeed; // @synthesize waveSpeed=_waveSpeed;
@property(nonatomic) float waveAmplitude; // @synthesize waveAmplitude=_waveAmplitude;
@property(nonatomic) float noiseAmplitude; // @synthesize noiseAmplitude=_noiseAmplitude;
@property(nonatomic) float noisiness; // @synthesize noisiness=_noisiness;

- (id)pathAtTime:(double)arg1 inRect:(struct CGRect)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

