//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class ABDisabledViewController, NSString;

@protocol ABDisabledControllerDelegate <NSObject>

@optional
- (NSString *)helperTextForABDisabledViewController:(ABDisabledViewController *)arg1;
- (NSString *)helperTitleForABDisabledViewController:(ABDisabledViewController *)arg1;
- (void)abDisabledViewControllerDidCancel:(ABDisabledViewController *)arg1;
@end

