//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface ABDisabledViewController : WAViewController
{
    UIImageView *_imageViewLock;
    UILabel *_labelHelperTop;
    UILabel *_labelHelperBottom;
    id <ABDisabledControllerDelegate> _delegate;
}


- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (void)cancelAction:(id)arg1;
- (void)layoutHelperLabels;
- (id)initWithDelegate:(id)arg1;

@end

