//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "ABDisabledControllerDelegate.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "ProblemInputControllerDelegate.h"

@class UIImageView, UILabel, UITableView, UIView;

__attribute__((visibility("hidden")))
@interface AboutViewController : WAViewController <MFMailComposeViewControllerDelegate, ABDisabledControllerDelegate, ProblemInputControllerDelegate>
{
    UITableView *_tableViewButtons;
    UIView *_viewDivider;
    UIView *_viewLogoContainer;
    UIImageView *_imageLogo;
    UIImageView *_imageWP;
    UILabel *_labelTitlePortrait;
    UILabel *_labelVersionPortrait;
    UIView *_viewTableHeader;
    UILabel *_labelTitleLandscape;
    UILabel *_labelVersionLandscape;
    UIView *_footerView;
    UILabel *_labelCopyright;
}

@property(retain, nonatomic) UILabel *labelCopyright; // @synthesize labelCopyright=_labelCopyright;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UILabel *labelVersionLandscape; // @synthesize labelVersionLandscape=_labelVersionLandscape;
@property(retain, nonatomic) UILabel *labelTitleLandscape; // @synthesize labelTitleLandscape=_labelTitleLandscape;
@property(retain, nonatomic) UIView *viewTableHeader; // @synthesize viewTableHeader=_viewTableHeader;
@property(retain, nonatomic) UILabel *labelVersionPortrait; // @synthesize labelVersionPortrait=_labelVersionPortrait;
@property(retain, nonatomic) UILabel *labelTitlePortrait; // @synthesize labelTitlePortrait=_labelTitlePortrait;
@property(retain, nonatomic) UIImageView *imageWP; // @synthesize imageWP=_imageWP;
@property(retain, nonatomic) UIImageView *imageLogo; // @synthesize imageLogo=_imageLogo;
@property(retain, nonatomic) UIView *viewLogoContainer; // @synthesize viewLogoContainer=_viewLogoContainer;
@property(retain, nonatomic) UIView *viewDivider; // @synthesize viewDivider=_viewDivider;
@property(retain, nonatomic) UITableView *tableViewButtons; // @synthesize tableViewButtons=_tableViewButtons;

- (id)helperTextForABDisabledViewController:(id)arg1;
- (id)helperTitleForABDisabledViewController:(id)arg1;
- (void)abDisabledViewControllerDidCancel:(id)arg1;
- (void)probleminputControllerDidCancel:(id)arg1;
- (void)problemInputController:(id)arg1 didFinishWithText:(id)arg2 attachment:(id)arg3;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)uniqueIdentifier;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)openFAQAction;
- (void)contactUsAction;
- (void)updateLayoutToOrientation:(int)arg1;
- (void)dealloc;
- (id)init;

@end

