//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

#import "DeleteAccountControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "VerificationControllerDelegate.h"

__attribute__((visibility("hidden")))
@interface AccountViewController : WAStaticTableViewController <UINavigationControllerDelegate, DeleteAccountControllerDelegate, VerificationControllerDelegate>
{
}

- (void)applicationDidEnterBackground:(id)arg1;
- (void)verificationControllerDidCancel:(id)arg1;
- (void)verificationControllerDidSucceed:(id)arg1;
- (void)deleteAccountContollerDidCancel:(id)arg1;
- (void)deleteAccountContollerDidFinish:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)deleteAccountAction;
- (void)changeNumberAction;
- (void)viewNetworkUsageAction;
- (void)viewPaymentInfoAction;
- (void)setPrivacyAction;
- (void)deselectActiveCell;
- (void)dealloc;
- (id)init;

@end

