//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface AudioSession : NSObject
{
    BOOL _sessionActivated;
    BOOL _speakerActivated;
    BOOL _headsetPluggedIn;
    unsigned long _previousAudioCategory;
    id <AudioSessionDelegate> _delegate;
}

@property(readonly) id <AudioSessionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly) BOOL headsetPluggedIn; // @synthesize headsetPluggedIn=_headsetPluggedIn;
@property(readonly) BOOL speakerActivated; // @synthesize speakerActivated=_speakerActivated;
@property(readonly) BOOL sessionActivated; // @synthesize sessionActivated=_sessionActivated;
- (BOOL)isHeadsetPluggedIn;
- (BOOL)isSilentMode;
- (float)systemVolume;
- (id)audioRoute;
- (void)deactivateSession;
- (void)activateSession;
- (void)redirectToEarpiece;
- (void)redirectToSpeaker;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

