//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class NSDate, UIActivityIndicatorView, UILabel, UITableView, UIView, WABackupInfoTableCell, WAProgressHUD;

__attribute__((visibility("hidden")))
@interface BackupViewController : WAViewController
{
    long long _potentialBackupSize;
    WAProgressHUD *_progressHUD;
    NSDate *_hudDisplayedDate;
    UITableView *_tableViewBackup;
    WABackupInfoTableCell *_cellBackupInfo;
    UIView *_viewTableFooter;
    UILabel *_labelProgressInfo;
    UILabel *_labelFooterText;
    UIActivityIndicatorView *_aiBackup;
}

@property(retain, nonatomic) UIActivityIndicatorView *aiBackup; // @synthesize aiBackup=_aiBackup;
@property(retain, nonatomic) UILabel *labelFooterText; // @synthesize labelFooterText=_labelFooterText;
@property(retain, nonatomic) UILabel *labelProgressInfo; // @synthesize labelProgressInfo=_labelProgressInfo;
@property(retain, nonatomic) UIView *viewTableFooter; // @synthesize viewTableFooter=_viewTableFooter;
@property(retain, nonatomic) WABackupInfoTableCell *cellBackupInfo; // @synthesize cellBackupInfo=_cellBackupInfo;
@property(retain, nonatomic) UITableView *tableViewBackup; // @synthesize tableViewBackup=_tableViewBackup;

- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)showAutobackupSettings;
- (void)startBackupAction;
- (void)chatStorageDidLoadDatabase:(id)arg1;
- (void)iCloudBackupUpdated:(id)arg1;
- (void)stopAnimatingGears;
- (void)startAnimatingGears;
- (void)reloadBackupInfo;
- (void)setProgressText:(id)arg1 showFooterText:(BOOL)arg2 animates:(BOOL)arg3;
- (id)footerTextForBackupUploadProgress:(float)arg1;
- (id)footerTextForBackupProgress:(float)arg1;
- (void)removeHUD:(BOOL)arg1;
- (void)removeHUD;
- (void)showHUD:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

