//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MultilineHeaderView.h"

@class NSString, UIFont;

__attribute__((visibility("hidden")))
@interface ChatHeaderView : MultilineHeaderView
{
    NSString *_secondLineText;
    UIFont *_firstLineFont;
}

@property(retain, nonatomic) UIFont *firstLineFont; // @synthesize firstLineFont=_firstLineFont;

- (void)setLayoutType:(unsigned int)arg1;
- (void)setOrientation:(unsigned int)arg1;
- (id)secondLineText;
- (void)setSecondLineText:(id)arg1;
- (void)setFirstLineText:(id)arg1;
- (id)secondLineFontForLayout:(unsigned int)arg1 orientation:(unsigned int)arg2;
- (id)firstLineFontForLayout:(unsigned int)arg1 orientation:(unsigned int)arg2;
- (id)initWithFrame:(struct CGRect)arg1 orientation:(unsigned int)arg2;

@end

