//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "ABDisabledControllerDelegate.h"
#import "ABNewPersonViewControllerDelegate.h"
#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "ForwardPickerDelegate.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "PhoneConfirmationControllerDelegate.h"
#import "PhoneInputViewControllerDelegate.h"
#import "SinglePersonPickerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIVideoEditorControllerDelegate.h"
#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerTransitioningDelegate.h"
#import "WAChatSessionCellDelegate.h"
#import "WAGroupComposerDelegate.h"
#import "WAInfoInputViewControllerDelegate.h"
#import "WAMediaGalleryControllerDelegate.h"

@class NSArray, NSManagedObjectID, NSMutableArray, NSMutableDictionary, NSOperationQueue, NSString, UIBarButtonItem, UILabel, UIPercentDrivenInteractiveTransition, UITableView, UITableViewCell, UIView, UIWebView, WAActivityLabel, WAChatButton, WAChatSession, WAChatsTableView;

__attribute__((visibility("hidden")))
@interface ChatListViewController : WATableViewController <UIVideoEditorControllerDelegate, UIActionSheetDelegate, UINavigationControllerDelegate, MFMessageComposeViewControllerDelegate, MFMailComposeViewControllerDelegate, ForwardPickerDelegate, SinglePersonPickerDelegate, PhoneInputViewControllerDelegate, WAGroupComposerDelegate, WAChatSessionCellDelegate, ABNewPersonViewControllerDelegate, ABPeoplePickerNavigationControllerDelegate, WAInfoInputViewControllerDelegate, ABDisabledControllerDelegate, UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning, WAMediaGalleryControllerDelegate, UIGestureRecognizerDelegate, PhoneConfirmationControllerDelegate>
{
     _prepareToSendVideoFileCompletionHandler;
    UIBarButtonItem *_barButtonCompose;
    UIBarButtonItem *_barButtonEditBegin;
    UIBarButtonItem *_barButtonEditDone;
    UIBarButtonItem *_barButtonDeleteAll;
    WAActivityLabel *_activityLabel;
    UIView *_viewSearchInProgress;
    void *_addressBook;
    NSMutableDictionary *_chatViewControllers;
    BOOL _viewIsActive;
    NSString *_selectedChatJID;
    int _numberOfRows;
    NSArray *_searchResults;
    NSOperationQueue *_searchQueue;
    BOOL _moreResultsComing;
    NSString *_messageText;
    NSMutableArray *_contactPhones;
    NSMutableArray *_contactEmails;
    NSManagedObjectID *_contactID;
    NSString *_stringForSizingDeleteButton;
    WAChatSession *_selectedChatSessionForMoreOptions;
    WAChatSession *_chatSessionForSideSwipe;
    UITableViewCell *_chatSessionCellForSideSwipe;
    UIPercentDrivenInteractiveTransition *_sideSwipeInteractionController;
    BOOL _sideSwipeInteractionInProgress;
    BOOL _sideSwipeIsPresenting;
    struct dispatch_group_s *_sideSwipeDispatchGroup;
    WAChatsTableView *_tableViewChats;
    UITableView *_tableViewNoChats;
    UIView *_viewHelperText;
    UIWebView *_labelHelperTop;
    UILabel *_labelHelperBottom;
    UIView *_viewChatButtons;
    WAChatButton *_buttonBroadcast;
    WAChatButton *_buttonGroupChat;
}

@property(retain, nonatomic) WAChatButton *buttonGroupChat; // @synthesize buttonGroupChat=_buttonGroupChat;
@property(retain, nonatomic) WAChatButton *buttonBroadcast; // @synthesize buttonBroadcast=_buttonBroadcast;
@property(retain, nonatomic) UIView *viewChatButtons; // @synthesize viewChatButtons=_viewChatButtons;
@property(retain, nonatomic) UILabel *labelHelperBottom; // @synthesize labelHelperBottom=_labelHelperBottom;
@property(retain, nonatomic) UIWebView *labelHelperTop; // @synthesize labelHelperTop=_labelHelperTop;
@property(retain, nonatomic) UIView *viewHelperText; // @synthesize viewHelperText=_viewHelperText;
@property(retain, nonatomic) UITableView *tableViewNoChats; // @synthesize tableViewNoChats=_tableViewNoChats;
@property(retain, nonatomic) WAChatsTableView *tableViewChats; // @synthesize tableViewChats=_tableViewChats;

- (void)mediaManagerDidDeleteContent:(id)arg1;
- (void)mediaGalleryController:(id)arg1 interactiveDismissGestureDidChange:(id)arg2;
- (void)mediaGalleryControllerDidExit:(id)arg1;
- (void)mediaGalleryController:(id)arg1 didSelectMediaAtIndexPath:(id)arg2;
- (void)cleanUpAfterSideSwipe;
- (double)transitionDuration:(id)arg1;
- (void)animateTransition:(id)arg1;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)prepareForSideSwipe;
- (void)cancelSideSwipeGesture:(id)arg1;
- (void)chatSessionCell:(id)arg1 sideSwipeGestureDidChange:(id)arg2;
- (BOOL)allowSideSwipeGestureToComplete:(id)arg1;
- (BOOL)sideSwipeGestureSupportsLandscapeOrientation;
- (void)abDisabledViewControllerDidCancel:(id)arg1;
- (void)infoInputViewControllerDidCancel:(id)arg1;
- (void)infoInputViewControllerDidFinish:(id)arg1;
- (void)continueEditingPerson:(void *)arg1 onNavigationController:(id)arg2;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)addNumberFromChatSessionToExistingContact:(id)arg1;
- (void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(void *)arg2;
- (void)addNewPersonFromChatSessionToContacts:(id)arg1;
- (void)emailChatHistoryForChatSession:(id)arg1 withMailComposeViewController:(id)arg2;
- (void)showUnknownContactOptionsForChatSession:(id)arg1;
- (void)showKnownContactOptionsForChatSession:(id)arg1;
- (void)showGroupOptionsForChatSession:(id)arg1;
- (void)chatSessionCellShowMoreOptions:(id)arg1;
- (void)promptForConfirmationToClearChatSession:(id)arg1;
- (void)updateMuteStateOfCellForChatSession:(id)arg1;
- (id)tableViewSessions;
- (void)videoEditorControllerDidCancel:(id)arg1;
- (void)videoEditorController:(id)arg1 didFailWithError:(id)arg2;
- (void)videoEditorController:(id)arg1 didSaveEditedVideoToPath:(id)arg2;
- (void)prepareExternalVideoFileForSending:(id)arg1 completion:(id)arg2;
- (void)groupComposerDidCancel:(id)arg1;
- (void)groupComposer:(id)arg1 didFinishWithContacts:(id)arg2 subject:(id)arg3 picture:(id)arg4;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)phoneInputViewControllerDidCancel:(id)arg1;
- (void)phoneInputViewController:(id)arg1 didFinishWithCountryCode:(id)arg2 phoneNumber:(id)arg3;
- (void)profilePictureUpdated:(id)arg1;
- (void)chatStorageDidLoadDatabase:(id)arg1;
- (void)fontSizeDidChange:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (id)forwardPicker:(id)arg1 confirmationTextForContact:(id)arg2;
- (void)forwardPickerDidCancel:(id)arg1;
- (void)forwardPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)singlePersonPickerDidCancel:(id)arg1;
- (void)singlePersonPicker:(id)arg1 didSelectAction:(id)arg2;
- (void)singlePersonPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)xmppConnectionChatStateDidChange:(id)arg1;
- (void)xmppConnectionStateDidChange:(id)arg1;
- (void)xmppConnectionNetworkStatusDidChange:(id)arg1;
- (void)chatStorageDidDeleteMessagesInChatSession:(id)arg1;
- (void)chatStorageDidUpdateChatSessionList:(id)arg1;
- (void)chatStorageDidDeleteChatSessions:(id)arg1;
- (void)chatStorageWillDeleteChatSession:(id)arg1;
- (void)chatStorageDidUpdateMessage:(id)arg1;
- (void)chatStorageDidUpdateChatSession:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)requestConfirmationToDeleteGroupChatSession:(id)arg1 atIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)visibleCellWithJid:(id)arg1;
- (void)processSendURL:(id)arg1;
- (void)showChatAfterSendingExternalMediaWithMessage:(id)arg1 error:(id)arg2;
- (void)sendExternalMediaAtURL:(id)arg1 toContact:(id)arg2;
- (void)forwardFileAtURL:(id)arg1;
- (void)forwardMessages:(id)arg1 toContact:(id)arg2 JID:(id)arg3;
- (void)jumpToAllChatsFromViewController:(id)arg1;
- (void)startChatFromURLWithContactDict:(id)arg1;
- (void)startChatFromURLWithJID:(id)arg1;
- (id)startChatWithContact:(id)arg1 JID:(id)arg2 pushImmediately:(BOOL)arg3 animated:(BOOL)arg4;
- (id)startChatWithSession:(id)arg1 highlightedMessage:(id)arg2 activateKeyboard:(BOOL)arg3 pushImmediately:(BOOL)arg4 animated:(BOOL)arg5;
- (id)startChatWithContact:(id)arg1 JID:(id)arg2 animated:(BOOL)arg3;
- (void)sendEmailInviteTo:(id)arg1;
- (void)sendSMSInviteTo:(id)arg1;
- (id)backItemTitleForViewController:(id)arg1;
- (id)shortViewControllerTitle;
- (id)searchQueue;
- (id)chatViewControllers;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidUnload;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)uniqueIdentifier;
- (void)searchFinishedWithUserInfo:(id)arg1;
- (void)startSearch;
- (void)phoneConfirmationControllerDidCancel:(id)arg1;
- (void)phoneConfirmationControllerDidFinish:(id)arg1;
- (void)groupChatAction:(id)arg1;
- (void)broadcastAction:(id)arg1;
- (void)deleteAllAction:(id)arg1;
- (void)leaveEditModeAction:(id)arg1;
- (void)enterEditModeAction:(id)arg1;
- (void)composeAction:(id)arg1;
- (void)inviteContacts;
- (void)leaveSearchMode;
- (void)leaveEditMode;
- (void)startGroupChat;
- (void)startNewChat;
- (void)removeFileAtURL:(id)arg1;
- (void)layoutTopButtons;
- (void)formatHelperText;
- (id)topHelperHTMLStringWithFont:(id)arg1;
- (void)showTooltipIfNeeded;
- (void)purgeViewControllers;
- (BOOL)isCachedViewControllerAvailableForChatSession:(id)arg1;
- (void)hideActivity;
- (void)showActivity:(id)arg1;
- (void)updateUI;
- (void)formatTitle;
- (void)hideSearchBarIfNecessary;
- (void)dealloc;
- (id)init;

@end

