//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAImageToImageTransitionNavigationController.h"

__attribute__((visibility("hidden")))
@interface ChatNavigationController : WAImageToImageTransitionNavigationController
{
}

- (BOOL)shouldAutorotate;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (id)init;
- (void)reloadViewControllers;

@end

