//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "WAChatStorageDataSource.h"
#import "WAChatStorageDelegate.h"
#import "WAContactsStorageDelegate.h"
#import "WASyncManagerDelegate.h"
#import "XMPPConnectionDataSource.h"
#import "XMPPConnectionDelegate.h"

@class ALAssetsLibrary, CLLocation, NSByteCountFormatter, NSCalendar, NSDate, NSDateFormatter, NSDictionary, NSLock, NSMutableArray, NSMutableDictionary, NSMutableSet, NSNumberFormatter, NSString, NSThread, UIAlertView, WAChatStorage, WACloudBackup, WAContactsStorage, WANotificationCenter, WASyncManager, XMPPConnection;

__attribute__((visibility("hidden")))
@interface ChatManager : NSObject <WAChatStorageDelegate, WAChatStorageDataSource, WAContactsStorageDelegate, WASyncManagerDelegate, XMPPConnectionDelegate, XMPPConnectionDataSource>
{
    NSDictionary *_iCloudStats;
     _blockToPerformAfterDisconnecting;
    NSNumberFormatter *_numberFormatter;
    NSDateFormatter *_dateFormatterShortStyle;
    NSDateFormatter *_dateFormatterMediumStyle;
    NSDateFormatter *_dateFormatterMediumStyleNoYear;
    NSDateFormatter *_timeFormatter;
    NSDateFormatter *_dateTimeFormatter;
    NSByteCountFormatter *_bcFormatter;
    NSCalendar *_sharedCalendar;
    NSMutableArray *_shortWeekdaySymbols;
    NSMutableArray *_weekdaySymbols;
    NSMutableDictionary *_lastNotificationTimeForChat;
    UIAlertView *_networkUnavailableAlertView;
    NSMutableSet *_chatSessionsToRefresh;
    NSMutableSet *_groupChatsToRefresh;
    NSThread *_addressBookThread;
    BOOL _needsReloadAddressBook;
    BOOL _needsRefreshChats;
    BOOL _verificationInProgress;
    BOOL _popupMenuVisible;
    BOOL _usingSilentPush;
    BOOL _addressBookReloadingInProgress;
    WAChatStorage *_storage;
    ALAssetsLibrary *_assetsLibrary;
    void *_sharedAddressBook;
    NSString *_bingAPIKey;
    NSString *_googleAPIKey;
    NSString *_fsqClientID;
    NSString *_fsqClientSecret;
    NSString *_registrationURL;
    NSString *_codeRequestURL;
    NSString *_sameDeviceCheckURL;
    NSString *_phoneNumber;
    NSString *_countryCode;
    NSString *_currentStatus;
    NSString *_deviceToken;
    XMPPConnection *_connection;
    WACloudBackup *_cloudBackup;
    WAContactsStorage *_contactsStorage;
    WASyncManager *_syncManager;
    NSMutableArray *_statusList;
    NSMutableSet *_navigationBarHintHistory;
    WANotificationCenter *_notificationCenter;
    NSMutableSet *_placeCache;
    NSDate *_gOverQueryLimitDate;
    CLLocation *_lastKnownLocation;
}

+ (id)sharedManager;
@property(readonly, nonatomic) BOOL addressBookReloadingInProgress; // @synthesize addressBookReloadingInProgress=_addressBookReloadingInProgress;
@property(nonatomic) BOOL usingSilentPush; // @synthesize usingSilentPush=_usingSilentPush;
@property(retain, nonatomic) CLLocation *lastKnownLocation; // @synthesize lastKnownLocation=_lastKnownLocation;
@property(retain, nonatomic) NSDate *gOverQueryLimitDate; // @synthesize gOverQueryLimitDate=_gOverQueryLimitDate;
@property(readonly, nonatomic) NSMutableSet *placeCache; // @synthesize placeCache=_placeCache;
@property(nonatomic) BOOL popupMenuVisible; // @synthesize popupMenuVisible=_popupMenuVisible;
@property(nonatomic) BOOL verificationInProgress; // @synthesize verificationInProgress=_verificationInProgress;
@property(readonly, nonatomic) WANotificationCenter *notificationCenter; // @synthesize notificationCenter=_notificationCenter;
@property(readonly, nonatomic) NSMutableSet *navigationBarHintHistory; // @synthesize navigationBarHintHistory=_navigationBarHintHistory;
@property(readonly, nonatomic) NSMutableArray *statusList; // @synthesize statusList=_statusList;
@property(readonly, nonatomic) WASyncManager *syncManager; // @synthesize syncManager=_syncManager;
@property(readonly, nonatomic) WAContactsStorage *contactsStorage; // @synthesize contactsStorage=_contactsStorage;
@property(readonly, nonatomic) WACloudBackup *cloudBackup; // @synthesize cloudBackup=_cloudBackup;
@property(readonly, nonatomic) XMPPConnection *connection; // @synthesize connection=_connection;
@property(copy, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(copy, nonatomic) NSString *currentStatus; // @synthesize currentStatus=_currentStatus;
@property(readonly, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(readonly, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;

- (void)reconnectAndLoadChatDatabaseWithCompletionHandler:(id)arg1;
- (void)disconnectAndUnloadChatDatabaseWithCompletionHandler:(id)arg1;
- (id)addContactFromABRecord:(void *)arg1 addressBook:(void *)arg2 whatsAppID:(id)arg3;
- (id)reloadDataFromABRecord:(void *)arg1 whatsAppID:(id)arg2;
- (void)reloadUnknownChatsWithWAContact:(id)arg1;
- (void)reportCloudBackupStatsWithInfo:(id)arg1;
- (void)reportMediaPickerStatsWithInfo:(id)arg1;
- (void)chatStorageDidLoadDatabase:(id)arg1;
- (void)currentLocaleDidChange:(id)arg1;
- (void)menuControllerDidHideMenu:(id)arg1;
- (void)menuControllerDidShowMenu:(id)arg1;
- (void)sendLocalNotificationForMessage:(id)arg1 fromUser:(id)arg2;
- (BOOL)messageShouldBeMuted:(id)arg1;
- (void)saveNotificationTimeForMessage:(id)arg1;
- (void)changeNumberFailedWithError:(id)arg1;
- (void)changeNumberFinishedWithAccountInfo:(id)arg1;
- (id)addressBookContainsJID:(id)arg1;
- (void)xmppConnection:(id)arg1 callabilityChangedForJID:(id)arg2 callability:(int)arg3;
- (void)xmppConnection:(id)arg1 contactsSyncRequest:(id)arg2 timestamp:(id)arg3;
- (void)xmppConnection:(id)arg1 contactUpdated:(id)arg2;
- (void)xmppConnection:(id)arg1 contactRemoved:(id)arg2;
- (void)xmppConnection:(id)arg1 contactAdded:(id)arg2;
- (void)xmppConnection:(id)arg1 statusChanged:(id)arg2;
- (void)xmppConnection:(id)arg1 dirtyFlagsReceived:(id)arg2 timestamp:(id)arg3;
- (void)xmppConnection:(id)arg1 profilePictureUploadRequestFor:(id)arg2 timestamp:(id)arg3;
- (void)xmppConnection:(id)arg1 profilePictureChangedFor:(id)arg2 identifier:(id)arg3 author:(id)arg4 name:(id)arg5 timestamp:(id)arg6;
- (void)xmppConnection:(id)arg1 subjectChanged:(id)arg2 forGroup:(id)arg3 name:(id)arg4 ujid:(id)arg5 timestamp:(id)arg6 offlineStorage:(BOOL)arg7;
- (void)xmppConnection:(id)arg1 userModified:(id)arg2 toJID:(id)arg3 inGroup:(id)arg4 timestamp:(id)arg5;
- (void)xmppConnection:(id)arg1 userRemoved:(id)arg2 fromGroup:(id)arg3 byUser:(id)arg4 timestamp:(id)arg5;
- (void)xmppConnection:(id)arg1 userAdded:(id)arg2 toGroup:(id)arg3 timestamp:(id)arg4;
- (void)xmppConnection:(id)arg1 statusChanged:(unsigned int)arg2 forMessageWithStanzaID:(id)arg3 fromJID:(id)arg4 participantJID:(id)arg5 userData:(id)arg6;
- (void)xmppConnection:(id)arg1 chatStateChanged:(unsigned int)arg2 forJID:(id)arg3;
- (void)xmppConnection:(id)arg1 presenceChanged:(unsigned int)arg2 forJID:(id)arg3;
- (void)xmppConnection:(id)arg1 presenceChanged:(unsigned int)arg2;
- (void)xmppConnection:(id)arg1 lastActivityChangedForJID:(id)arg2;
- (void)xmppConnectionDidDisconnect:(id)arg1;
- (void)xmppConnectionDidNotAuthenticate:(id)arg1;
- (void)xmppConnectionDidAuthenticate:(id)arg1;
- (void)xmppConnectionDidConnect:(id)arg1;
- (void)xmppConnection:(id)arg1 stateChanged:(unsigned int)arg2;
- (void)xmppConnection:(id)arg1 networkStatusChanged:(unsigned int)arg2;
- (void)networkStatusChanged:(unsigned int)arg1;
- (void)showNetworkUnavailableAlert;
- (void)syncManager:(id)arg1 didFinishSyncWithResult:(unsigned int)arg2;
- (void)contactsStorageDidFailToGenerateFavorites:(id)arg1;
- (void)contactsStorageDidGenerateFavorites:(id)arg1;
- (void)contactsStorageDidUpdateFavorites:(id)arg1;
- (void)contactsStorageDidUpdateStatus:(id)arg1;
- (void)contactsStorageDidUpdateContacts:(id)arg1;
- (BOOL)isRecipientExists:(id)arg1;
- (void)getPresenseForChatSession:(id)arg1;
- (id)contactForJID:(id)arg1;
- (void)updateChatSessionWithContactData:(id)arg1;
- (void)chatStorage:(id)arg1 didUpdateParticipantsOfChatSession:(id)arg2;
- (void)chatStorage:(id)arg1 didDeleteMessagesInChatSession:(id)arg2;
- (void)chatStorage:(id)arg1 willDeleteChatSession:(id)arg2;
- (void)chatStorage:(id)arg1 didUpdateChatSession:(id)arg2;
- (void)chatStorage:(id)arg1 didDeleteChatSessionsAtIndexes:(id)arg2;
- (void)chatStorageDidUpdateChatSessionList:(id)arg1;
- (void)chatStorageDidUpdateBlacklist:(id)arg1;
- (void)mediaDownloadFailedForMessage:(id)arg1 withError:(id)arg2 autodownload:(BOOL)arg3;
- (void)mediaUploadFailedForMessage:(id)arg1;
- (void)chatStorage:(id)arg1 didUpdateMessage:(id)arg2;
- (void)chatStorage:(id)arg1 didReceiveMessage:(id)arg2;
- (void)chatStorage:(id)arg1 didAddMessages:(id)arg2;
- (void)chatStorage:(id)arg1 didFailWithError:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)fetcher:(id)arg1 finishedWithJSONData:(id)arg2 error:(id)arg3;
- (void)failedUploadNotifyForMessage:(id)arg1;
- (id)pushSettings;
- (void)saveStatusList;
- (void)deleteAllStatusMessages;
- (void)resetStatusMessages;
- (void)loadStatusMessages;
- (id)statusListFilePath;
- (void)postPhoneNumberChangedNotification;
- (void)registerWithAuthCode:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4;
- (void)requestAuthCodeWithDelegate:(id)arg1 method:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4;
- (void)getNewPasswordFailedWithError:(id)arg1;
- (void)getNewPasswordFinishedWithResult:(id)arg1;
- (void)sameDeviceCheckForPhone:(id)arg1 countryCode:(id)arg2 delegate:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5;
- (void)sameDeviceCheckForPhone:(id)arg1 countryCode:(id)arg2 rcToken:(id)arg3 delegate:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6;
- (id)requiredString2;
- (id)requiredString1;
- (void)resetAuthInfo;
- (void)initializeChat;
- (void)requestLastSeenForJID:(id)arg1;
- (void)dataRefreshContextDidSave:(id)arg1;
- (void)mergeChanges:(id)arg1;
- (void)refreshChats;
- (void)refreshChatSessionsForUnknownContactsWithContext:(id)arg1;
- (id)allWhatsAppIDsInChatSessions:(id)arg1;
- (void)refreshChatSessionsForKnownContactsWithContext:(id)arg1;
- (id)allABIDsInChatSessions:(id)arg1;
- (BOOL)findContactInContext:(id)arg1 forChatSession:(id)arg2;
- (void)reset;
- (void)internalReset;
- (void)requestInteractiveDeltaSync;
- (void)reloadFavorites;
- (void)internalReloadFavorites;
- (void)resetContactsSync;
- (void)enableContactsSync;
- (void)reloadAddressBook;
- (void)reloadAddressBookIfNeeded;
- (void)setNeedsReloadAddressBook;
@property(readonly, nonatomic) NSLock *addressBookMutationLock;
- (void)abThreadMain;
- (void)startAddressBookThread;
- (id)addressBookThread;
- (void)setUserInteractionEnabled;
- (id)mapsURLsForAddress:(id)arg1;
- (id)mapsURLsForCoordinate:(CDStruct_c3b9c2ee)arg1 address:(id)arg2;
- (id)routeURLsForSourceLocation:(id)arg1 destCoordinate:(CDStruct_c3b9c2ee)arg2 destAddress:(id)arg3;
- (void)initializeIPod;
- (id)lastSeenStringFromDate:(id)arg1;
- (id)dayOfTheWeekFromDate:(id)arg1;
- (id)messageTimestampStringFromDate:(id)arg1;
- (id)messageDateStringFromDate:(id)arg1;
- (id)dateTimeStringFromDate:(id)arg1;
- (id)chatTimestampFromDate:(id)arg1;
- (id)backupSizeStringFromLongLong:(long long)arg1;
- (id)sizeStringFromLongLong:(long long)arg1;
- (id)sizeStringFromLongLong:(long long)arg1 numberFormatter:(id)arg2;
- (id)localizedStringWithFormat:(id)arg1 number:(id)arg2;
- (id)sharedCalendar;
- (id)dateTimeFormatter;
- (id)timeFormatter;
- (id)dateFormatterMediumStyleNoYear;
- (id)dateFormatterMediumStyle;
- (id)dateFormatterShortStyle;
- (id)numberFormatter;
@property(readonly, nonatomic) WAChatStorage *storage; // @synthesize storage=_storage;
- (id)shortWeekdaySymbols;
- (id)weekdaySymbols;
@property(readonly, nonatomic) ALAssetsLibrary *assetsLibrary; // @synthesize assetsLibrary=_assetsLibrary;
@property(readonly, nonatomic) void *sharedAddressBook; // @synthesize sharedAddressBook=_sharedAddressBook;
@property(readonly, nonatomic) NSString *fsqClientSecret; // @synthesize fsqClientSecret=_fsqClientSecret;
@property(readonly, nonatomic) NSString *fsqClientID; // @synthesize fsqClientID=_fsqClientID;
@property(readonly, nonatomic) NSString *googleAPIKey; // @synthesize googleAPIKey=_googleAPIKey;
@property(readonly, nonatomic) NSString *bingAPIKey; // @synthesize bingAPIKey=_bingAPIKey;
@property(readonly, nonatomic) NSString *sameDeviceCheckURL; // @synthesize sameDeviceCheckURL=_sameDeviceCheckURL;
@property(readonly, nonatomic) NSString *codeRequestURL; // @synthesize codeRequestURL=_codeRequestURL;
@property(readonly, nonatomic) NSString *registrationURL; // @synthesize registrationURL=_registrationURL;
- (BOOL)allowServicePurchase;
- (id)localizedServiceExpirationDate;
- (id)localizedServicePrice;
- (id)serviceExpirationDate;
- (unsigned int)accountType;
- (unsigned int)serviceType;
- (id)fullPhoneNumber:(BOOL)arg1;
- (id)fullPhoneNumber;
- (void)setCountryCode:(id)arg1 phoneNumber:(id)arg2;
- (void)dealloc;
- (id)init;

@end

