//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "ABNewPersonViewControllerDelegate.h"

@class NSArray, NSIndexPath, NSTimer, UIActivityIndicatorView, UILabel, UITableView, UITableViewCell, UIView, WAContactNameLabel;

__attribute__((visibility("hidden")))
@interface ContactsViewController : WAViewController <ABNewPersonViewControllerDelegate>
{
    NSArray *_sections;
    NSArray *_searchResults;
    int _numberOfContacts;
    NSIndexPath *_selectedRowIndexPath;
    BOOL _dataAvailable;
    BOOL _needsUpdateUI;
    BOOL _initialLoadingCompleted;
    NSTimer *_dataAvailabilityTimer;
    int _groupID;
    UITableView *_tableView;
    UIView *_viewMyNumber;
    WAContactNameLabel *_labelMyNumber;
    UITableViewCell *_cellNoContacts;
    UILabel *_labelNoContacts;
    UITableViewCell *_cellContactsTotal;
    UILabel *_labelContactsTotal;
    UITableViewCell *_cellLoading;
    UIActivityIndicatorView *_aiLoading;
    UILabel *_labelLoading;
}

@property(retain, nonatomic) UILabel *labelLoading; // @synthesize labelLoading=_labelLoading;
@property(retain, nonatomic) UIActivityIndicatorView *aiLoading; // @synthesize aiLoading=_aiLoading;
@property(retain, nonatomic) UITableViewCell *cellLoading; // @synthesize cellLoading=_cellLoading;
@property(retain, nonatomic) UILabel *labelContactsTotal; // @synthesize labelContactsTotal=_labelContactsTotal;
@property(retain, nonatomic) UITableViewCell *cellContactsTotal; // @synthesize cellContactsTotal=_cellContactsTotal;
@property(retain, nonatomic) UILabel *labelNoContacts; // @synthesize labelNoContacts=_labelNoContacts;
@property(retain, nonatomic) UITableViewCell *cellNoContacts; // @synthesize cellNoContacts=_cellNoContacts;
@property(retain, nonatomic) WAContactNameLabel *labelMyNumber; // @synthesize labelMyNumber=_labelMyNumber;
@property(retain, nonatomic) UIView *viewMyNumber; // @synthesize viewMyNumber=_viewMyNumber;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int groupID; // @synthesize groupID=_groupID;

- (void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(void *)arg2;
- (void)contactsStorageDidUpdateContacts:(id)arg1;
- (void)contactsStorageDidUpdateStatus:(id)arg1;
- (void)chatManagerDidChangePhoneNumer:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)fontSizeDidChange:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)adjustSearchbarPositionAndTableviewInsets;
- (void)addContactAction:(id)arg1;
- (void)alignActivityIndicator;
- (void)saveTableScrollPosition;
- (BOOL)showIndexBar;
- (void)setNeedsUpdateUI;
- (void)checkDataAvailability:(id)arg1;
- (void)restoreTableScrollPosition;
- (void)setupDisplayList;
- (void)loadContactsInSection:(id)arg1;
- (void)leaveSearchMode;
- (void)searchWithCriteria:(id)arg1;
- (void)dealloc;
- (id)init;

@end

