//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSMutableSet, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface CountryInfo : NSObject
{
    NSString *_iso;
    NSString *_name;
    NSString *_localizedName;
    NSString *_cc;
    NSArray *_mcc;
    NSArray *_lengths;
    NSArray *_trims;
    NSString *_regex;
    NSArray *_formats;
    NSMutableSet *_searchTokens;
}

@property(retain, nonatomic) NSArray *formats; // @synthesize formats=_formats;
@property(retain, nonatomic) NSString *regex; // @synthesize regex=_regex;
@property(retain, nonatomic) NSArray *trims; // @synthesize trims=_trims;
@property(retain, nonatomic) NSArray *lengths; // @synthesize lengths=_lengths;
@property(retain, nonatomic) NSArray *mcc; // @synthesize mcc=_mcc;
@property(retain, nonatomic) NSString *cc; // @synthesize cc=_cc;
@property(retain, nonatomic) NSString *localizedName; // @synthesize localizedName=_localizedName;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *iso; // @synthesize iso=_iso;

@property(readonly, nonatomic) NSSet *searchTokens; // @dynamic searchTokens;
- (id)description;

@end

