//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAModalNavigationController.h"

#import "DeleteConfirmationControllerDelegate.h"
#import "FeedbackInputControllerDelegate.h"
#import "PhoneConfirmationControllerDelegate.h"

__attribute__((visibility("hidden")))
@interface DeleteAccountContoller : WAModalNavigationController <PhoneConfirmationControllerDelegate, FeedbackInputControllerDelegate, DeleteConfirmationControllerDelegate>
{
}

- (void)deleteConfirmationControllerDidCancel:(id)arg1;
- (void)deleteConfirmationControllerDidFinish:(id)arg1;
- (void)feedbackInputControllerDidCancel:(id)arg1;
- (void)feedbackInputController:(id)arg1 didFinishWithFeedbackText:(id)arg2;
- (void)phoneConfirmationControllerDidCancel:(id)arg1;
- (void)phoneConfirmationControllerDidFinish:(id)arg1;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(nonatomic) id <UINavigationControllerDelegate><DeleteAccountControllerDelegate> delegate; // @dynamic delegate;

@end

