//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class NSString, UIButton, UIImageView, UILabel, UITableView, UITableViewCell, UIView, WAProgressHUD;

__attribute__((visibility("hidden")))
@interface DeleteConfirmationController : WAViewController
{
    id <DeleteConfirmationControllerDelegate> _delegate;
    WAProgressHUD *_progressHUD;
    NSString *_feedbackText;
    UITableView *_tableView;
    UIView *_viewThankYou;
    UILabel *_labelThankYou;
    UIView *_viewDeleteButton;
    UIButton *_buttonDelete;
    UITableViewCell *_cellConfirmation;
    UILabel *_labelTitle;
    UILabel *_labelHelperText;
    UIImageView *_imageSadPhone;
}

@property(retain, nonatomic) UIImageView *imageSadPhone; // @synthesize imageSadPhone=_imageSadPhone;
@property(retain, nonatomic) UILabel *labelHelperText; // @synthesize labelHelperText=_labelHelperText;
@property(retain, nonatomic) UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(retain, nonatomic) UITableViewCell *cellConfirmation; // @synthesize cellConfirmation=_cellConfirmation;
@property(retain, nonatomic) UIButton *buttonDelete; // @synthesize buttonDelete=_buttonDelete;
@property(retain, nonatomic) UIView *viewDeleteButton; // @synthesize viewDeleteButton=_viewDeleteButton;
@property(retain, nonatomic) UILabel *labelThankYou; // @synthesize labelThankYou=_labelThankYou;
@property(retain, nonatomic) UIView *viewThankYou; // @synthesize viewThankYou=_viewThankYou;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *feedbackText; // @synthesize feedbackText=_feedbackText;

- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)deleteAction;
- (void)cancelAction:(id)arg1;
- (void)removeHUD;
- (void)showHUD:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

