//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITextViewDelegate.h"

@class UILabel, UITableView, UITableViewCell, UITextView;

__attribute__((visibility("hidden")))
@interface FeedbackInputViewController : WAViewController <UITextViewDelegate>
{
    id <FeedbackInputControllerDelegate> _delegate;
    float _keyboardHeight;
    UITableView *_tableViewFeedback;
    UITableViewCell *_cellFeedbackInput;
    UITextView *_textViewFeedback;
    UILabel *_labelPlaceholder;
}

@property(retain, nonatomic) UILabel *labelPlaceholder; // @synthesize labelPlaceholder=_labelPlaceholder;
@property(retain, nonatomic) UITextView *textViewFeedback; // @synthesize textViewFeedback=_textViewFeedback;
@property(retain, nonatomic) UITableViewCell *cellFeedbackInput; // @synthesize cellFeedbackInput=_cellFeedbackInput;
@property(retain, nonatomic) UITableView *tableViewFeedback; // @synthesize tableViewFeedback=_tableViewFeedback;

- (void)keyboardWillShow:(id)arg1;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)nextAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

