//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "MFMailComposeViewControllerDelegate.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface FileBrowserViewController : WATableViewController <MFMailComposeViewControllerDelegate>
{
    NSString *_path;
    NSArray *_files;
}

@property(retain, nonatomic) NSArray *files; // @synthesize files=_files;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;

- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (BOOL)fileIsDirectory:(id)arg1;
- (id)pathForFile:(id)arg1;
- (void)done:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(int)arg1;

@end

