//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, UILabel, UISegmentedControl, UITableView, UITableViewCell, UIToolbar, UIView;

__attribute__((visibility("hidden")))
@interface ForwardPickerViewController : WAViewController <UITableViewDelegate, UITableViewDataSource>
{
    unsigned int _sourceIndex;
    NSArray *_recents;
    NSArray *_groups;
    NSArray *_broadcasts;
    NSArray *_contactSections;
    int _numberOfContacts;
    BOOL _dataAvailable;
    BOOL _viewDidAppear;
    NSArray *_searchResults;
    id <ForwardPickerDelegate> _delegate;
    int _tag;
    id _userInfo;
    UITableView *_tableViewRecents;
    UIView *_viewNoRecents;
    UITableView *_tableViewGroups;
    UIView *_viewNoGroups;
    UITableView *_tableViewBroadcasts;
    UIView *_viewNoBroadcasts;
    UITableView *_tableViewContacts;
    UIToolbar *_toolbar;
    UISegmentedControl *_segmentedControl;
    UILabel *_labelLoading;
    UITableViewCell *_cellLoading;
    UILabel *_labelNoContacts;
    UITableViewCell *_cellNoContacts;
}

@property(retain, nonatomic) UITableViewCell *cellNoContacts; // @synthesize cellNoContacts=_cellNoContacts;
@property(retain, nonatomic) UILabel *labelNoContacts; // @synthesize labelNoContacts=_labelNoContacts;
@property(retain, nonatomic) UITableViewCell *cellLoading; // @synthesize cellLoading=_cellLoading;
@property(retain, nonatomic) UILabel *labelLoading; // @synthesize labelLoading=_labelLoading;
@property(retain, nonatomic) UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UITableView *tableViewContacts; // @synthesize tableViewContacts=_tableViewContacts;
@property(retain, nonatomic) UIView *viewNoBroadcasts; // @synthesize viewNoBroadcasts=_viewNoBroadcasts;
@property(retain, nonatomic) UITableView *tableViewBroadcasts; // @synthesize tableViewBroadcasts=_tableViewBroadcasts;
@property(retain, nonatomic) UIView *viewNoGroups; // @synthesize viewNoGroups=_viewNoGroups;
@property(retain, nonatomic) UITableView *tableViewGroups; // @synthesize tableViewGroups=_tableViewGroups;
@property(retain, nonatomic) UIView *viewNoRecents; // @synthesize viewNoRecents=_viewNoRecents;
@property(retain, nonatomic) UITableView *tableViewRecents; // @synthesize tableViewRecents=_tableViewRecents;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) int tag; // @synthesize tag=_tag;

- (void)profilePictureUpdated:(id)arg1;
- (void)fontSizeDidChange:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)cancelAction:(id)arg1;
- (void)segmentIndexChanged:(id)arg1;
- (void)searchWithCriteria:(id)arg1;
- (id)confirmationTextForContact:(id)arg1;
- (void)addHelperText:(id)arg1 andImage:(id)arg2 toView:(id)arg3;
- (void)updateSelectedSource;
- (void)checkContactsAvailability:(id)arg1;
- (void)loadContacts;
- (void)loadBroadcasts;
- (void)loadRecentsAndGroups;
- (void)updateTableHeader;
- (BOOL)displaySearchBar;
- (id)currentTableView;
- (void)layoutTextToImageInView:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

