//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "WASinglePhotoPickerControllerDelegate.h"
#import "WebImagePickerDelegate.h"

@class NSString, UIActivityIndicatorView, UIBarButtonItem, UIImageView, WAActivityLabel, WAProgressHUD, WebImagePicker;

__attribute__((visibility("hidden")))
@interface GroupIconViewController : WAViewController <WASinglePhotoPickerControllerDelegate, WebImagePickerDelegate>
{
    WAActivityLabel *_activityLabel;
    UIImageView *_imageViewGroupIcon;
    UIActivityIndicatorView *_activityIndicator;
    WAProgressHUD *_progressHUD;
    WebImagePicker *_webImagePicker;
    UIBarButtonItem *_bbItemPictureAction;
    BOOL _addressBookPictureAllowed;
    BOOL _updating;
    NSString *_jid;
}

+ (id)controllerWithJID:(id)arg1;
@property(readonly, nonatomic) BOOL updating; // @synthesize updating=_updating;
@property(nonatomic) BOOL addressBookPictureAllowed; // @synthesize addressBookPictureAllowed=_addressBookPictureAllowed;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;

- (void)applicationDidEnterBackground:(id)arg1;
- (void)webImagePickerDidCancel:(id)arg1;
- (void)webImagePicker:(id)arg1 didSelectImage:(id)arg2;
- (void)singlePhotoPickerControllerDidCancel:(id)arg1;
- (void)singlePhotoPickerController:(id)arg1 didFinishWithImage:(id)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)pictureAction:(id)arg1;
- (void)editAction:(id)arg1;
- (void)reloadPicture:(BOOL)arg1;
- (void)showImageSearchController;
- (void)showImagePickerForSourceType:(int)arg1;
- (void)deletePicture:(BOOL)arg1;
- (void)hideActivityIndicator;
- (void)showActivityIndicator;
- (void)hideActivity;
- (void)showActivity:(id)arg1;
- (void)removeHUD;
- (void)showHUD:(id)arg1;
- (void)updateNavigationTitle;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

