//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface GroupViewController : WATableViewController
{
    NSMutableArray *_groupList;
    BOOL _showCancelButton;
    id <GroupViewControllerDelegate> _delegate;
}

@property(nonatomic) BOOL showCancelButton; // @synthesize showCancelButton=_showCancelButton;
@property(nonatomic) id <GroupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)cancelAction:(id)arg1;
- (void)dealloc;
- (id)init;

@end

