//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "SoundPickerDelegate.h"

@class NSManagedObjectID, NSString, UISwitch, WAActivityLabel;

__attribute__((visibility("hidden")))
@interface GroupSettingsViewController : WATableViewController <SoundPickerDelegate>
{
    UISwitch *_switchOnOff;
    UISwitch *_switchAlerts;
    WAActivityLabel *_activityLabel;
    NSManagedObjectID *_chatSessionID;
    NSString *_tempSound;
    int _tag;
    int _iPodPlaybackState;
    BOOL _activityInProgress;
    id <GroupSettingsViewControllerDelegate> _delegate;
}

+ (id)controllerWithChatSessionID:(id)arg1 delegate:(id)arg2;
@property(nonatomic) id <GroupSettingsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BOOL activityInProgress; // @synthesize activityInProgress=_activityInProgress;

- (void)settingUpdateFailedWithError:(id)arg1;
- (void)settingUpdateFinished;
- (void)soundPickerDidCancel:(id)arg1;
- (void)soundPicker:(id)arg1 didFinishWithSound:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)switchAlertsAction:(id)arg1;
- (void)switchOnOffAction:(id)arg1;
- (void)updateSettingsOnServer:(int)arg1;
- (void)showSoundPickerController;
- (void)hideActivity;
- (void)showActivity:(id)arg1;
- (id)chatSession;
- (void)dealloc;
- (id)initWithChatSessionID:(id)arg1 delegate:(id)arg2;

@end

