//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSData, NSDictionary, NSFileHandle, NSInputStream, NSMutableData, NSMutableDictionary, NSMutableURLRequest, NSOperationQueue, NSString, NSThread, NSTimer, NSURLConnection, NSURLCredential, NSURLResponse;

__attribute__((visibility("hidden")))
@interface GTMHTTPFetcher : NSObject
{
    NSMutableURLRequest *request_;
    NSURLConnection *connection_;
    NSMutableData *downloadedData_;
    NSString *downloadPath_;
    NSString *temporaryDownloadPath_;
    NSFileHandle *downloadFileHandle_;
    unsigned long long downloadedLength_;
    NSURLCredential *credential_;
    NSURLCredential *proxyCredential_;
    NSArray *allowedCertificates_;
    NSData *postData_;
    NSInputStream *postStream_;
    NSMutableData *loggedStreamData_;
    NSURLResponse *response_;
    id delegate_;
    SEL finishedSel_;
    SEL sentDataSel_;
    SEL receivedDataSel_;
     completionBlock_;
     receivedDataBlock_;
     sentDataBlock_;
     retryBlock_;
    BOOL hasConnectionEnded_;
    BOOL isCancellingChallenge_;
    BOOL isStopNotificationNeeded_;
    BOOL shouldFetchInBackground_;
    unsigned int backgroundTaskIdentifer_;
    id userData_;
    NSMutableDictionary *properties_;
    NSArray *runLoopModes_;
    NSOperationQueue *delegateQueue_;
    id <GTMHTTPFetchHistoryProtocol> fetchHistory_;
    int cookieStorageMethod_;
    id <GTMCookieStorageProtocol> cookieStorage_;
    id <GTMFetcherAuthorizationProtocol> authorizer_;
    id <GTMHTTPFetcherServiceProtocol> service_;
    NSString *serviceHost_;
    int servicePriority_;
    NSThread *thread_;
    BOOL isRetryEnabled_;
    SEL retrySel_;
    NSTimer *retryTimer_;
    unsigned int retryCount_;
    double maxRetryInterval_;
    double minRetryInterval_;
    double retryFactor_;
    double lastRetryInterval_;
    BOOL hasAttemptedAuthRefresh_;
    NSString *comment_;
    NSString *log_;
    NSString *logRequestBody_;
    NSString *logResponseBody_;
    BOOL shouldDeferResponseBodyLogging_;
}

+ (void)setConnectionClass:(Class)arg1;
+ (Class)connectionClass;
+ (BOOL)doesSupportSentDataCallback;
+ (id)staticCookieStorage;
+ (void)initialize;
+ (id)fetcherWithURLString:(id)arg1;
+ (id)fetcherWithURL:(id)arg1;
+ (id)fetcherWithRequest:(id)arg1;
@property BOOL shouldFetchInBackground; // @synthesize shouldFetchInBackground=shouldFetchInBackground_;
@property(copy)  retryBlock; // @synthesize retryBlock=retryBlock_;
@property(copy)  receivedDataBlock; // @synthesize receivedDataBlock=receivedDataBlock_;
@property(copy)  sentDataBlock; // @synthesize sentDataBlock=sentDataBlock_;
@property(copy)  completionBlock; // @synthesize completionBlock=completionBlock_;
@property(retain) id <GTMCookieStorageProtocol> cookieStorage; // @synthesize cookieStorage=cookieStorage_;
@property(copy) NSString *log; // @synthesize log=log_;
@property(copy) NSString *comment; // @synthesize comment=comment_;
@property(retain) NSArray *runLoopModes; // @synthesize runLoopModes=runLoopModes_;
@property(retain) NSOperationQueue *delegateQueue; // @synthesize delegateQueue=delegateQueue_;
@property(retain) NSFileHandle *downloadFileHandle; // @synthesize downloadFileHandle=downloadFileHandle_;
@property(copy) NSString *temporaryDownloadPath; // @synthesize temporaryDownloadPath=temporaryDownloadPath_;
@property(copy) NSString *downloadPath; // @synthesize downloadPath=downloadPath_;
@property(retain) NSData *downloadedData; // @synthesize downloadedData=downloadedData_;
@property(readonly) unsigned long long downloadedLength; // @synthesize downloadedLength=downloadedLength_;
@property(retain) NSURLResponse *response; // @synthesize response=response_;
@property double retryFactor; // @synthesize retryFactor=retryFactor_;
@property SEL retrySelector; // @synthesize retrySelector=retrySel_;
@property SEL receivedDataSelector; // @synthesize receivedDataSelector=receivedDataSel_;
@property SEL sentDataSelector; // @synthesize sentDataSelector=sentDataSel_;
@property(retain) NSThread *thread; // @synthesize thread=thread_;
@property int servicePriority; // @synthesize servicePriority=servicePriority_;
@property(copy) NSString *serviceHost; // @synthesize serviceHost=serviceHost_;
@property(retain) id <GTMHTTPFetcherServiceProtocol> service; // @synthesize service=service_;
@property(retain) id <GTMFetcherAuthorizationProtocol> authorizer; // @synthesize authorizer=authorizer_;
@property(retain) id delegate; // @synthesize delegate=delegate_;
@property(retain) NSInputStream *postStream; // @synthesize postStream=postStream_;
@property(retain) NSData *postData; // @synthesize postData=postData_;
@property(retain) NSArray *allowedCertificates; // @synthesize allowedCertificates=allowedCertificates_;
@property(retain) NSURLCredential *proxyCredential; // @synthesize proxyCredential=proxyCredential_;
@property(retain) NSURLCredential *credential; // @synthesize credential=credential_;
@property(retain) NSMutableURLRequest *mutableRequest; // @synthesize mutableRequest=request_;
- (void)setCommentWithFormat:(id)arg1;
- (void)addPropertiesFromDictionary:(id)arg1;
- (id)propertyForKey:(id)arg1;
- (void)setProperty:(id)arg1 forKey:(id)arg2;
@property(copy) NSMutableDictionary *properties; // @dynamic properties;
@property(retain) id userData; // @dynamic userData;
@property(retain) id <GTMHTTPFetchHistoryProtocol> fetchHistory; // @dynamic fetchHistory;
@property int cookieStorageMethod; // @dynamic cookieStorageMethod;
@property double minRetryInterval; // @dynamic minRetryInterval;
@property double maxRetryInterval; // @dynamic maxRetryInterval;
@property(getter=isRetryEnabled) BOOL retryEnabled; // @dynamic retryEnabled;
@property(readonly) double nextRetryInterval; // @dynamic nextRetryInterval;
@property(readonly) unsigned int retryCount; // @dynamic retryCount;
- (void)destroyRetryTimer;
- (void)retryTimerFired:(id)arg1;
- (void)primeRetryTimerWithNewTimeInterval:(double)arg1;
- (void)beginRetryTimer;
- (BOOL)shouldRetryNowForStatus:(int)arg1 error:(id)arg2;
- (BOOL)isRetryError:(id)arg1;
- (void)logNowWithError:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (BOOL)shouldReleaseCallbacksUponCompletion;
- (void)connectionDidFinishLoading:(id)arg1;
- (int)statusAfterHandlingNotModifiedError;
- (id)cachedDataForStatus;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(int)arg2 totalBytesWritten:(int)arg3 totalBytesExpectedToWrite:(int)arg4;
- (BOOL)invokeRetryCallback:(SEL)arg1 target:(id)arg2 willRetry:(BOOL)arg3 error:(id)arg4;
- (void)invokeSentDataCallback:(SEL)arg1 target:(id)arg2 didSendBodyData:(int)arg3 totalBytesWritten:(int)arg4 totalBytesExpectedToWrite:(int)arg5;
- (void)invokeOnQueueWithDictionary:(id)arg1;
- (void)invokeFetchCallbacksOnDelegateQueueWithData:(id)arg1 error:(id)arg2;
- (void)invokeFetchCallback:(SEL)arg1 target:(id)arg2 data:(id)arg3 error:(id)arg4;
- (void)invokeFetchCallbacksWithData:(id)arg1 error:(id)arg2;
- (BOOL)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)handleCookiesForResponse:(id)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)waitForCompletionWithTimeout:(double)arg1;
- (void)retryFetch;
- (void)sendStopNotificationIfNeeded;
- (void)stopFetching;
- (void)stopFetchReleasingCallbacks:(BOOL)arg1;
- (void)releaseCallbacks;
@property(readonly) NSDictionary *responseHeaders; // @dynamic responseHeaders;
@property(readonly) int statusCode; // @dynamic statusCode;
- (BOOL)isFetching;
- (void)addCookiesToRequest:(id)arg1;
- (id)createTempDownloadFilePathForPath:(id)arg1;
- (BOOL)beginFetchWithCompletionHandler:(id)arg1;
- (void)authorizer:(id)arg1 request:(id)arg2 finishedWithError:(id)arg3;
- (BOOL)authorizeRequest;
- (void)endBackgroundTask;
- (void)backgroundFetchExpired;
- (void)failToBeginFetchWithError:(id)arg1;
- (void)failToBeginFetchDeferWithError:(id)arg1;
- (BOOL)beginFetchMayDelay:(BOOL)arg1 mayAuthorize:(BOOL)arg2;
- (BOOL)beginFetchWithDelegate:(id)arg1 didFinishSelector:(SEL)arg2;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithRequest:(id)arg1;
- (id)init;

@end

