//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

@class UITextField, UIView;

__attribute__((visibility("hidden")))
@interface HostSelector : WATableViewController
{
    UITextField *_textField;
    UIView *_viewHeader;
    id <HostSelectorDelegate> _delegate;
}


- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)doneAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

