//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface KeychainWrapper : NSObject
{
}

+ (BOOL)updateKeychainValue:(id)arg1 forIdentifier:(id)arg2;
+ (BOOL)createKeychainValue:(id)arg1 forIdentifier:(id)arg2;
+ (id)keychainItemMatching:(id)arg1 withAccessibilityControl:(BOOL)arg2;
+ (id)searchDictionary:(id)arg1 withAccessibilityControl:(BOOL)arg2;
+ (void)deleteKeychainValueWithIdentifier:(id)arg1;
+ (void)setKeychainValue:(id)arg1 forIdentifier:(id)arg2;
+ (id)keychainValueWithIdentifier:(id)arg1;

@end

