//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class LabelPickerViewController, NSString;

@protocol LabelPickerViewControllerDelegate
- (void)labelPickerViewControllerDidCancel:(LabelPickerViewController *)arg1;
- (void)labelPickerViewController:(LabelPickerViewController *)arg1 didSelectLabel:(NSString *)arg2;
@end

