//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSDate, NSDateFormatter, NSFileHandle, NSLock, NSString;

__attribute__((visibility("hidden")))
@interface Logger : NSObject
{
    unsigned int _counter;
    NSDateFormatter *_dateFormatter;
    NSFileHandle *_fileHandle;
    NSDate *_creationDate;
    NSLock *_backgroundPurgeLock;
    NSString *_activeLog;
    NSString *_previousLog;
}

+ (id)sharedLogger;
@property(retain, nonatomic) NSString *previousLog; // @synthesize previousLog=_previousLog;
@property(retain, nonatomic) NSString *activeLog; // @synthesize activeLog=_activeLog;

- (id)collect;
- (void)purge;
- (void)flush;
- (void)write:(int)arg1 format:(id)arg2;
- (id)searchLogsAtPath:(id)arg1 fileManager:(id)arg2;
- (id)format:(id)arg1 level:(int)arg2 prefix:(BOOL)arg3;
- (id)logLevelToString:(int)arg1;
- (void)createLogFile;
- (id)header;
- (id)logsDirectory;
- (id)init;

@end

