//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImage, UILabel, WADimmableButton;

__attribute__((visibility("hidden")))
@interface MultilineHeaderView : UIView
{
    UILabel *_labelFirstLine;
    UILabel *_labelSecondLine;
    UILabel *_labelActivity;
    WADimmableButton *_buttonImage;
    UIButton *_buttonAllView;
    UIActivityIndicatorView *_activityIndicator;
    unsigned int _orientation;
    unsigned int _layoutType;
    BOOL _showsActivity;
    BOOL _showImage;
    BOOL _tapable;
    id <MultilineHeaderViewDelegate> _delegate;
}

@property(nonatomic) id <MultilineHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL tapable; // @synthesize tapable=_tapable;
@property(nonatomic) BOOL showImage; // @synthesize showImage=_showImage;
@property(nonatomic) BOOL showsActivity; // @synthesize showsActivity=_showsActivity;
@property(nonatomic) unsigned int layoutType; // @synthesize layoutType=_layoutType;

- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (BOOL)isAccessibilityElement;
- (id)secondLineFontForLayout:(unsigned int)arg1 orientation:(unsigned int)arg2;
- (id)firstLineFontForLayout:(unsigned int)arg1 orientation:(unsigned int)arg2;
@property(retain, nonatomic) UIImage *contactImage;
@property(nonatomic) unsigned int orientation;
@property(retain, nonatomic) NSString *activityText;
@property(retain, nonatomic) NSString *secondLineText;
@property(retain, nonatomic) NSString *firstLineText;
- (void)buttonAllViewAnyTouch:(id)arg1;
- (void)buttonAllViewTouchUp:(id)arg1;
- (void)contactImageTapAction:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 orientation:(unsigned int)arg2;

@end

