//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface NoNetwokViewController : WAViewController
{
    UILabel *_labelWarning;
}

@property(retain, nonatomic) UILabel *labelWarning; // @synthesize labelWarning=_labelWarning;

- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidLoad;
- (id)init;

@end

