//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface NSObject (PerformSelector)
- (void)performSelector:(SEL)arg1 onThread:(id)arg2 waitUntilDone:(BOOL)arg3 objects:(id)arg4;
- (void)handleInvocation:(id)arg1;
@end

