//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Crypto)
- (id)wa_URLEncodedHexToBinary;
- (id)wa_decodedStringWithSalt:(id)arg1;
- (id)wa_encodedStringWithSalt:(id)arg1;
- (id)wa_decodedString;
- (id)wa_encodedString;
- (id)wa_SHA256String;
- (id)wa_MD5String;
- (id)wa_dataValue;
@end

