//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class NSArray, UIActivityIndicatorView, UIBarButtonItem, UILabel, UITableView, UITableViewCell, UIToolbar;

__attribute__((visibility("hidden")))
@interface PeopleViewController : WAViewController
{
    UIBarButtonItem *_buttonSelectAll;
    NSArray *_sections;
    NSArray *_searchResults;
    NSArray *_blockedJIDs;
    int _numberOfContacts;
    int _selectedCount;
    BOOL _dataAvailable;
    int _groupID;
    unsigned int _pickerMode;
    int _selectionLimit;
    NSArray *_selectedContacts;
    id <PeopleViewControllerDelegate> _delegate;
    UITableView *_tableViewContacts;
    UILabel *_labelLoading;
    UITableViewCell *_cellLoading;
    UIActivityIndicatorView *_aiLoading;
    UILabel *_labelContactsTotal;
    UITableViewCell *_cellContactsTotal;
    UILabel *_labelNoContacts;
    UITableViewCell *_cellNoContacts;
    UIToolbar *_toolbarBottom;
    UIBarButtonItem *_buttonSelectDone;
    UIBarButtonItem *_buttonCancel;
}

@property(retain, nonatomic) UIBarButtonItem *buttonCancel; // @synthesize buttonCancel=_buttonCancel;
@property(retain, nonatomic) UIBarButtonItem *buttonSelectDone; // @synthesize buttonSelectDone=_buttonSelectDone;
@property(retain, nonatomic) UIToolbar *toolbarBottom; // @synthesize toolbarBottom=_toolbarBottom;
@property(retain, nonatomic) UITableViewCell *cellNoContacts; // @synthesize cellNoContacts=_cellNoContacts;
@property(retain, nonatomic) UILabel *labelNoContacts; // @synthesize labelNoContacts=_labelNoContacts;
@property(retain, nonatomic) UITableViewCell *cellContactsTotal; // @synthesize cellContactsTotal=_cellContactsTotal;
@property(retain, nonatomic) UILabel *labelContactsTotal; // @synthesize labelContactsTotal=_labelContactsTotal;
@property(retain, nonatomic) UIActivityIndicatorView *aiLoading; // @synthesize aiLoading=_aiLoading;
@property(retain, nonatomic) UITableViewCell *cellLoading; // @synthesize cellLoading=_cellLoading;
@property(retain, nonatomic) UILabel *labelLoading; // @synthesize labelLoading=_labelLoading;
@property(retain, nonatomic) UITableView *tableViewContacts; // @synthesize tableViewContacts=_tableViewContacts;
@property(nonatomic) id <PeopleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *selectedContacts; // @synthesize selectedContacts=_selectedContacts;
@property(nonatomic) int selectionLimit; // @synthesize selectionLimit=_selectionLimit;
@property(nonatomic) unsigned int pickerMode; // @synthesize pickerMode=_pickerMode;
@property(nonatomic) int groupID; // @synthesize groupID=_groupID;

- (void)fontSizeDidChange:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayController:(id)arg1 willHideSearchResultsTableView:(id)arg2;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidUnload;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)selectAllAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)doneSelectingAction:(id)arg1;
- (void)searchWithCriteria:(id)arg1;
- (void)adjustSearchbarPositionAndTableviewInsets;
- (void)alignActivityIndicator;
- (void)checkDataAvailability:(id)arg1;
- (void)setupDisplayList;
- (void)updateTableHeader;
- (BOOL)displaySearchBar;
- (void)formatButtonText;
- (void)dealloc;
- (id)init;

@end

