//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAContactInfoBaseViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSMutableString, UIButton, UILabel, UIView, WAContact, WAMergedContact;

__attribute__((visibility("hidden")))
@interface PersonViewController : WAContactInfoBaseViewController <UIActionSheetDelegate, MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate>
{
    int _displayedContactID;
    NSMutableArray *_personData;
    NSMutableArray *_phonesForFavs;
    NSMutableArray *_phonesForChat;
    NSMutableArray *_phonesWithChatHistory;
    NSMutableArray *_phonesToInvite;
    NSMutableArray *_contactEmails;
    NSMutableString *_contactName;
    WAMergedContact *_mergedContact;
    WAContact *_contact;
    unsigned int _selectedPhoneIndex;
    BOOL _showTableFooter;
    BOOL _enableClearButton;
    UIView *_callHistoryHeaderView;
    NSMutableDictionary *_blockStatusRowInfo;
    BOOL _showMergedContact;
    BOOL _hasLinkedContacts;
    UIView *_headerView;
    UIButton *_buttonProfilePhoto;
    UIView *_titlesView;
    UILabel *_textLabelFullName;
    UILabel *_textLabelPhonetic;
    UILabel *_textLabelNickname;
    UILabel *_textLabelJob;
    UILabel *_textLabelCompany;
}

+ (id)sharedTimePeriodFormatter;
@property(retain, nonatomic) UILabel *textLabelCompany; // @synthesize textLabelCompany=_textLabelCompany;
@property(retain, nonatomic) UILabel *textLabelJob; // @synthesize textLabelJob=_textLabelJob;
@property(retain, nonatomic) UILabel *textLabelNickname; // @synthesize textLabelNickname=_textLabelNickname;
@property(retain, nonatomic) UILabel *textLabelPhonetic; // @synthesize textLabelPhonetic=_textLabelPhonetic;
@property(retain, nonatomic) UILabel *textLabelFullName; // @synthesize textLabelFullName=_textLabelFullName;
@property(retain, nonatomic) UIView *titlesView; // @synthesize titlesView=_titlesView;
@property(retain, nonatomic) UIButton *buttonProfilePhoto; // @synthesize buttonProfilePhoto=_buttonProfilePhoto;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;

- (void)setAggregateCallEvent:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)chatStorageDidUpdateChatSession:(id)arg1;
- (void)didAddMessages;
- (void)updateClearButtonsWithAnimation:(BOOL)arg1;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)chatWithContact;
- (void)startChatWithPhoneID:(id)arg1 contact:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)addToFavorites;
- (void)addPhoneToFavorites:(id)arg1;
- (void)setUpMediaManager;
- (void)clearChatHistory;
- (void)emailChatHistory;
- (void)askToAttachMedia;
- (void)emailChatHistoryWithMedia:(BOOL)arg1;
- (void)inviteContact;
- (void)inviteViaSMS;
- (void)emailToAddress:(id)arg1 subject:(id)arg2 body:(id)arg3;
- (void)launchMailAppOnDevice:(id)arg1 subject:(id)arg2 body:(id)arg3;
- (void)displayComposerSheet:(id)arg1 subject:(id)arg2 body:(id)arg3;
- (void)callerBlockedStatusDidChange;
- (void)updateBlockStatusRowInfo;
- (void)setUpUnknownContactData;
- (void)setupPersonData;
- (void)setupPersonViewHeader;
- (void)prepareMergedContactIfNeeded;
- (void)reloadProfilePhoto;
- (void)reload;
- (void)reloadWithContact:(id)arg1;
- (void)viewProfilePhoto:(id)arg1;
- (id)initWithContact:(id)arg1 merged:(BOOL)arg2 whatsAppID:(id)arg3 detailText:(id)arg4;

@end

