//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, WAContactNameLabel;

__attribute__((visibility("hidden")))
@interface PersonTableViewCell : UITableViewCell
{
    BOOL _personSelected;
    UIImageView *_imageViewCheckMark;
    WAContactNameLabel *_nameLabel;
    UILabel *_statusLabel;
    UILabel *_detailLabel;
}

@property(nonatomic) BOOL personSelected; // @synthesize personSelected=_personSelected;
@property(readonly, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(readonly, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(readonly, nonatomic) WAContactNameLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(readonly, nonatomic) UIImageView *imageViewCheckMark; // @synthesize imageViewCheckMark=_imageViewCheckMark;

- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)updateBackgroundColor;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

