//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface PhoneNumberFormatter : NSObject
{
}

+ (id)clearNumber:(id)arg1;
+ (BOOL)phoneNumber:(id)arg1 meetsMinimumLengthRequirementOfCountry:(id)arg2;
+ (id)formatNumber:(id)arg1 withIsoCode:(id)arg2;
+ (id)formatNumber:(id)arg1;
+ (id)isoCodeFromCountryCode:(id)arg1;
+ (id)countryInfoByCountryCode:(id)arg1;
+ (id)countryInfoByMCC:(id)arg1;
+ (id)countryInfoByIsoCode:(id)arg1;
+ (id)preferredCountries;
+ (id)allCountries;
+ (void)initializeFormatter;
+ (id)removeDigits:(int)arg1 atEndOfString:(id)arg2;
+ (id)formatNationalNumber:(id)arg1 withCountryInfo:(id)arg2;
+ (id)countryInfoFromNumber:(id)arg1;
+ (id)countryInfoFromRawNumber:(id)arg1;
+ (BOOL)nationalNumber:(id)arg1 containsLeadingDigits:(id)arg2;

@end

