//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "ProblemInputControllerDelegate.h"
#import "WACountryPickerControllerDelegate.h"
#import "WAPhoneNumberTextFieldDelegate.h"

@class CountryInfo, NSDictionary, NSMutableString, NSString, UIAlertView, UIImageView, UILabel, UITextField, UIView, WAOverlayView, WAPhoneNumberTextField;

__attribute__((visibility("hidden")))
@interface PhoneInputViewController : WATableViewController <WACountryPickerControllerDelegate, ProblemInputControllerDelegate, MFMailComposeViewControllerDelegate, WAPhoneNumberTextFieldDelegate>
{
    CountryInfo *_selectedCountry;
    NSMutableString *_actualPhoneNumber;
    NSDictionary *_urlParameters;
    UIAlertView *_phoneConfirmAlert;
    NSString *_contextFailReason;
    WAOverlayView *_overlayView;
    id <PhoneInputViewControllerDelegate> _delegate;
    BOOL _registrationUI;
    UIView *_headerView;
    UILabel *_labelHeaderText;
    UIView *_footerView;
    UILabel *_labelFooterText;
    UIView *_viewInputFieldsContainer;
    UIView *_viewCCodeContainer;
    UILabel *_labelPlusSign;
    UILabel *_labelCCode;
    UITextField *_textFieldCode;
    UIImageView *_imageCodeBg;
    UIView *_viewPhoneNumberContainer;
    WAPhoneNumberTextField *_phoneNumberTextField;
    UIImageView *_imagePhoneBg;
}

@property(retain, nonatomic) UIImageView *imagePhoneBg; // @synthesize imagePhoneBg=_imagePhoneBg;
@property(retain, nonatomic) WAPhoneNumberTextField *phoneNumberTextField; // @synthesize phoneNumberTextField=_phoneNumberTextField;
@property(retain, nonatomic) UIView *viewPhoneNumberContainer; // @synthesize viewPhoneNumberContainer=_viewPhoneNumberContainer;
@property(retain, nonatomic) UIImageView *imageCodeBg; // @synthesize imageCodeBg=_imageCodeBg;
@property(retain, nonatomic) UITextField *textFieldCode; // @synthesize textFieldCode=_textFieldCode;
@property(retain, nonatomic) UILabel *labelCCode; // @synthesize labelCCode=_labelCCode;
@property(retain, nonatomic) UILabel *labelPlusSign; // @synthesize labelPlusSign=_labelPlusSign;
@property(retain, nonatomic) UIView *viewCCodeContainer; // @synthesize viewCCodeContainer=_viewCCodeContainer;
@property(retain, nonatomic) UIView *viewInputFieldsContainer; // @synthesize viewInputFieldsContainer=_viewInputFieldsContainer;
@property(retain, nonatomic) UILabel *labelFooterText; // @synthesize labelFooterText=_labelFooterText;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UILabel *labelHeaderText; // @synthesize labelHeaderText=_labelHeaderText;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) BOOL registrationUI; // @synthesize registrationUI=_registrationUI;

- (void)deviceCheckFailedWithError:(id)arg1;
- (void)deviceCheckFinishedWithResult:(id)arg1;
- (void)launchedFromUrl:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)probleminputControllerDidCancel:(id)arg1;
- (void)problemInputController:(id)arg1 didFinishWithText:(id)arg2 attachment:(id)arg3;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)countryPicker:(id)arg1 didSelectCountry:(id)arg2;
- (void)phoneNumberTextFieldDidChange:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)verificationCodeFromUrl;
- (void)resetPhoneNumber;
- (void)cancelAction:(id)arg1;
- (void)doneAction:(id)arg1;
- (void)codeChangedAction:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)confirmNewChat;
- (void)composeEmail:(id)arg1;
- (void)showAppStoreAlert:(id)arg1;
- (void)showContactSupportAlert:(id)arg1;
- (void)requestAuthCode;
- (void)performSameDeviceCheck;
- (void)resizeHelperTextLabels;
- (void)formatCodeField;
- (void)formatTitle;
- (void)validateUserInput;
- (void)showOverlay:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

