//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString, ProblemInputController;

@protocol ProblemInputControllerDelegate <NSObject>
- (void)probleminputControllerDidCancel:(ProblemInputController *)arg1;
- (void)problemInputController:(ProblemInputController *)arg1 didFinishWithText:(NSString *)arg2 attachment:(NSString *)arg3;
@end

