//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITextFieldDelegate.h"
#import "WASinglePhotoPickerControllerDelegate.h"

@class ACAccount, ACAccountStore, GroupIconViewController, UIActivityIndicatorView, UIButton, UIImage, UIImageView, UILabel, UITableView, UITableViewCell, UITextField, UIView, WAProgressHUD;

__attribute__((visibility("hidden")))
@interface ProfileViewController : WAViewController <WASinglePhotoPickerControllerDelegate, UITextFieldDelegate>
{
    UIImage *_tempProfilePicture;
    UIActivityIndicatorView *_aiGroupIcon;
    WAProgressHUD *_progressHUD;
    int _networkActivities;
    BOOL _modal;
    BOOL _photoModified;
    BOOL _showFBSection;
    BOOL _showProfilePhotoReminder;
    GroupIconViewController *_groupIconViewController;
    ACAccountStore *_accountStore;
    ACAccount *_fbAccount;
    struct UIEdgeInsets _originalContentInset;
    float _keyboardHeight;
    BOOL _useDeviceName;
    id <ProfileViewControllerDelegate> _delegate;
    UITableView *_tableViewProfile;
    UIView *_viewTableHeader;
    UILabel *_labelHelperText;
    UIView *_viewProfilePhoto;
    UIImageView *_imageProfilePhoto;
    UIButton *_buttonAddPhoto;
    UIButton *_buttonEditPhoto;
    UITableViewCell *_cellPushName;
    UITextField *_textFieldName;
    UIView *_viewFacebookTitle;
    UILabel *_labelFacebookTitle;
}

@property(retain, nonatomic) UILabel *labelFacebookTitle; // @synthesize labelFacebookTitle=_labelFacebookTitle;
@property(retain, nonatomic) UIView *viewFacebookTitle; // @synthesize viewFacebookTitle=_viewFacebookTitle;
@property(retain, nonatomic) UITextField *textFieldName; // @synthesize textFieldName=_textFieldName;
@property(retain, nonatomic) UITableViewCell *cellPushName; // @synthesize cellPushName=_cellPushName;
@property(retain, nonatomic) UIButton *buttonEditPhoto; // @synthesize buttonEditPhoto=_buttonEditPhoto;
@property(retain, nonatomic) UIButton *buttonAddPhoto; // @synthesize buttonAddPhoto=_buttonAddPhoto;
@property(retain, nonatomic) UIImageView *imageProfilePhoto; // @synthesize imageProfilePhoto=_imageProfilePhoto;
@property(retain, nonatomic) UIView *viewProfilePhoto; // @synthesize viewProfilePhoto=_viewProfilePhoto;
@property(retain, nonatomic) UILabel *labelHelperText; // @synthesize labelHelperText=_labelHelperText;
@property(retain, nonatomic) UIView *viewTableHeader; // @synthesize viewTableHeader=_viewTableHeader;
@property(retain, nonatomic) UITableView *tableViewProfile; // @synthesize tableViewProfile=_tableViewProfile;
@property(nonatomic) id <ProfileViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL useDeviceName; // @synthesize useDeviceName=_useDeviceName;

- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)adjustContentInsetForKeyboardHeight:(float)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textFieldShouldEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)singlePhotoPickerControllerDidCancel:(id)arg1;
- (void)singlePhotoPickerController:(id)arg1 didFinishWithImage:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)deleteProfilePhoto;
- (void)showImagePickerForSourceType:(int)arg1;
- (void)showProfilePhotoActivity:(BOOL)arg1;
- (void)reloadProfilePicture;
- (void)requestFBAccess;
- (void)renewCredentialsForAccount:(id)arg1;
- (void)importUsernameFromFBAccount:(id)arg1 accountRenewed:(BOOL)arg2;
- (void)importProfilePhotoFromFBAccount:(id)arg1;
- (void)processFBPicture:(id)arg1;
- (void)processFBAccountInfo:(id)arg1;
- (void)checkFBCompletion;
- (void)cancelAction:(id)arg1;
- (void)doneAction:(id)arg1;
- (void)textFieldValueChanged:(id)arg1;
- (void)editPhotoAction:(id)arg1;
- (void)removeHUD;
- (void)showHUD:(id)arg1;
- (void)layoutFBHelperText;
- (void)checkProfilePictureActivity:(id)arg1;
- (void)updateTextFieldValues;
- (void)validateUserInput;
- (void)updateUI;
- (void)dealloc;
- (id)initWithProfileContollerDelegate:(id)arg1;

@end

