//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "AVAudioPlayerDelegate.h"

@class AVAudioPlayer, NSArray, NSIndexPath, NSMutableDictionary, NSString, UILabel;

__attribute__((visibility("hidden")))
@interface SoundPicker : WATableViewController <AVAudioPlayerDelegate>
{
    NSArray *_soundSets;
    NSIndexPath *_indexPathForSelectedSound;
    NSMutableDictionary *_audioPlayers;
    AVAudioPlayer *_currentPlayer;
    id <SoundPickerDelegate> _delegate;
    int _tag;
    NSString *_viewTitle;
    UILabel *_navItemTitle;
}

@property(retain, nonatomic) UILabel *navItemTitle; // @synthesize navItemTitle=_navItemTitle;
@property(retain, nonatomic) NSString *viewTitle; // @synthesize viewTitle=_viewTitle;
@property(nonatomic) int tag; // @synthesize tag=_tag;

- (void)cancelAction:(id)arg1;
- (void)saveAction:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)adjustTitleFont;
- (void)fadeOut;
- (id)audioPlayerForFilename:(id)arg1;
- (id)audioPlayers;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 selectedSoundFilename:(id)arg2 soundSets:(id)arg3;

@end

