//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SoundPicker, WAPushSound;

@protocol SoundPickerDelegate
- (void)soundPickerDidCancel:(SoundPicker *)arg1;
- (void)soundPicker:(SoundPicker *)arg1 didFinishWithSound:(WAPushSound *)arg2;
@end

