//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, StatusEditController;

@protocol StatusEditControllerDelegate
- (void)statusEditControllerDidCancel:(StatusEditController *)arg1;
- (void)statusEditController:(StatusEditController *)arg1 didSaveStatus:(NSDictionary *)arg2;
- (void)statusEditController:(StatusEditController *)arg1 didAddStatus:(NSDictionary *)arg2;
@end

