//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSDate;

__attribute__((visibility("hidden")))
@interface Stat : NSObject
{
    int _messagesSent;
    int _messagesReceived;
    NSDate *_lastReset;
    long long _mediaBytesSent;
    long long _mediaBytesReceived;
    long long _systemBytesSent;
    long long _systemBytesReceived;
}

+ (id)sharedManager;
@property(readonly, nonatomic) NSDate *lastReset; // @synthesize lastReset=_lastReset;
@property(nonatomic) int messagesReceived; // @synthesize messagesReceived=_messagesReceived;
@property(nonatomic) int messagesSent; // @synthesize messagesSent=_messagesSent;
@property(nonatomic) long long systemBytesReceived; // @synthesize systemBytesReceived=_systemBytesReceived;
@property(nonatomic) long long systemBytesSent; // @synthesize systemBytesSent=_systemBytesSent;
@property(nonatomic) long long mediaBytesReceived; // @synthesize mediaBytesReceived=_mediaBytesReceived;
@property(nonatomic) long long mediaBytesSent; // @synthesize mediaBytesSent=_mediaBytesSent;

- (void)reset:(BOOL)arg1;
- (void)save;
- (id)init;

@end

