//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

__attribute__((visibility("hidden")))
@interface TwoLineTableViewCell : UITableViewCell
{
}

+ (float)heightWithText:(id)arg1 textFont:(id)arg2 detailText:(id)arg3 detailTextFont:(id)arg4 forWidth:(float)arg5;
- (void)layoutSubviews;

@end

