//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface UIApplication (BackgroundAdditions)
+ (BOOL)iOS7;
- (id)wa_statusBarView;
- (BOOL)wa_blurEffectsEnabled;
- (id)packageHash;
- (id)cachesDirectory;
- (id)libraryDirectory;
- (id)documentsDirectory;
- (id)topMostWindow;
- (id)httpUserAgentString;
- (id)versionString;
- (void)wa_showLocalNotificationForJailbrokenPhoneAndTerminate;
- (void)clearLocalNotifications;
- (void)showLocalNotification:(id)arg1 hasAction:(BOOL)arg2 alertAction:(id)arg3 fireDate:(id)arg4;
- (BOOL)isActive;
- (BOOL)isBackgrounded;
- (void)setupEnv;
- (BOOL)isDirty;
@end

