//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (machine)
- (BOOL)wa_shouldBeAskedToReview;
- (id)wa_memoryInfo;
- (id)mapsUrl;
- (long long)freeDiskSpace;
- (double)estimatedMigrationTimeForDatabaseSize:(unsigned long long)arg1;
- (BOOL)wa_hasMulticoreProcessor;
- (id)modelName;
- (id)machine;
- (BOOL)wa_isDeviceSuspicious;
- (id)wa_deviceInfoForXMPPAuth;
@end

