//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Bubbles)
+ (id)blueBubbleOut;
+ (id)blueBubbleIn;
+ (id)blueBubble;
+ (id)greenBubbleOutHighlighted;
+ (id)greenBubbleOut;
+ (id)grayBubbleInHighlighted;
+ (id)grayBubbleIn;
+ (void)wa_makeAllBubblesiOS7;
+ (void)wa_makeAllBubblesiOS6;
+ (void)wa_makeAllBubbles;
+ (struct UIEdgeInsets)wa_incomingBubbleInset;
+ (struct UIEdgeInsets)wa_outgoingBubbleInset;
@end

