//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Additions)
- (void)wa_snapToPixelOrigin;
@property(readonly, nonatomic) float screenY;
@property(readonly, nonatomic) float screenX;
- (id)ancestorOrSelfWithClass:(Class)arg1;
@property(nonatomic) struct CGSize size;
@property(nonatomic) struct CGPoint origin;
@property(nonatomic) float height;
@property(nonatomic) float width;
@property(nonatomic) float centerY;
@property(nonatomic) float centerX;
@property(nonatomic) float bottom;
@property(nonatomic) float right;
@property(nonatomic) float top;
@property(nonatomic) float left;
- (id)snapshotImage;
@end

