//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAModalNavigationController.h"

#import "ChangeConfirmationControllerDelegate.h"
#import "ChangeNumberInputControllerDelegate.h"
#import "PassInputViewControllerDelegate.h"
#import "PaymentEduControllerDelegate.h"
#import "PhoneInputViewControllerDelegate.h"
#import "ProfileViewControllerDelegate.h"
#import "RestoreBackupViewControllerDelegate.h"
#import "WAAutobackupSettingsViewControllerDelegate.h"

@class PassInputViewController, PaymentEduViewController, PhoneInputViewController, ProfileViewController, RestoreBackupViewController, WAAutobackupSettingsViewController, iPadNoticeViewController;

__attribute__((visibility("hidden")))
@interface VerificationController : WAModalNavigationController <PhoneInputViewControllerDelegate, PassInputViewControllerDelegate, ProfileViewControllerDelegate, RestoreBackupViewControllerDelegate, ChangeConfirmationControllerDelegate, ChangeNumberInputControllerDelegate, PaymentEduControllerDelegate, WAAutobackupSettingsViewControllerDelegate>
{
    PhoneInputViewController *_phoneInputController;
    PassInputViewController *_passInputController;
    iPadNoticeViewController *_iPadNoticeController;
    ProfileViewController *_profileViewController;
    RestoreBackupViewController *_restoreBackupViewController;
    PaymentEduViewController *_paymentEduViewController;
    WAAutobackupSettingsViewController *_autobackupSettingsController;
    unsigned int _mode;
}

+ (void)cancelPhoneNumberChange;
+ (void)updateDefaultsAndKeychain:(id)arg1 password:(id)arg2;
+ (BOOL)autobackupOff;
+ (BOOL)pushNameAndProfilePhotoAreValid;
+ (BOOL)validateProfileAndSettingsOnUpgrade;
@property(readonly, nonatomic) unsigned int mode; // @synthesize mode=_mode;

- (void)autobackupSettingsControllerDidFinish:(id)arg1;
- (void)changeNumberInputControllerDidCancel:(id)arg1;
- (void)changeNumberInputControllerDidEnterPhone:(id)arg1;
- (void)changeNumberInputControllerDidFinish:(id)arg1;
- (void)changeConfirmationControllerDidCancel:(id)arg1;
- (void)changeConfirmationControllerDidFinish:(id)arg1;
- (void)restoreBackupViewControllerDidFinish:(id)arg1;
- (void)paymentEduControllerDidFinish:(id)arg1;
- (void)profileViewControllerDidFinish:(id)arg1;
- (void)passInputViewControllerDidCancel:(id)arg1;
- (void)passInputViewControllerDidFinish:(id)arg1;
- (void)phoneInputViewControllerDidFinish:(id)arg1;
- (void)phoneInputViewControllerDidEnterPhone:(id)arg1;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)goToPaymentEducationScreen:(id)arg1;
- (void)goToProfileScreen:(id)arg1;
- (void)verifiedAfterInstallGoToNextScreen:(id)arg1;
- (void)resetPhoneNumber;
- (id)autobackupSettingsController;
- (id)paymentEduViewController;
- (id)restoreBackupViewController;
- (id)profileViewController;
- (id)passInputController;
- (id)phoneInputController;
- (id)iPadNoticeController;
- (id)init;
- (id)initWithMode:(unsigned int)arg1;

// Remaining properties
@property(nonatomic) id <VerificationControllerDelegate><UINavigationControllerDelegate> delegate;

@end

