//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface WAAlertStyleTableViewCell : UITableViewCell
{
    NSMutableArray *_optionViews;
    BOOL _disabled;
    unsigned int _selectedAlertStyle;
     _handler;
}

@property(copy, nonatomic)  handler; // @synthesize handler=_handler;
@property(nonatomic) BOOL disabled; // @synthesize disabled=_disabled;
@property(nonatomic) unsigned int selectedAlertStyle; // @synthesize selectedAlertStyle=_selectedAlertStyle;

- (float)rowHeight;
- (void)optionViewTapped:(id)arg1;
- (void)layoutSubviews;
- (void)updateSelectionState;
- (void)configure;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

