//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CALayer, NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface WAAnimatedCancelLabel : UIView
{
    UILabel *_label;
    UIImageView *_slideArrow;
    BOOL _animating;
    CALayer *_maskLayer;
}

+ (id)labelFontOfSize:(float)arg1;
+ (float)defaultFontSize;

- (void)stopAnimating;
- (void)startAnimating;
- (BOOL)isAnimating;
@property(copy, nonatomic) NSString *text;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

