//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface WAAssetsLibraryManager : NSObject
{
}

+ (void)showNoPhotoLibraryAccessAlertView;
+ (id)resizedImageForSending:(id)arg1;
+ (void)saveNextPhotoInQueueToCameraRoll;
+ (void)savePhotoAtPathToCameraRoll:(id)arg1;
+ (void)endDeferringSavingPhotosToCameraRoll;
+ (void)beginDeferringSavingPhotosToCameraRoll;
+ (void)loadBestEditedImageForAssetURL:(id)arg1 completion:(id)arg2;
+ (id)bestEditedImageForAssetURL:(id)arg1;
+ (void)creationDateForAssetURL:(id)arg1 completion:(id)arg2;
+ (void)countOfAssetsInAssetsGroup:(id)arg1 completion:(id)arg2;
+ (id)fullScreenImageAtAssetURL:(id)arg1;
+ (void)loadFullScreenImageForAssetURL:(id)arg1 completion:(id)arg2;
+ (id)allAssetsInAssetsGroup:(id)arg1;
+ (void)fetchAllAssetsFromAssetsGroup:(id)arg1 completion:(id)arg2;
+ (id)allAssetsGroupsForMediaTypes:(unsigned int)arg1;
+ (void)fetchAllAssetsGroupsForMediaTypes:(unsigned int)arg1 completion:(id)arg2;
+ (void)checkUserPermissionWithCompletionHandler:(id)arg1;
+ (id)assetsGroupForURL:(id)arg1;
+ (void)assetsGroupForURL:(id)arg1 completion:(id)arg2;
+ (id)assetForURL:(id)arg1;
+ (void)assetForURL:(id)arg1 completion:(id)arg2;
+ (id)assetsFilterForMediaType:(unsigned int)arg1;
+ (int)videosInCameraRollCount;
+ (int)photosInCameraRollCount;
+ (BOOL)authorizationGranted;
+ (id)sharedAssetsLibrary;
+ (void)initialize;

@end

