//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

__attribute__((visibility("hidden")))
@interface WAAutoCropImageView : UIImageView
{
    float _cropInset;
    struct CGPoint _focusPoint;
}

@property(nonatomic) float cropInset; // @synthesize cropInset=_cropInset;
@property(nonatomic) struct CGPoint focusPoint; // @synthesize focusPoint=_focusPoint;
@property(readonly, nonatomic) struct CGRect contentsRect;
- (void)updateContentsRect;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

