//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

@class NSString, WATableRow;

__attribute__((visibility("hidden")))
@interface WAAutoDownloadSettingsViewController : WAStaticTableViewController
{
    NSString *_autoDownloadImagesString;
    NSString *_autoDownloadAudioString;
    NSString *_autoDownloadVideosString;
    NSString *_autoDownloadNeverString;
    NSString *_autoDownloadWifiString;
    NSString *_autoDownloadCellularString;
    WATableRow *_imageRow;
    WATableRow *_audioRow;
    WATableRow *_videoRow;
}


- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)updateSettingsDisplay;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(int)arg1;

@end

