//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIColor, UIImageView, WAMessageStatusView;

__attribute__((visibility("hidden")))
@interface WABubbleView : UIView
{
    BOOL _incoming;
    BOOL _dimmed;
    id <WABubbleViewDelegate> _delegate;
    WAMessageStatusView *_messageStatusView;
    int _maxWidth;
    NSString *_fromName;
    NSString *_pushName;
    UIColor *_nameColor;
    UIImageView *_listIconImageView;
}

+ (void)drawDividerAtPoint:(struct CGPoint)arg1 width:(float)arg2;
@property(readonly, nonatomic) UIImageView *listIconImageView; // @synthesize listIconImageView=_listIconImageView;
@property(retain, nonatomic) UIColor *nameColor; // @synthesize nameColor=_nameColor;
@property(retain, nonatomic) NSString *pushName; // @synthesize pushName=_pushName;
@property(retain, nonatomic) NSString *fromName; // @synthesize fromName=_fromName;
@property(nonatomic) int maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic, getter=isDimmed) BOOL dimmed; // @synthesize dimmed=_dimmed;
@property(readonly, nonatomic, getter=isIncoming) BOOL incoming; // @synthesize incoming=_incoming;
@property(readonly, nonatomic) WAMessageStatusView *messageStatusView; // @synthesize messageStatusView=_messageStatusView;
@property(nonatomic) id <WABubbleViewDelegate> delegate; // @synthesize delegate=_delegate;

- (id)accessibilityLabel;
- (struct CGRect)accessibilityFrame;
- (BOOL)isAccessibilityElement;
- (void)handleSingleTap;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)menuControllerDidHideMenu:(id)arg1;
- (void)showPopupMenu;
- (void)replyMessageSender:(id)arg1;
- (void)addMessageSenderToContacts:(id)arg1;
- (void)forwardMessage:(id)arg1;
- (void)deleteMessage:(id)arg1;
- (void)copyMessage:(id)arg1;
@property(nonatomic) BOOL listIconHidden;
@property(retain, nonatomic) NSString *timestampString;
@property(nonatomic) unsigned int messageStatus;
- (id)shortName;
- (void)setDimmed:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithIncomingState:(BOOL)arg1 delegate:(id)arg2;

@end

