//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface WACallHistoryTableViewCell : UITableViewCell
{
    UIImageView *_outgoingCallIconView;
    UILabel *_dateLabel;
    UILabel *_eventCountLabel;
    UILabel *_displayNameLabel;
    UILabel *_detailLabel;
}

+ (struct UIEdgeInsets)preferredSeparatorInset;
+ (float)preferredRowHeight;
+ (id)cellWithReuseIdentifier:(id)arg1;
+ (void)initialize;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *displayNameLabel; // @synthesize displayNameLabel=_displayNameLabel;
@property(readonly, nonatomic) UILabel *eventCountLabel; // @synthesize eventCountLabel=_eventCountLabel;
@property(readonly, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(readonly, nonatomic) UIImageView *outgoingCallIconView; // @synthesize outgoingCallIconView=_outgoingCallIconView;

- (void)configureWithAggregateCallEvent:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

