//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImagePickerController.h"

__attribute__((visibility("hidden")))
@interface WACameraOnlyImagePickerController : UIImagePickerController
{
}

+ (BOOL)_reviewCapturedItems;
- (id)statusBarView;
- (void)viewWillDisappear:(BOOL)arg1;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;

@end

