//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class NSTimer, UIView, _WAMaximizeButtonView;

__attribute__((visibility("hidden")))
@interface WACallWindow : UIWindow
{
    _WAMaximizeButtonView *_maximizeButtonView;
    UIView *_statusBarBackgroundView;
    UIView *_backgroundContainerView;
    int _lastInterfaceOrientation;
    struct CGPoint _initialMaximizeButtonCenter;
    BOOL _minimized;
    NSTimer *_updateTimer;
}


- (void)handleUpdateTimer:(id)arg1;
- (void)stopUpdatingMaximizeButton;
- (void)startUpdatingMaximizeButton;
- (void)maximize;
- (void)maximizeButtonTapped:(id)arg1;
- (void)statusBarTapped:(id)arg1;
- (void)minimizeFromPoint:(struct CGPoint)arg1 withAnimation:(BOOL)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)handleMaximizeButtonPan:(id)arg1;
- (void)deviceOrientationDidChange:(id)arg1;
- (int)interfaceOrientationFromCurrentStatusBarFrame;
- (void)layoutSubviews;
- (void)observeDeviceOrientationChanges;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

