//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class UIImage, WAChatBarManager;

@protocol WAChatBarManagerDelegate <NSObject>
- (void)chatBarManager:(WAChatBarManager *)arg1 didCancelPTTRecordingByUser:(BOOL)arg2;
- (void)chatBarManagerDidEndPTTRecording:(WAChatBarManager *)arg1;
- (double)chatBarManagerWillEndPTTRecording:(WAChatBarManager *)arg1;
- (void)chatBarManagerDidBeginPTTRecording:(WAChatBarManager *)arg1;
- (BOOL)chatBarManagerShouldBeginPTTRecording:(WAChatBarManager *)arg1;
- (void)chatBarManagerWantsToPresentCamera:(WAChatBarManager *)arg1;
- (void)chatBarManagerWantsToAttachMedia:(WAChatBarManager *)arg1;
- (void)chatBarManager:(WAChatBarManager *)arg1 didPasteImage:(UIImage *)arg2;
- (void)chatBarManager:(WAChatBarManager *)arg1 didEndDraggingChatBarWithAdditionalTranslation:(float)arg2 finalBottomInset:(float)arg3;
- (void)chatBarManagerWillBeginDraggingChatBar:(WAChatBarManager *)arg1;
- (void)chatBarManagerWantsToScrollToTop:(WAChatBarManager *)arg1;
- (void)chatBarManagerUserDidFocusChatBar:(WAChatBarManager *)arg1;
- (BOOL)chatBarManagerDelegateIsDisappearing:(WAChatBarManager *)arg1;
- (BOOL)chatBarManagerDelegateIsAppearing:(WAChatBarManager *)arg1;
- (void)chatBarManager:(WAChatBarManager *)arg1 needsAdjustBottomInset:(float)arg2 withScrolling:(BOOL)arg3;
- (BOOL)chatBarManagerUserDidSubmitText:(WAChatBarManager *)arg1;
- (void)chatBarManagerDidChangeText:(WAChatBarManager *)arg1;
- (float)chatBarManagerMaximumHeight:(WAChatBarManager *)arg1;
@end

