//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "WAInputTextViewDelegate.h"

@class NSString, UIButton, UIImageView, UILabel, UILongPressGestureRecognizer, UIPanGestureRecognizer, UIScrollView, UITapGestureRecognizer, UITextView, WAAnimatedCancelLabel, WAInputTextView;

__attribute__((visibility("hidden")))
@interface WAChatBar : UIView <WAInputTextViewDelegate>
{
    BOOL _sendButtonHidden;
    UIView *_contentView;
    UIView *_backgroundView;
    UIView *_inputBoxView;
    WAInputTextView *_inputTextView;
    UIView *_placeholderTapReceiverView;
    struct CGPoint _selectionPoint;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIPanGestureRecognizer *_placeholderChatBarPanGestureRecognizer;
    UIPanGestureRecognizer *_chatBarPanGestureRecognizer;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    BOOL _clearingTextViewAfterSendingMessage;
    UIImageView *_dividerImageView;
    UIScrollView *_statusBarTapDetectionScrollView;
    UILabel *_pttRecordingProgressLabel;
    WAAnimatedCancelLabel *_pttSlideToCancelLabel;
    UIView *_pttSlideToCancelLabelMaskView;
    UIImageView *_pttMic;
    UIImageView *_pttMicInactive;
    UIImageView *_pttBucket;
    UIImageView *_pttBucketLid;
    struct CGPoint _pttButtonOriginalTouchPoint;
    BOOL _isPlaceholder;
    BOOL _pttRecordingIsActive;
    BOOL _receivedLongPress;
    BOOL _editingEnabled;
    id <WAChatBarDelegate> _delegate;
    UIButton *_sendButton;
    UIButton *_attachMediaButton;
    UIButton *_cameraButton;
    UIButton *_pttButton;
}

+ (float)minimumHeight;
+ (float)preferredInitialHeight;
@property(nonatomic) BOOL editingEnabled; // @synthesize editingEnabled=_editingEnabled;
@property(nonatomic) BOOL receivedLongPress; // @synthesize receivedLongPress=_receivedLongPress;
@property(readonly, nonatomic) BOOL pttRecordingIsActive; // @synthesize pttRecordingIsActive=_pttRecordingIsActive;
@property(readonly, nonatomic) UITextView *inputTextView; // @synthesize inputTextView=_inputTextView;
@property(readonly, nonatomic) UIButton *pttButton; // @synthesize pttButton=_pttButton;
@property(readonly, nonatomic) UIButton *cameraButton; // @synthesize cameraButton=_cameraButton;
@property(readonly, nonatomic) UIButton *attachMediaButton; // @synthesize attachMediaButton=_attachMediaButton;
@property(readonly, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic) id <WAChatBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BOOL isPlaceholder; // @synthesize isPlaceholder=_isPlaceholder;

- (void)cancelPTTRecording;
- (void)animatePttControlsOutWithDiscardAnimation:(BOOL)arg1;
- (void)setRecordingMicActive:(BOOL)arg1;
- (void)animatePttControlsIn;
- (void)setPTTRecordingTime:(double)arg1;
- (void)pttButtonTrackSliding:(id)arg1 withEvent:(id)arg2;
- (void)pttButtonReleased:(id)arg1 withEvent:(id)arg2;
- (void)pttButtonPressed:(id)arg1 withEvent:(id)arg2;
- (void)configurePTTViews;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (BOOL)textViewShouldEndEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidPasteImage:(id)arg1;
- (void)textView:(id)arg1 needsHeightChangedTo:(float)arg2;
- (float)textViewMaximumHeight:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (void)handlePan:(id)arg1;
- (id)keyboardWindow;
- (void)hideKeyboard;
- (void)showKeyboard;
- (BOOL)isKeyboardVisible;
- (void)showPopupMenuForMessageCell:(id)arg1;
- (void)clearAnimationInSubviews:(id)arg1;
- (void)clearAnimations;
- (void)reallySetInputTextViewHeight:(float)arg1 animated:(BOOL)arg2;
- (void)setInputTextViewHeight:(float)arg1 animated:(BOOL)arg2;
- (void)didSendMessage;
@property(readonly, nonatomic) struct CGRect contentFrame;
- (void)cameraButtonTapped:(id)arg1;
- (void)attachMediaButtonTapped:(id)arg1;
- (void)sendButtonTapped:(id)arg1;
- (void)updateChatBarAnimated:(BOOL)arg1;
- (void)notifyNetworkStateChanged;
- (void)restoreSelectedTextRangeFromChatBar:(id)arg1 showMenu:(BOOL)arg2;
- (void)configureWithChatBar:(id)arg1;
- (void)redraw;
- (void)compactLayout;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)didRotateToInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1;
- (void)configureViews;
- (void)configureViews6;
- (void)fontSizeDidChange:(id)arg1;
- (void)detachFromKeyboardWindow;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
@property(copy, nonatomic) NSString *text;
- (void)inputTextViewTapped:(id)arg1;
@property(readonly, nonatomic) UIPanGestureRecognizer *panGestureRecognizer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 isPlaceHolder:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

