//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "WAChatBarDelegate.h"

@class NSNumber, NSString, UIButton, UIView, UIViewController<WAChatBarManagerDelegate>, WAChatBar;

__attribute__((visibility("hidden")))
@interface WAChatBarManager : NSObject <WAChatBarDelegate>
{
    WAChatBar *_placeholderChatBar;
    WAChatBar *_chatBar;
    BOOL _ignoreKeyboardNotifications;
    int _keyboardState;
    BOOL _interfaceRotationInProgress;
    BOOL _notifyDelegateOfHeightChangeInKeyboardDidShow;
    float _keyboardHeight;
    BOOL _suppressScrollingOnNextKeyboardWillShow;
    struct dispatch_group_s *_keyboardDispatchGroup;
    float _lastKeyboardDragOffset;
    BOOL _lastKeyboardDragDirectionIsUp;
    struct CGAffineTransform _keyboardTransformBeforeKeyboardDrag;
    NSNumber *_externalDragInProgressStartingWithKeyboardShown;
    BOOL _userInteractionDisabled;
    BOOL _interactiveKeyboardDraggingInProgress;
    BOOL _showKeyboardOnAppear;
    BOOL _scrollToBottomOnShowKeyboardOnAppear;
    BOOL _interactiveKeyboardDraggingEnabled;
    UIViewController<WAChatBarManagerDelegate> *_delegate;
}

+ (BOOL)isPTTRecordingInProgress;
+ (void)windowDidResignKey:(id)arg1;
+ (void)windowDidBecomeKey:(id)arg1;
+ (void)initialize;
@property(nonatomic) BOOL interactiveKeyboardDraggingEnabled; // @synthesize interactiveKeyboardDraggingEnabled=_interactiveKeyboardDraggingEnabled;
@property(nonatomic) BOOL scrollToBottomOnShowKeyboardOnAppear; // @synthesize scrollToBottomOnShowKeyboardOnAppear=_scrollToBottomOnShowKeyboardOnAppear;
@property(nonatomic) BOOL showKeyboardOnAppear; // @synthesize showKeyboardOnAppear=_showKeyboardOnAppear;
@property(readonly, nonatomic) BOOL interactiveKeyboardDraggingInProgress; // @synthesize interactiveKeyboardDraggingInProgress=_interactiveKeyboardDraggingInProgress;
@property(readonly, nonatomic) UIView *chatBar; // @synthesize chatBar=_chatBar;
@property(readonly, nonatomic) UIView *placeholderChatBar; // @synthesize placeholderChatBar=_placeholderChatBar;
@property(nonatomic) UIViewController<WAChatBarManagerDelegate> *delegate; // @synthesize delegate=_delegate;

- (void)endDraggingChatBarWithTranslation:(float)arg1;
- (void)updateChatBarDraggingWithTranslation:(float)arg1;
- (void)beginDraggingChatBar;
- (void)handleChatBarDragging:(id)arg1;
- (void)chatBarDidEndDragging:(id)arg1;
- (void)chatBarDidDrag:(id)arg1;
- (void)beginDraggingWithKeyboardShown;
- (void)chatBarDidBeginDragging:(id)arg1;
- (void)handlePlaceholderChatBarDragging:(id)arg1;
- (void)placeholderChatBarDidEndDragging:(id)arg1;
- (void)endDraggingWithKeyboardOffset:(float)arg1;
- (void)placeholderChatBarDidDrag:(id)arg1;
- (void)waitForKeyboardToAppear;
- (void)beginDraggingWithKeyboardHidden;
- (void)placeholderChatBarDidBeginDragging:(id)arg1;
- (void)updateDraggingWithKeyboardOffset:(float)arg1;
- (void)chatBarWantsToScrollToTop:(id)arg1;
- (void)chatBar:(id)arg1 didCancelPTTRecordingByUser:(BOOL)arg2;
- (void)chatBarDidEndPTTRecording:(id)arg1;
- (double)chatBarWillEndPTTRecording:(id)arg1;
- (void)chatBarDidBeginPTTRecording:(id)arg1;
- (BOOL)chatBarShouldBeginPTTRecording:(id)arg1;
- (void)chatBarDidChangeHeight:(id)arg1;
- (void)chatBarUserDidSubmitText:(id)arg1;
- (void)chatBarWantsToPresentCamera:(id)arg1;
- (void)chatBarWantsToAttachMedia:(id)arg1;
- (void)chatBar:(id)arg1 didPasteImage:(id)arg2;
- (void)chatBarDidChangeText:(id)arg1;
- (void)chatBarDidEndEditing:(id)arg1;
- (void)chatBarWillEndEditing:(id)arg1;
- (void)chatBarDidBeginEditing:(id)arg1;
- (BOOL)chatBarShouldBeginEditing:(id)arg1;
- (void)chatBarUserDidFocusChatBar:(id)arg1;
- (void)chatBarDidMoveToWindow:(id)arg1;
- (void)chatBar:(id)arg1 willMoveToWindow:(id)arg2;
- (float)chatBarMaximumHeight:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)reenableUserInteractionIfNeeded;
- (void)disableUserInteractionIfNeeded;
- (void)preloadKeyboard;
- (void)removeKeyboardAnimationsHidingKeyboard:(BOOL)arg1;
- (id)keyboardView;
- (id)keyboardWindow;
- (void)delegateWillDisappearWithoutInteraction;
@property(nonatomic) float chatBarAlpha;
@property(copy, nonatomic) NSString *text;
- (void)notifyNetworkStateChanged;
- (void)makeMainApplicationWindowKeyWindow;
- (void)restoreKeyWindow;
- (BOOL)isKeyboardVisible;
- (void)hideKeyboard;
- (BOOL)showKeyboard;
- (void)showPopupMenuForMessageCell:(id)arg1;
@property(readonly, nonatomic) UIButton *pttButton;
@property(readonly, nonatomic) UIButton *attachMediaButton;
@property(readonly, nonatomic) float bottomInset;
- (void)cancelPTTRecording;
- (void)setPTTRecordingTime:(double)arg1;
- (void)didRotateToInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)initWithInitialWidth:(float)arg1;

@end

