//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class NSTimer, UIButton, UILabel, UIProgressView, UIView, WAChatStorage, WACircularProgressView;

__attribute__((visibility("hidden")))
@interface WAChatDatabaseMigrationViewController : WAViewController
{
    NSTimer *_progressTimer;
    double _estimatedMigrationTime;
    unsigned long long _databaseSize;
    double _migrationStartTime;
    WAChatStorage *_chatStorage;
    id <WAChatDatabaseMigrationViewControllerDelegate> _delegate;
    UIView *_viewMigrationProgress;
    UILabel *_labelMigrationProgress;
    UIProgressView *_progressView;
    WACircularProgressView *_circularProgressView;
    UILabel *_labelProgress;
    UIView *_viewNoSpace;
    UILabel *_labelNoSpace;
    UIButton *_buttonTryAgain;
}

+ (id)controller;
@property(retain, nonatomic) UIButton *buttonTryAgain; // @synthesize buttonTryAgain=_buttonTryAgain;
@property(retain, nonatomic) UILabel *labelNoSpace; // @synthesize labelNoSpace=_labelNoSpace;
@property(retain, nonatomic) UIView *viewNoSpace; // @synthesize viewNoSpace=_viewNoSpace;
@property(retain, nonatomic) UILabel *labelProgress; // @synthesize labelProgress=_labelProgress;
@property(retain, nonatomic) WACircularProgressView *circularProgressView; // @synthesize circularProgressView=_circularProgressView;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *labelMigrationProgress; // @synthesize labelMigrationProgress=_labelMigrationProgress;
@property(retain, nonatomic) UIView *viewMigrationProgress; // @synthesize viewMigrationProgress=_viewMigrationProgress;
@property(nonatomic) id <WAChatDatabaseMigrationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAChatStorage *chatStorage; // @synthesize chatStorage=_chatStorage;

- (void)tryAgain:(id)arg1;
- (void)updateProgress:(id)arg1;
- (void)reallyPerformMigration;
- (void)performMigration;
- (BOOL)hasSufficientDiskSpaceForMigration;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (int)preferredStatusBarStyle;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

