//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CLLocationManagerDelegate.h"
#import "NSFilePresenter.h"
#import "WAMediaDownloadOperationDelegate.h"
#import "WAMediaUploadOperationDelegate.h"

@class CLLocation, CLLocationManager, NSCondition, NSManagedObjectContext, NSManagedObjectModel, NSMutableArray, NSMutableSet, NSOperationQueue, NSPersistentStore, NSPersistentStoreCoordinator, NSString, NSURL, WAChatSession;

__attribute__((visibility("hidden")))
@interface WAChatStorage : NSObject <CLLocationManagerDelegate, NSFilePresenter, WAMediaDownloadOperationDelegate, WAMediaUploadOperationDelegate>
{
    struct dispatch_queue_s *_backgroundFetchingQueue;
    BOOL _needsDeleteOrphanedMessages;
    double _timeOfLastCheckForOrphanedMessages;
    double _deletingOrphanedMessagesInProgress;
    WAChatSession *_chatSessionWithOrphanedMessages;
    NSMutableArray *_deletedEmptyChatSessions;
    NSManagedObjectModel *_managedObjectModel;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    NSManagedObjectContext *_managedObjectContext;
    NSManagedObjectContext *_dataRefreshContext;
    NSPersistentStore *_chatStore;
    NSURL *_persistentStoreURL;
    NSMutableArray *_chatSessions;
    int _blacklistSize;
    NSOperationQueue *_mediaDownloadQueue;
    NSOperationQueue *_mediaUploadQueue;
    NSMutableArray *_mediaAutodownloadRetryArray;
    NSMutableSet *_mediaUploaders;
    CLLocationManager *_locationManager;
    CLLocation *_bestLocation;
    NSMutableSet *_locationQueue;
    BOOL _processingMessages;
    NSCondition *_processMessagesCondition;
    id <WAChatStorageDelegate> _delegate;
    id <WAChatStorageDataSource> _dataSource;
    NSString *_persistentStorePath;
}

+ (id)errorWithDescription:(id)arg1 failureReason:(id)arg2;
+ (id)storageWithDelegate:(id)arg1 dataSource:(id)arg2;
+ (id)storage;
@property(readonly, nonatomic) NSString *persistentStorePath; // @synthesize persistentStorePath=_persistentStorePath;
@property(retain, nonatomic) id <WAChatStorageDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) id <WAChatStorageDelegate> delegate; // @synthesize delegate=_delegate;

@property(readonly) NSOperationQueue *presentedItemOperationQueue;
@property(readonly) NSURL *presentedItemURL;
- (id)sortedBroadcastLists;
- (void)requestListsIfNeeded;
- (void)addGroupPictureChangeEventToWAChatSession:(id)arg1 authorJID:(id)arg2 timestamp:(id)arg3;
- (void)addGroupPictureDeleteEventToWAChatSession:(id)arg1 authorJID:(id)arg2 timestamp:(id)arg3;
- (int)numberOfGroups;
- (id)groupChatSessions;
- (void)requestParticipatingGroups:(BOOL)arg1;
- (id)groupMessagesForJID:(id)arg1;
- (id)lastPushNameForGroupMember:(id)arg1 inContext:(id)arg2;
- (id)groupMemberWithObjectID:(id)arg1;
- (id)groupMemberWithObjectID:(id)arg1 inContext:(id)arg2;
- (void)requestParticipantsForGroupWithJID:(id)arg1;
- (void)requestInfoForGroupWithJID:(id)arg1;
- (void)setSubject:(id)arg1 forChatSession:(id)arg2 byUserWithJID:(id)arg3 name:(id)arg4 date:(id)arg5 sendNotification:(BOOL)arg6;
- (void)modifyParticipantInChatSession:(id)arg1 oldJID:(id)arg2 newJID:(id)arg3 timestamp:(id)arg4;
- (void)removeContact:(id)arg1 fromChatSession:(id)arg2 authorJID:(id)arg3 timestamp:(id)arg4;
- (void)removeContactWithJID:(id)arg1 fromChatSession:(id)arg2 authorJID:(id)arg3 timestamp:(id)arg4;
- (id)addContact:(id)arg1 withJID:(id)arg2 toChatSession:(id)arg3 save:(BOOL)arg4 addMessage:(BOOL)arg5 timestamp:(id)arg6;
- (id)groupMembersWithJIDs:(id)arg1;
- (id)groupMembersWithJID:(id)arg1 inContext:(id)arg2;
- (id)groupMemberWithJID:(id)arg1 inChatSession:(id)arg2;
- (BOOL)isJID:(id)arg1 memberOfChatSession:(id)arg2;
- (id)memberJIDsForChatSession:(id)arg1;
- (id)sortedGroupMembersForChatSession:(id)arg1;
- (id)membersForChatSession:(id)arg1;
- (void)requestGroupLeaveForWAChatSession:(id)arg1;
- (void)requestGroupCreateWithSubject:(id)arg1 tempJID:(id)arg2;
- (void)retryGroupCreateForWAChatSession:(id)arg1;
- (id)createChatSessionForContacts:(id)arg1 subject:(id)arg2 picture:(id)arg3;
- (id)createChatSessionWithSubject:(id)arg1 groupJID:(id)arg2 ownerJID:(id)arg3 time:(id)arg4;
- (void)requestBlackListOnlyIfOutOfSync:(BOOL)arg1;
- (BOOL)isJIDBlocked:(id)arg1;
- (void)setBlacklistJIDs:(id)arg1;
- (id)blacklistJIDs;
- (id)blacklistItems;
- (int)blacklistSize;
- (void)changeStatus:(unsigned int)arg1 forMessagesWithStanzaID:(id)arg2 fromJID:(id)arg3 participantJID:(id)arg4 userData:(id)arg5 playSound:(char *)arg6;
- (void)storeModifiedMessage:(id)arg1 notify:(BOOL)arg2;
- (void)forwardMessages:(id)arg1 toChatSession:(id)arg2;
- (void)sendMessages:(id)arg1;
- (void)sendMessage:(id)arg1 notify:(BOOL)arg2;
- (void)receiveError:(id)arg1 forMessage:(id)arg2;
- (void)receiveChatMessages:(id)arg1;
- (void)mediaDownloadOperation:(id)arg1 downloadProgressChanged:(float)arg2;
- (void)mediaDownloadOperation:(id)arg1 didFailWithError:(id)arg2;
- (void)mediaDownloadOperation:(id)arg1 didFinishWithData:(id)arg2;
- (void)mediaUploadOperation:(id)arg1 uploadProgressChanged:(float)arg2;
- (void)mediaUploadOperation:(id)arg1 didFailWithError:(id)arg2;
- (void)mediaUploadOperationDidFinish:(id)arg1;
- (void)cancelAutodownloadOperations;
- (void)cancelMediaDownloadForMessage:(id)arg1;
- (void)queueMediaDownloadForMessage:(id)arg1 autodownload:(BOOL)arg2;
- (void)processRetryDownloadArray;
- (void)checkMessagesForMediaAutodownload;
- (void)cancelFileUploadForMessage:(id)arg1;
- (void)startMediaUploadForMessage:(id)arg1;
- (id)streamingUploadingOperationForMediaAtPath:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)useBestLocationResult:(id)arg1;
- (void)requestLocationWithCallbackDictionary:(id)arg1;
- (void)locationRequestFailedWithError:(id)arg1 userInfo:(id)arg2;
- (void)locationRequestFinishedWithLocation:(id)arg1 userInfo:(id)arg2;
- (void)requestLocationForMessage:(id)arg1;
- (id)thumbnailDataForMessage:(id)arg1;
- (id)messageWithVCard:(id)arg1 contactName:(id)arg2 inChatSession:(id)arg3;
- (id)messageWithAudioURL:(id)arg1 inChatSession:(id)arg2 origin:(unsigned int)arg3 durationSeconds:(int)arg4 doNotUpload:(BOOL)arg5 streaming:(BOOL)arg6 streamingHash:(id)arg7 error:(id *)arg8;
- (void)sendPlace:(id)arg1 inChatSession:(id)arg2 completion:(id)arg3;
- (void)sendMessageWithMedia:(id)arg1;
- (void)sendVideoAtURL:(id)arg1 inChatSession:(id)arg2 completion:(id)arg3;
- (void)sendAudioTrack:(id)arg1 inChatSession:(id)arg2 completion:(id)arg3;
- (void)sendMessageWithImage:(id)arg1 ofIndex:(int)arg2 totalCount:(int)arg3 inChatSession:(id)arg4 completion:(id)arg5;
- (void)sendMessageWithImage:(id)arg1 inChatSession:(id)arg2 completion:(id)arg3;
- (id)messageWithText:(id)arg1 inChatSession:(id)arg2;
- (id)messagesForSession:(id)arg1 startOffset:(unsigned int)arg2 limit:(unsigned int)arg3;
- (long long)potentialBackupSize;
- (unsigned int)countAllImageMessages;
- (unsigned int)countAllDownloadedMediaMessagesOfType:(unsigned int)arg1;
- (unsigned int)countAllDownloadedVoiceMessages;
- (unsigned int)countAllTextMessages;
- (unsigned int)countAllMessagesOfType:(unsigned int)arg1;
- (int)compareNumberOfMessagesInChatSession:(id)arg1 withNumber:(unsigned int)arg2;
- (id)refetchAllMessages:(id)arg1;
- (id)messagesWithStanzaIDs:(id)arg1 inChatSession:(id)arg2;
- (id)messageWithStanzaID:(id)arg1 inChatSession:(id)arg2;
- (id)receivedVoiceMessagesWithStanzaID:(id)arg1;
- (id)sentMessagesWithStanzaID:(id)arg1 jid:(id)arg2;
- (id)messageWithStanzaID:(id)arg1 contactJID:(id)arg2;
- (id)messageWithID:(id)arg1;
- (id)messageWithID:(id)arg1 inContext:(id)arg2;
- (int)indexOfMessageWithID:(id)arg1;
- (id)receivedMessagesWithStanzaIDs:(id)arg1;
- (id)outgoingMessageTemplateForSession:(id)arg1 withMedia:(BOOL)arg2;
- (id)incomingMessageTemplateWithMedia:(BOOL)arg1;
- (id)cpVideoToTempDirectory:(id)arg1 preserveName:(BOOL)arg2 error:(id *)arg3;
- (id)fullPathForAudioRecord;
- (void)fetchLocationMessagesInChatSession:(id)arg1 afterDate:(id)arg2 completion:(id)arg3;
- (id)pushToTalkMessagesInChatSessionWithID:(id)arg1;
- (void)deferredFetchEntitiesWithName:(id)arg1 request:(id)arg2 completion:(id)arg3;
- (void)fetchEntitiesWithName:(id)arg1 request:(id)arg2 completion:(id)arg3;
- (unsigned int)countSentMedia;
- (unsigned int)countMediaInChatSessionWithID:(id)arg1;
- (void)deleteAllMedia;
- (void)deleteMessage:(id)arg1;
- (int)countMediaForMessage:(id)arg1 tag:(int)arg2;
- (void)rollbackPendingDeletionOfEligibleChatSessions;
- (void)commitPendingDeletionOfEligibleChatSessions;
- (void)deleteEmptyEligibleChatSessionsImmediately:(BOOL)arg1;
- (void)deleteMessages:(id)arg1 inChatSession:(id)arg2;
- (void)deleteOrphanedMessages;
- (void)deleteOrphanedMessagesIfNeeded;
- (void)debug_deleteAllOrphanedMessagesNow;
- (id)replaceChatSessionWithEmptySession:(id)arg1;
- (void)removeChatSession:(id)arg1;
- (void)deleteMessagesInSession:(id)arg1;
- (void)clearAllChatSessions;
- (void)deleteAllChatSessions;
- (void)deleteChatSession:(id)arg1;
- (void)deleteNotificationsForAllGroups;
- (id)groupSettingsExcludingGroupJID:(id)arg1;
- (void)preparePropertiesForChatSession:(id)arg1;
- (void)updateChatSessionWithMessage:(id)arg1;
- (BOOL)chatSessionsContainMessages:(id)arg1;
- (int)numberOfUnreadChatSessions;
- (void)saveUnreadCount;
- (int)totalNumberOfUnreadMessages;
- (void)prepareSessionToUse:(id)arg1;
- (void)storeModifiedChatSession:(id)arg1;
- (id)chatSessionWithObjectID:(id)arg1;
- (id)chatSessionWithObjectID:(id)arg1 inContext:(id)arg2;
- (id)chatSessionForJID:(id)arg1 inContext:(id)arg2;
- (id)existingChatSessionsForJIDs:(id)arg1 prefetchingLastMessage:(BOOL)arg2;
- (id)existingChatSessionsForContact:(id)arg1 includeLinkedContacts:(BOOL)arg2;
- (id)existingChatSessionForJID:(id)arg1;
- (id)chatSessionForJID:(id)arg1;
- (id)chatSessionsForContactsUpdateInContext:(id)arg1;
- (id)createChatSessionForContact:(id)arg1 JID:(id)arg2;
- (id)createChatSessionForContact:(id)arg1 JID:(id)arg2 hidden:(BOOL)arg3;
- (id)chatSessions;
- (void)resetChatSessions;
- (void)searchWithCriteria:(id)arg1 delegate:(id)arg2 selector:(SEL)arg3;
- (void)workerMOCDidSave:(id)arg1;
- (BOOL)saveManagedObjectContextAndMergeChanges:(id)arg1;
- (void)delayedSave;
- (void)mergeChanges:(id)arg1;
- (void)save;
- (BOOL)saveContext:(id)arg1;
- (void)disposeDataRefreshContext;
- (id)fullPathToMediaInMessage:(id)arg1;
- (void)xmppConnectionStateDidChange:(id)arg1;
- (void)mediaDownloadPolicyDidChange:(id)arg1;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)removeGroupPictureIDs;
- (void)cancelAllDownloads;
- (void)cancelAllUploads;
- (void)finishProcessingRemainingMessages;
- (void)deleteStorage;
- (unsigned int)databaseStatus;
- (void)reportMigrationTimeFieldStatsWithDuration:(double)arg1 databaseSize:(long long)arg2;
- (void)migrateChatDatabaseWithCompletionHandler:(id)arg1;
- (BOOL)addMediaSectionIDToAllMessagesInContext:(id)arg1;
- (void)migrateChatSessionPropertiesInContext:(id)arg1;
- (void)migrateGroupMemberPropertiesInContext:(id)arg1;
- (void)setMetadata:(id)arg1 forKey:(id)arg2;
- (id)metadataForKey:(id)arg1;
- (id)newManagedObjectContext;
- (id)dataRefreshContext;
- (id)managedObjectContext;
- (id)chatStore;
- (void)dropStore;
- (void)sendChatStorageDidLoadDatabaseNotification;
- (BOOL)loadPersistentStore;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly) NSURL *primaryPresentedItemURL;

@end

