//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

__attribute__((visibility("hidden")))
@interface WAChatsTableView : UITableView
{
    BOOL _disableScroll;
}

@property(nonatomic) BOOL disableScroll; // @synthesize disableScroll=_disableScroll;
- (void)setContentOffset:(struct CGPoint)arg1;

@end

