//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSNumber, NSString, WAChatSession;

__attribute__((visibility("hidden")))
@interface WAChatProperties : NSManagedObject
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *alerts; // @dynamic alerts;
@property(retain, nonatomic) WAChatSession *chatSession; // @dynamic chatSession;
@property(retain, nonatomic) NSNumber *enabled; // @dynamic enabled;
@property(retain, nonatomic) NSDate *muteDate; // @dynamic muteDate;
@property(retain, nonatomic) NSString *soundName; // @dynamic soundName;
@end

