//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WAContactInfoPageAction : NSObject
{
    BOOL _enabled;
    BOOL _destructive;
    NSString *_title;
    SEL _selector;
}

+ (id)actionWithTitle:(id)arg1 selector:(SEL)arg2;
@property(nonatomic) BOOL destructive; // @synthesize destructive=_destructive;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) SEL selector; // @synthesize selector=_selector;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

- (id)initWithTitle:(id)arg1 selector:(SEL)arg2;

@end

