//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString, UIImage, WAContactProperty;

__attribute__((visibility("hidden")))
@interface WAContactInfoUnit : NSObject
{
    BOOL _multipleLines;
    BOOL _highlighted;
    UIImage *_image;
    NSString *_detailText;
     _action;
    WAContactProperty *_property;
}

+ (id)contactInfoUnitForContactProperty:(id)arg1;
@property(retain, nonatomic) WAContactProperty *property; // @synthesize property=_property;
@property(copy, nonatomic)  action; // @synthesize action=_action;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) BOOL multipleLines; // @synthesize multipleLines=_multipleLines;
@property(copy, nonatomic) NSString *detailText; // @synthesize detailText=_detailText;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;

@property(readonly, nonatomic) NSString *label;
@property(readonly, nonatomic) NSString *value;
@property(readonly, nonatomic) NSString *valueText;
- (id)init;
- (id)initWithContactProperty:(id)arg1;

@end

