//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, NSString, UILabel;

__attribute__((visibility("hidden")))
@interface WAContactInfoSectionHeaderView : UIView
{
    UILabel *_titleLabel;
    UIView *_topBorder;
    UIView *_bottomBorder;
    NSLayoutConstraint *_titleLeftConstraint;
    NSLayoutConstraint *_backgroundViewBottomConstraint;
    UIView *_backgroundView;
    BOOL _extendsLowerEdge;
    struct UIEdgeInsets _insets;
}

@property(nonatomic) BOOL extendsLowerEdge; // @synthesize extendsLowerEdge=_extendsLowerEdge;
@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;

@property(nonatomic) BOOL bottomEdgeHidden;
@property(nonatomic) BOOL topEdgeHidden;
@property(copy, nonatomic) NSString *text;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

