//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAContactInfoBaseViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"

@class NSArray, NSManagedObjectID, NSMutableArray, WACallEventsTableViewCell, WAContactInfoPageAction, WAContactInfoTableHeaderView, WAMergedContact;

__attribute__((visibility("hidden")))
@interface WAContactInfoViewController : WAContactInfoBaseViewController <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, UIActionSheetDelegate>
{
    NSManagedObjectID *_contactID;
    WAMergedContact *_mergedContact;
    NSMutableArray *_contactInfoSections;
    NSMutableArray *_sectionHeights;
    WAContactInfoPageAction *_clearChatHistoryAction;
    WAContactInfoPageAction *_emailChatHistoryAction;
    WAContactInfoPageAction *_viewAllMediaAction;
    WAContactInfoPageAction *_blockCallerPageAction;
    int _selectedPhoneIndex;
    NSArray *_phonesWithChatHistory;
    BOOL _showMergedContact;
    BOOL _hasLinkedContacts;
    NSArray *_whatsAppPhoneIDs;
    NSArray *_inviteUnits;
    WACallEventsTableViewCell *_callEventsCell;
    WAContactInfoTableHeaderView *_tableHeader;
}

@property(retain, nonatomic) WAContactInfoTableHeaderView *tableHeader; // @synthesize tableHeader=_tableHeader;

- (void)profilePictureUpdated:(id)arg1;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)cellForContact:(id)arg1 indexPath:(id)arg2 tableView:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)inviteViaEmail:(id)arg1;
- (void)inviteViaSMS:(id)arg1;
- (void)inviteContactViaPhoneOrEmail:(id)arg1;
- (void)inviteContact;
- (void)profilePictureTapped:(id)arg1 withEvent:(id)arg2;
- (void)callButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)whatsAppButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)sendMessageToWAPhoneWithID:(id)arg1;
- (void)sendMessageToContact;
- (void)setUpMediaManager;
- (void)didDeleteMessages;
- (void)didAddMessages;
- (void)clearChatHistory;
- (void)emailChatHistory;
- (void)askToAttachMedia;
- (void)emailChatHistoryWithMedia:(BOOL)arg1;
- (void)callerBlockedStatusDidChange;
- (void)updateBlockCallerPageAction;
- (void)setAggregateCallEvent:(id)arg1;
- (void)rebuildContactInfoDataUnitsForKnownContact;
- (void)rebuildContactInfoDataUnitsForUnknownContact;
- (void)reload;
- (id)headerTextForLinkedContacts;
- (void)setContact:(id)arg1;
- (id)contact;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (void)reloadWithContact:(id)arg1;
- (id)initWithContact:(id)arg1 merged:(BOOL)arg2 whatsAppID:(id)arg3 detailText:(id)arg4;

@end

