//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSNumber, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface WAContactSection : NSManagedObject
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *contactCount; // @dynamic contactCount;
@property(retain, nonatomic) NSSet *contacts; // @dynamic contacts;
@property(retain, nonatomic) NSNumber *sort; // @dynamic sort;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@end

