//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface WAContactInfoPhotoUnit : NSObject
{
    UIImage *_image;
}

+ (id)contactInfoPhotoUnitForRecord:(void *)arg1;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;

- (id)initWithRecord:(void *)arg1;

@end

