//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray, NSTimer, UIButton, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface WAContactInfoTableViewCell : UITableViewCell
{
    NSTimer *_popupTimer;
    BOOL _popupActive;
    UILabel *_titleLabel;
    UILabel *_valueLabel;
    UILabel *_detailLabel;
    unsigned int _cellPosition;
    NSArray *_accessoryButtons;
    UIButton *_leftButton;
    UIView *_bottomEdgeView;
}

+ (float)heightForContactInfoUnit:(id)arg1 cellPosition:(unsigned int)arg2 displayWidth:(float)arg3;
+ (float)heightForContactFieldValue:(id)arg1 multiline:(BOOL)arg2 cellPosition:(unsigned int)arg3 displayWidth:(float)arg4;
+ (float)bottomInsetForCellPosition:(unsigned int)arg1;
+ (float)topInsetForCellPosition:(unsigned int)arg1;
+ (id)valueLabelFont;
+ (id)cellWithReuseIdentifier:(id)arg1;
@property(readonly, nonatomic) UIView *bottomEdgeView; // @synthesize bottomEdgeView=_bottomEdgeView;
@property(retain, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) NSArray *accessoryButtons; // @synthesize accessoryButtons=_accessoryButtons;
@property(nonatomic) BOOL popupActive; // @synthesize popupActive=_popupActive;
@property(nonatomic) unsigned int cellPosition; // @synthesize cellPosition=_cellPosition;
@property(readonly, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(readonly, nonatomic) UILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

- (void)configureWithContactInfoUnit:(id)arg1;
- (void)didHideMenu;
- (void)showCopyMenu:(id)arg1;
- (void)copy:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)canBecomeFirstResponder;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

