//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSCharacterSet, NSIndexSet, NSLock, NSManagedObjectContext, NSManagedObjectModel, NSMutableArray, NSMutableDictionary, NSPersistentStoreCoordinator, UILocalizedIndexedCollation;

__attribute__((visibility("hidden")))
@interface WAContactsStorage : NSObject
{
    NSArray *_contactEmails;
    NSMutableDictionary *_existResults;
    long _abAuthStatus;
    NSLock *_pscLock;
    NSLock *_momLock;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    NSManagedObjectModel *_managedObjectModel;
    NSManagedObjectContext *_managedObjectContext;
    NSManagedObjectContext *_addressBookReloadMOC;
    NSManagedObjectContext *_syncResponseMOC;
    BOOL _needsRefreshContacts;
    BOOL _needsRefreshStatus;
    BOOL _contactsAvailable;
    BOOL _emailsLoading;
    BOOL _reverseNameSearch;
    UILocalizedIndexedCollation *_collation;
    NSArray *_sectionTitles;
    NSArray *_sectionIndexTitles;
    NSIndexSet *_ignoredIndexTitles;
    struct _NSRange _oldLatinIndexRange;
    struct _NSRange _newLatinIndexRange;
    struct _NSRange _oldLatinSectionRange;
    struct _NSRange _newLatinSectionRange;
    NSCharacterSet *_nonAlphanumericCharacterSet;
    struct dispatch_queue_s *_contactsSerialQueue;
    NSMutableArray *_contactGroups;
    id <WAContactsStorageDelegate> _delegate;
    NSLock *_addressBookMutationLock;
    int _approxCountOfContactsBeingUpdated;
}

@property int approxCountOfContactsBeingUpdated; // @synthesize approxCountOfContactsBeingUpdated=_approxCountOfContactsBeingUpdated;
@property(readonly, nonatomic) NSLock *addressBookMutationLock; // @synthesize addressBookMutationLock=_addressBookMutationLock;
@property(nonatomic) id <WAContactsStorageDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSMutableArray *contactGroups; // @synthesize contactGroups=_contactGroups;

- (void)performSeriallyOnQueue:(struct dispatch_queue_s *)arg1 block:(id)arg2;
- (void)existCheckFailedWithError:(id)arg1 backoff:(id)arg2 userInfo:(id)arg3;
- (void)existCheckSuccess:(id)arg1 wait:(id)arg2 version:(id)arg3 userInfo:(id)arg4;
- (void)setExistStatus:(id)arg1 forJID:(id)arg2;
- (id)existStatusForJID:(id)arg1;
- (void)refreshExistStatusForJID:(id)arg1;
- (void)statusFetchFailerWithError:(id)arg1;
- (void)statusFetchFinishedWithResults:(id)arg1;
- (void)requestStatusMessagesForAllContactsIfNeeded;
- (void)requestStatusMessagesForJIDs:(id)arg1;
- (void)requestCallabilityStatusesForJIDs:(id)arg1;
- (void)deleteStatusForJID:(id)arg1;
- (void)createStatusForJID:(id)arg1;
- (id)addressBookContainsJID:(id)arg1;
- (void)setCallabilityStatus:(int)arg1 forJID:(id)arg2;
- (void)setStatusText:(id)arg1 timestamp:(id)arg2 forJID:(id)arg3;
- (id)statusForWhatsAppID:(id)arg1;
- (id)statusForWhatsAppID:(id)arg1 inContext:(id)arg2;
- (id)statusMessagesForWhatsAppIDs:(id)arg1 inContext:(id)arg2;
- (id)statusesForWhatsAppID:(id)arg1 inContext:(id)arg2;
- (id)statusWithObjectID:(id)arg1 inContext:(id)arg2;
- (id)statusWithObjectID:(id)arg1;
- (void)loadContactEmails;
- (id)emailsForAllContacts;
- (id)contactEmails;
- (id)phoneWithObjectID:(id)arg1 inContext:(id)arg2;
- (id)phoneWithObjectID:(id)arg1;
- (id)allPhonesMatchingNumbers:(id)arg1 inContext:(id)arg2;
- (id)phonesWithStatus:(BOOL)arg1;
- (id)phoneNumbers:(BOOL)arg1;
- (unsigned int)numberOfPhones;
- (BOOL)phoneNumber:(id)arg1 isFavoriteForContactABID:(int)arg2;
- (void)addPhoneToFavorites:(id)arg1;
- (void)deleteFavorites:(id)arg1;
- (id)sectionWithTitle:(id)arg1 inContext:(id)arg2;
- (id)addSectionWithTitle:(id)arg1 inContext:(id)arg2;
- (id)contactsInSectionWithID:(id)arg1;
- (id)contactsIDsInSectionWithID:(id)arg1;
- (id)sectionWithObjectID:(id)arg1;
- (id)sections;
- (id)addContactFromABRecord:(void *)arg1 addressBook:(void *)arg2 whatsAppID:(id)arg3;
- (id)reloadDataFromABRecord:(void *)arg1 whatsAppID:(id)arg2;
- (id)allContactsForWhatsAppID:(id)arg1 inContext:(id)arg2;
- (id)bestContactForWhatsAppID:(id)arg1 inContext:(id)arg2;
- (id)bestContactForJID:(id)arg1;
- (id)bestContactFromContacts:(id)arg1;
- (id)allContactsWithWhatsAppIDs:(id)arg1 inContext:(id)arg2;
- (id)contactsWithABIDs:(id)arg1 withPrefetchedRelationships:(id)arg2 inContext:(id)arg3;
- (id)findContactWithABID:(int)arg1 registeredInContext:(id)arg2;
- (id)contactWithABID:(int)arg1 inContext:(id)arg2 parentOnly:(BOOL)arg3;
- (id)parentContactWithABID:(int)arg1 inContext:(id)arg2;
- (id)parentContactWithABID:(int)arg1;
- (id)contactWithObjectID:(id)arg1;
- (unsigned int)numberOfContacts;
- (int)sectionForSectionIndexTitle:(id)arg1 atIndex:(int)arg2;
- (unsigned int)sectionForObjectName:(id)arg1;
- (id)sectionIndexTitles;
- (id)sectionTitles;
- (void)prepareSectionData;
- (void)processSyncError:(id)arg1;
- (void)processSyncResults:(id)arg1 syncMode:(unsigned int)arg2 syncContext:(unsigned int)arg3;
- (id)mergeContacts:(id)arg1;
- (void)establishParentChildRelationshipsWithContacts:(id)arg1;
- (void)reloadContactsFromAddressBook;
- (void)updateContact:(id)arg1 withRecord:(void *)arg2;
- (void)reloadPhonesForContact:(id)arg1 fromABRecord:(void *)arg2;
- (void)deletePhone:(id)arg1;
- (id)addPhone:(id)arg1 label:(id)arg2 toContact:(id)arg3;
- (id)addStatus:(id)arg1 toPhone:(id)arg2 whatsAppID:(id)arg3 statusDate:(id)arg4;
- (void)notifyUpdatedStatusIfNecessary;
- (void)notifyUpdatedContactsIfNecessary;
- (void)workerMOCDidSave:(id)arg1;
- (BOOL)saveManagedObjectContextAndMergeChanges:(id)arg1;
- (void)destroyManagedObjectContext:(id)arg1;
- (void)addressBookReloadMOCDidSave:(id)arg1;
- (void)syncResponseMOCDidSave:(id)arg1;
- (void)reset;
- (void)setMetadata:(id)arg1 forKey:(id)arg2;
- (id)metadataForKey:(id)arg1;
- (id)newManagedObjectContext;
@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext;
- (id)persistentStoreCoordinator;
- (id)managedObjectModel;
- (id)persistentStoreURL;
- (id)persistentStorePath;
- (id)nonAlphanumericCharacterSet;
@property(readonly, nonatomic) BOOL reverseNameSearch;
@property(readonly, nonatomic) BOOL contactsAvailable;
@property(readonly, nonatomic, getter=isAddressBookAuthStatusKnown) BOOL addressBookAuthStatusKnown;
@property(readonly, nonatomic, getter=isAddressBookAllowed) BOOL addressBookAllowed;
- (void)reloadAddressBookAuthStatus;
- (void)dealloc;
- (id)initWithStorageDelegate:(id)arg1;
- (id)init;

@end

