//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "ProblemInputControllerDelegate.h"

@class UITextView;

__attribute__((visibility("hidden")))
@interface WADatabaseIntegrityCheckerViewController : WAViewController <ProblemInputControllerDelegate, MFMailComposeViewControllerDelegate>
{
    UITextView *_consoleTextView;
}

@property(retain, nonatomic) UITextView *consoleTextView; // @synthesize consoleTextView=_consoleTextView;

- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)probleminputControllerDidCancel:(id)arg1;
- (void)problemInputController:(id)arg1 didFinishWithText:(id)arg2 attachment:(id)arg3;
- (void)performRepairChatDatabase;
- (void)repairChatDatabase:(id)arg1;
- (void)email:(id)arg1;
- (void)checkDatabaseIntegrity:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

