//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface WADateBubbleView : UIView
{
    UIImageView *_bubbleImageView;
    UILabel *_titleLabel;
    UIView *_backgroundView;
    UIView *_maskView;
    UIImageView *_blurredBackgroundView;
    UIImageView *_highlightsImageView;
    BOOL _useBlurredBackground;
    id <WADateBubbleViewDelegate> _delegate;
    float _floating;
    int _sectionIndex;
}

+ (float)preferredHeightInEditingMode:(BOOL)arg1 sectionIndex:(int)arg2;
@property(nonatomic) int sectionIndex; // @synthesize sectionIndex=_sectionIndex;
@property(nonatomic) float floating; // @synthesize floating=_floating;
@property(nonatomic) id <WADateBubbleViewDelegate> delegate; // @synthesize delegate=_delegate;

- (id)accessibilityValue;
- (id)accessibilityLabel;
- (struct CGRect)accessibilityFrame;
- (BOOL)isAccessibilityElement;
- (void)fadeOutIfNeededWithAnimation:(BOOL)arg1;
- (void)fadeInWithAnimation:(BOOL)arg1;
@property(copy, nonatomic) NSString *title;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

