//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface WADatabaseResultsFetcher : NSObject
{
    NSManagedObjectContext *_sourceManagedObjectContext;
    NSManagedObjectContext *_destinationManagedObjectContext;
    NSArray *_objectIDs;
    NSArray *_relationshipKeyPathsForPrefetching;
}

+ (id)nullFetcher;
@property(retain, nonatomic) NSArray *relationshipKeyPathsForPrefetching; // @synthesize relationshipKeyPathsForPrefetching=_relationshipKeyPathsForPrefetching;
@property(retain, nonatomic) NSArray *objectIDs; // @synthesize objectIDs=_objectIDs;
@property(retain, nonatomic) NSManagedObjectContext *destinationManagedObjectContext; // @synthesize destinationManagedObjectContext=_destinationManagedObjectContext;
@property(retain, nonatomic) NSManagedObjectContext *sourceManagedObjectContext; // @synthesize sourceManagedObjectContext=_sourceManagedObjectContext;

- (id)fetchResults;
@property(readonly, nonatomic) unsigned int objectCount;

@end

