//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATranslucentTableViewCell.h"

@class NSString, UIImageView, UIView;

__attribute__((visibility("hidden")))
@interface WADividerCell : WATranslucentTableViewCell
{
    UIImageView *_imageViewBackground;
    UIView *_blurredBackgroundTrackingView;
}

+ (float)rowHeight;

- (BOOL)selectable;
- (void)layoutSubviews;
@property(copy, nonatomic) NSString *title;
- (id)blurMaskTrackingView;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

