//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class UIButton, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface WADisabledPushReminderViewController : WAViewController
{
    UIButton *_buttonClose;
    UILabel *_labelItem1;
    UILabel *_labelItem2;
    UILabel *_labelItem3;
    UILabel *_labelItem4;
    UILabel *_labelItem5;
    UILabel *_labelTitle;
    UILabel *_labelOpenSettings;
    UILabel *_labelOpenNotificationCenter;
    UILabel *_labelSelectWhatsApp;
    UILabel *_labelTurnOnAlerts;
    UILabel *_labelShowInNotificationCenter;
    UILabel *_labelShowOnLockScreen;
    UILabel *_labelSelectAlertStyle;
    UIImageView *_imageSettings;
    UIImageView *_imageNotificationCenter;
    UIImageView *_imageWhatsApp;
    UIImageView *_imageAlertBanners;
    UIView *_viewShowInNotificationCenter;
    UIView *_viewShowOnLockScreen;
}

+ (BOOL)canPresentReminder;
+ (id)controller;
@property(retain, nonatomic) UIView *viewShowOnLockScreen; // @synthesize viewShowOnLockScreen=_viewShowOnLockScreen;
@property(retain, nonatomic) UIView *viewShowInNotificationCenter; // @synthesize viewShowInNotificationCenter=_viewShowInNotificationCenter;
@property(retain, nonatomic) UIImageView *imageAlertBanners; // @synthesize imageAlertBanners=_imageAlertBanners;
@property(retain, nonatomic) UIImageView *imageWhatsApp; // @synthesize imageWhatsApp=_imageWhatsApp;
@property(retain, nonatomic) UIImageView *imageNotificationCenter; // @synthesize imageNotificationCenter=_imageNotificationCenter;
@property(retain, nonatomic) UIImageView *imageSettings; // @synthesize imageSettings=_imageSettings;
@property(retain, nonatomic) UILabel *labelSelectAlertStyle; // @synthesize labelSelectAlertStyle=_labelSelectAlertStyle;
@property(retain, nonatomic) UILabel *labelShowOnLockScreen; // @synthesize labelShowOnLockScreen=_labelShowOnLockScreen;
@property(retain, nonatomic) UILabel *labelShowInNotificationCenter; // @synthesize labelShowInNotificationCenter=_labelShowInNotificationCenter;
@property(retain, nonatomic) UILabel *labelTurnOnAlerts; // @synthesize labelTurnOnAlerts=_labelTurnOnAlerts;
@property(retain, nonatomic) UILabel *labelSelectWhatsApp; // @synthesize labelSelectWhatsApp=_labelSelectWhatsApp;
@property(retain, nonatomic) UILabel *labelOpenNotificationCenter; // @synthesize labelOpenNotificationCenter=_labelOpenNotificationCenter;
@property(retain, nonatomic) UILabel *labelOpenSettings; // @synthesize labelOpenSettings=_labelOpenSettings;
@property(retain, nonatomic) UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(retain, nonatomic) UILabel *labelItem5; // @synthesize labelItem5=_labelItem5;
@property(retain, nonatomic) UILabel *labelItem4; // @synthesize labelItem4=_labelItem4;
@property(retain, nonatomic) UILabel *labelItem3; // @synthesize labelItem3=_labelItem3;
@property(retain, nonatomic) UILabel *labelItem2; // @synthesize labelItem2=_labelItem2;
@property(retain, nonatomic) UILabel *labelItem1; // @synthesize labelItem1=_labelItem1;
@property(retain, nonatomic) UIButton *buttonClose; // @synthesize buttonClose=_buttonClose;

- (void)closeAction:(id)arg1;
- (void)dismiss;
- (void)presentModallyFromViewController:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (int)preferredStatusBarStyle;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

