//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@class UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface WADoneWithSpinnerBarButtonItem : UIBarButtonItem
{
    UIActivityIndicatorView *_spinner;
    unsigned int _buttonStyle;
}

+ (id)buttonWithTarget:(id)arg1 action:(SEL)arg2;
@property(nonatomic) unsigned int buttonStyle; // @synthesize buttonStyle=_buttonStyle;

@property(nonatomic) BOOL spinnerHidden;
- (void)done:(id)arg1;
- (void)sizeToFit;
- (id)initWithTitle:(id)arg1;

@end

