//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSNumber, WAPhone;

__attribute__((visibility("hidden")))
@interface WAFavorite : NSManagedObject
{
}

- (void)setDirty;

// Remaining properties
@property(retain, nonatomic) WAPhone *phone; // @dynamic phone;
@property(retain, nonatomic) NSNumber *sort; // @dynamic sort;

@end

