//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WAFieldStatsRecord : NSObject
{
    BOOL _written;
    int _type;
    int _uniqueId;
    unsigned int _timestamp;
    NSString *_stringValue;
    double _numericValue;
}

@property BOOL written; // @synthesize written=_written;
@property double numericValue; // @synthesize numericValue=_numericValue;
@property(retain) NSString *stringValue; // @synthesize stringValue=_stringValue;
@property unsigned int timestamp; // @synthesize timestamp=_timestamp;
@property int uniqueId; // @synthesize uniqueId=_uniqueId;
@property int type; // @synthesize type=_type;

- (id)description;
- (id)typeToString:(int)arg1;
- (BOOL)isEqualToRecord:(id)arg1;
- (BOOL)isDimension;
- (id)initWithType:(int)arg1 uniqueId:(int)arg2 timestamp:(unsigned int)arg3;

@end

