//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface WAFieldStats : NSObject
{
    struct __sFILE *_file;
    long _fileOffset;
    int _recordCount;
    unsigned int _timestamp;
    int _missedUpdateCount;
    _Bool _rotatedExists;
    NSMutableArray *_cachedRecords;
    struct dispatch_queue_s *_queue;
}

+ (id)sharedManager;

- (void)reportKnownDimensions;
- (BOOL)addRecordToCache:(id)arg1;
- (id)findCachedRecord:(int)arg1 uniqueId:(unsigned int)arg2;
- (BOOL)rotateFile;
- (void)appendRecord:(id)arg1;
- (int)writeRecord:(id)arg1;
- (int)writeRecord:(id)arg1 offset:(long)arg2;
- (void)closeFieldStatsFile;
- (BOOL)openFieldStatsFile;
- (BOOL)createFile;
- (BOOL)openFile;
- (int)readRecordFromFile:(struct __sFILE *)arg1 record:(id *)arg2;
- (id)rotatedFileName;
- (id)fileName;
- (id)fieldStatsDirectory;
- (BOOL)isFileExists:(id)arg1;
- (unsigned int)unixTimestamp;
- (void)numericRecord:(unsigned int)arg1 type:(int)arg2 value:(double)arg3;
- (void)stringRecord:(unsigned int)arg1 stringValue:(id)arg2;
- (double)qNaN;
- (void)metric:(int)arg1 timer:(double)arg2;
- (void)metric:(int)arg1 gauge:(double)arg2;
- (void)metric:(int)arg1 increment:(int)arg2;
- (void)clearNumericDimension:(int)arg1;
- (void)clearStringDimension:(int)arg1;
- (void)dimension:(int)arg1 numericValue:(double)arg2;
- (void)dimension:(int)arg1 stringValue:(id)arg2;
- (void)clearStatsData;
- (id)statsData;
- (BOOL)isReadyToSend;
- (void)dealloc;
- (id)init;

@end

