//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

#import "ForwardPickerDelegate.h"

@class NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface WAForwardActivity : UIActivity <ForwardPickerDelegate>
{
    NSArray *_items;
    NSString *_customActivityTitle;
    NSDictionary *_selectedContactInfo;
    int _maximumItemCount;
}

+ (int)activityCategory;
@property(nonatomic) int maximumItemCount; // @synthesize maximumItemCount=_maximumItemCount;
@property(readonly, nonatomic) NSDictionary *selectedContactInfo; // @synthesize selectedContactInfo=_selectedContactInfo;

- (void)forwardPickerDidCancel:(id)arg1;
- (void)forwardPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)performActivity;
- (id)activityViewController;
- (void)prepareWithActivityItems:(id)arg1;
- (BOOL)canPerformWithActivityItems:(id)arg1;
- (id)activityType;
- (void)setActivityTitle:(id)arg1;
- (id)activityTitle;
- (id)activityImage;

@end

