//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "WANewGroupViewControllerDelegate.h"
#import "WARecipientsViewControllerDelegate.h"

@class NSArray, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface WAGroupComposer : UINavigationController <WARecipientsViewControllerDelegate, WANewGroupViewControllerDelegate>
{
    NSArray *_contacts;
    NSString *_groupSubject;
    UIImage *_groupPicture;
    unsigned int _mode;
}

@property(readonly, nonatomic) unsigned int mode; // @synthesize mode=_mode;

- (void)newGroupViewControllerDidCancel:(id)arg1;
- (void)newGroupViewController:(id)arg1 didFinishWithSubject:(id)arg2 picture:(id)arg3;
- (void)recipientsControllerDidCancel:(id)arg1;
- (void)recipientsController:(id)arg1 didFinishWithContacts:(id)arg2;
- (id)recipientsViewController;
- (id)init;
- (id)initWithMode:(unsigned int)arg1;
- (id)initWithMode:(unsigned int)arg1 recipients:(id)arg2;

// Remaining properties
@property(nonatomic) id <UINavigationControllerDelegate><WAGroupComposerDelegate> delegate;

@end

