//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class WAImageCropToolView;

@protocol WAImageCropToolViewDelegate <NSObject>
- (void)imageCropToolViewNormalizedCropRectDidFinishChanging:(WAImageCropToolView *)arg1;
- (void)imageCropToolViewNormalizedCropRectDidChange:(WAImageCropToolView *)arg1;
- (void)imageCropToolViewNormalizedCropRectWillBeginChanging:(WAImageCropToolView *)arg1;
@end

