//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "UIViewControllerAnimatedTransitioning.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WAImageToImageTransitionController : NSObject <UIViewControllerAnimatedTransitioning>
{
    NSMutableDictionary *_context;
    BOOL _useSpringAnimation;
    double _animationDuration;
}

+ (id)transitionControllerForOperation:(int)arg1 fromViewController:(id)arg2 toViewController:(id)arg3;
@property(nonatomic) BOOL useSpringAnimation; // @synthesize useSpringAnimation=_useSpringAnimation;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;

- (void)animationEnded:(BOOL)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)init;

@end

