//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABubbleView.h"

@class NSString, UIAccessibilityElement, UIImage;

__attribute__((visibility("hidden")))
@interface WAInstantVoiceBubbleView : WABubbleView
{
    UIAccessibilityElement *_elemBody;
    BOOL _allowAction;
    BOOL _allowLablel;
    NSString *_buttonHint;
    UIImage *_thumbnailImage;
}

+ (struct CGSize)sizeForName:(id)arg1 incoming:(BOOL)arg2 forWidth:(float)arg3;
+ (float)heightForName:(id)arg1;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;

- (int)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(int)arg1;
- (int)accessibilityElementCount;
- (void)setButtonHint:(id)arg1 allowVoiceOverLabel:(BOOL)arg2 allowAction:(BOOL)arg3;
- (void)updateAccessibilityLabels;
- (BOOL)isAccessibilityElement;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithIncomingState:(BOOL)arg1 delegate:(id)arg2;

@end

