//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "LabelPickerViewControllerDelegate.h"
#import "WAContactInfoEditCellDelegate.h"

@class NSString, WAContactInfoEditCell, WAContactInfoNameUnit, WAContactInfoPhotoUnit, WAContactInfoTableHeaderView;

__attribute__((visibility("hidden")))
@interface WAInfoInputViewController : WATableViewController <WAContactInfoEditCellDelegate, LabelPickerViewControllerDelegate>
{
    id <WAInfoInputViewControllerDelegate> _delegate;
    WAContactInfoNameUnit *_contactNameUnit;
    WAContactInfoPhotoUnit *_contactPhotoUnit;
    WAContactInfoTableHeaderView *_tableHeader;
    WAContactInfoEditCell *_textFieldCell;
    void *_displayedPerson;
    int _propertyType;
    NSString *_propertyValue;
    NSString *_labelValue;
}

@property(copy, nonatomic) NSString *labelValue; // @synthesize labelValue=_labelValue;
@property(copy, nonatomic) NSString *propertyValue; // @synthesize propertyValue=_propertyValue;
@property(nonatomic) int propertyType; // @synthesize propertyType=_propertyType;
@property(nonatomic) void *displayedPerson; // @synthesize displayedPerson=_displayedPerson;

- (void)labelPickerViewController:(id)arg1 didSelectLabel:(id)arg2;
- (void)labelPickerViewControllerDidCancel:(id)arg1;
- (void)labelButtonTappedInCell:(id)arg1;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)presentLabelPicker;
- (void)textFieldValueChanged:(id)arg1;
- (void)saveAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)validateUserInput;
- (void)dealloc;
- (id)init;
- (id)initWithDelegate:(id)arg1;

@end

