//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextViewDelegate.h"

@class WAInputTextView;

@protocol WAInputTextViewDelegate <UITextViewDelegate>
- (void)textViewDidPasteImage:(WAInputTextView *)arg1;
- (void)textView:(WAInputTextView *)arg1 needsHeightChangedTo:(float)arg2;
- (float)textViewMaximumHeight:(WAInputTextView *)arg1;
@end

