//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WARecipientsViewControllerDelegate.h"

@class NSFetchedResultsController, UITableView, UIView, WAChatSession;

__attribute__((visibility("hidden")))
@interface WAListsViewController : WAViewController <NSFetchedResultsControllerDelegate, WARecipientsViewControllerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    NSFetchedResultsController *_fetchedResultsController;
    UIView *_emptyListView;
    UITableView *_tableView;
    BOOL _chatStorageAvailable;
    WAChatSession *_activeList;
}


- (void)fontSizeDidChange:(id)arg1;
- (void)chatStorageDidLoadDatabase:(id)arg1;
- (void)chatStorageWillUnloadDatabase:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)recipientsController:(id)arg1 didFinishWithContacts:(id)arg2;
- (void)recipientsControllerDidCancel:(id)arg1;
- (void)createNewList:(id)arg1;
- (void)deleteExistingList:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned int)arg3 forChangeType:(unsigned int)arg4;
- (void)controllerWillChangeContent:(id)arg1;
- (void)setUpFetchRequest;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)navigateToList:(id)arg1 animated:(BOOL)arg2;
- (void)updateInterfaceWithAnimation:(BOOL)arg1;
- (void)setUpEmptyListView;
- (void)setBackButtonHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)resetAllSeparatorInsets;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)uniqueIdentifier;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;

@end

