//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface WAListTableViewCell : UITableViewCell
{
    UILabel *_nameLabel;
    UILabel *_participantsLabel;
}

+ (id)cellWithReuseIdentifier:(id)arg1;

- (void)layoutSubviews;
- (id)systemAccessoryView;
- (void)setSystemAccessoryViewHidden:(BOOL)arg1;
- (void)willTransitionToState:(unsigned int)arg1;
- (void)configureWithList:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

