//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

#import "UINavigationControllerDelegate.h"
#import "WAMediaPickerDataSource.h"
#import "WAWallpaperPreviewControllerDelegate.h"

@class WAMediaPickerLibraryController;

__attribute__((visibility("hidden")))
@interface WallpaperSourceViewController : WATableViewController <UINavigationControllerDelegate, WAMediaPickerDataSource, WAWallpaperPreviewControllerDelegate>
{
    BOOL _photoLibraryAvailable;
    WAMediaPickerLibraryController *_libraryController;
}

+ (id)controller;

- (void)clearSelection;
- (void)showMaximumSelectionCountExceededError;
- (void)toggleSelectionOfMediaPickerAsset:(id)arg1;
- (BOOL)canAddMoreMediaPickerAssets;
- (BOOL)canSelectMediaPickerAsset:(id)arg1;
- (id)selectedAssetURLs;
- (BOOL)allowsMultipleSelection;
- (id)libraryController;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)wallpaperPreviewControllerDidCancel:(id)arg1;
- (void)wallpaperPreviewController:(id)arg1 didSelectImage:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)deleteSavedWallpaper;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

