//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "MKAnnotation.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface WALocationDataGroup : NSObject <MKAnnotation>
{
    NSMutableArray *_locations;
}


- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) NSString *subtitle;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) CDStruct_c3b9c2ee coordinate;
- (id)locations;
- (id)baseLocation;
- (void)addLocationData:(id)arg1;
- (id)locationAtIndex:(unsigned int)arg1;
- (unsigned int)numberOfLocations;
- (id)initWithLocations:(id)arg1;
- (id)initWithLocation:(id)arg1;

@end

