//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageHelper.h"

__attribute__((visibility("hidden")))
@interface WALocationMessageHelper : WAMessageHelper
{
}

- (id)stringRepresentation;
- (void)internalGenerateXMPPThumbnailFromImageRepresentation:(id)arg1 completion:(id)arg2;
- (void)internalGenerateChatThumbnailFromImageRepresentation:(id)arg1 completion:(id)arg2;
- (struct CGSize)chatThumbnailSize;
- (id)chatThumbnailReturningPermanentState:(char *)arg1;

@end

