//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, WAMediaPlayerSlider;

__attribute__((visibility("hidden")))
@interface WAMediaPlayerTransportControlView : UIView
{
    WAMediaPlayerSlider *_slider;
    UILabel *_currentTimeLabel;
    UILabel *_remainingTimeLabel;
    BOOL _scrubbingInProgress;
    id <WAMediaPlayerTransportControlViewDelegate> _delegate;
}

@property(readonly, nonatomic) BOOL scrubbingInProgress; // @synthesize scrubbingInProgress=_scrubbingInProgress;
@property(nonatomic) id <WAMediaPlayerTransportControlViewDelegate> delegate; // @synthesize delegate=_delegate;

- (void)sliderTouchEnd:(id)arg1;
- (void)sliderValueChanged:(id)arg1;
- (void)updateTimeLabels;
@property(nonatomic) double currentTime;
@property(nonatomic) double duration;
- (void)reset;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

