//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSIndexPath, UIScreenEdgePanGestureRecognizer, UIViewController;

@protocol WAMediaGalleryControllerDelegate <NSObject>
- (void)mediaGalleryController:(UIViewController *)arg1 didSelectMediaAtIndexPath:(NSIndexPath *)arg2;

@optional
- (void)mediaGalleryController:(UIViewController *)arg1 interactiveDismissGestureDidChange:(UIScreenEdgePanGestureRecognizer *)arg2;
- (void)mediaGalleryControllerDidExit:(UIViewController *)arg1;
@end

