//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WAMessageStatusView : UIView
{
    unsigned int _messageStatus;
    unsigned int _style;
    NSString *_timestampString;
}

+ (struct CGSize)sizeOfAreaForTimestampString:(id)arg1 messageStatus:(unsigned int)arg2;
+ (struct CGSize)sizeOfAreaForTimestampString:(id)arg1 messageStatus:(unsigned int)arg2 style:(unsigned int)arg3;
+ (id)messageStatusImageForStatus:(unsigned int)arg1 style:(unsigned int)arg2;
@property(retain, nonatomic) NSString *timestampString; // @synthesize timestampString=_timestampString;
@property(nonatomic) unsigned int style; // @synthesize style=_style;
@property(nonatomic) unsigned int messageStatus; // @synthesize messageStatus=_messageStatus;

- (BOOL)hasContent;
- (void)drawInContext:(struct CGContext *)arg1 fromPoint:(struct CGPoint)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

