//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSConditionLock, NSString, UIImage, WAMessage;

__attribute__((visibility("hidden")))
@interface WAMessageHelper : NSObject
{
    int _activeOperationCount;
    struct dispatch_group_s *_thumbnailLoadingGroup;
    struct dispatch_queue_s *_thumbnailLoadingQueue;
    NSConditionLock *_xmppLoadingLock;
    BOOL _thumbnailLoadingInProgress;
    WAMessage *_message;
    UIImage *_imageRepresentation;
    UIImage *_loResImageRepresentation;
    UIImage *_xmppImage;
    UIImage *_blurredImage;
    double _cachedMediaDuration;
}

+ (BOOL)needsBlurredImage;
+ (float)blurredImageMaximumWidth;
+ (struct CGSize)mediaBrowserThumbnailSize;
+ (double)durationOfVideoAtPath:(id)arg1;
+ (id)jpegDataFromImage:(id)arg1 error:(id *)arg2;
+ (BOOL)checkMediaSize:(id)arg1 error:(id *)arg2;
+ (id)errorWithDescription:(id)arg1 failureReason:(id)arg2;
+ (void)initialize;
+ (Class)helperClassForMessage:(id)arg1;
+ (id)messageHelperForMessage:(id)arg1;
@property BOOL thumbnailLoadingInProgress; // @synthesize thumbnailLoadingInProgress=_thumbnailLoadingInProgress;
@property(nonatomic) double cachedMediaDuration; // @synthesize cachedMediaDuration=_cachedMediaDuration;
@property(retain) UIImage *blurredImage; // @synthesize blurredImage=_blurredImage;
@property(retain) UIImage *xmppImage; // @synthesize xmppImage=_xmppImage;
@property(retain, nonatomic) UIImage *loResImageRepresentation; // @synthesize loResImageRepresentation=_loResImageRepresentation;
@property(retain) UIImage *imageRepresentation; // @synthesize imageRepresentation=_imageRepresentation;
@property(nonatomic) WAMessage *message; // @synthesize message=_message;

- (id)activityDataTypeIdentifierForActivityType:(id)arg1;
- (id)activitySubjectForActivityType:(id)arg1;
- (id)activityItemForActivityType:(id)arg1;
- (id)activityPlaceholderItem;
@property(readonly, nonatomic) NSString *stringRepresentation;
- (id)senderNameForStringRepresentation;
- (void)internalRepeatedlyFetchBetterThumbnailsWithBlock:(id)arg1;
- (void)repeatedlyFetchBetterThumbnailsWithBlock:(id)arg1;
- (void)prepareForDisplayWithCompletionHandler:(id)arg1;
- (id)generateImageRepresentationFromSourceMediaAtPath:(id)arg1;
- (struct CGSize)chatThumbnailSize;
- (id)chatThumbnailReturningPermanentState:(char *)arg1;
- (void)internalGenerateMediaBrowserThumbnailFromImageRepresentation:(id)arg1 completion:(id)arg2;
- (void)generateMediaBrowserThumbnailWithCompletionHandler:(id)arg1;
- (void)internalGenerateChatThumbnailFromImageRepresentation:(id)arg1 completion:(id)arg2;
- (void)generateChatThumbnailWithCompletionHandler:(id)arg1;
- (void)internalGenerateXMPPThumbnailFromImageRepresentation:(id)arg1 completion:(id)arg2;
- (void)generateXMPPThumbnailWithCompletionHandler:(id)arg1;
- (void)internalFetchImageRepresentationWithCompletionHandler:(id)arg1;
- (void)fetchImageRepresentationWithCompletionHandler:(id)arg1;
- (void)messageDidStoreIncomingMedia;
- (void)storeIncomingMediaWithFilename:(id)arg1 data:(id)arg2 completion:(id)arg3;
- (id)localMediaFilenameFromRemoteFilename:(id)arg1;
- (void)sanitizeIncomingMediaData:(id)arg1 completion:(id)arg2;
- (void)storeOutgoingMedia:(id)arg1 completion:(id)arg2;
- (BOOL)isProcessing;
- (void)freeCachedData;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

@end

