//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class UIButton, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface WAMessageAlertsReminderViewController : WAViewController
{
    UIButton *_buttonClose;
    UILabel *_labelItem1;
    UILabel *_labelItem2;
    UILabel *_labelItem3;
    UILabel *_labelTitle;
    UILabel *_labelOpenSettings;
    UILabel *_labelTapNotifications;
    UILabel *_labelTurnOnMessageNotifications;
    UILabel *_labelMessageAlerts;
    UIView *_viewMessageAlerts;
}

+ (BOOL)canPresentReminder;
+ (id)controller;
@property(retain, nonatomic) UIView *viewMessageAlerts; // @synthesize viewMessageAlerts=_viewMessageAlerts;
@property(retain, nonatomic) UILabel *labelMessageAlerts; // @synthesize labelMessageAlerts=_labelMessageAlerts;
@property(retain, nonatomic) UILabel *labelTurnOnMessageNotifications; // @synthesize labelTurnOnMessageNotifications=_labelTurnOnMessageNotifications;
@property(retain, nonatomic) UILabel *labelTapNotifications; // @synthesize labelTapNotifications=_labelTapNotifications;
@property(retain, nonatomic) UILabel *labelOpenSettings; // @synthesize labelOpenSettings=_labelOpenSettings;
@property(retain, nonatomic) UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(retain, nonatomic) UILabel *labelItem3; // @synthesize labelItem3=_labelItem3;
@property(retain, nonatomic) UILabel *labelItem2; // @synthesize labelItem2=_labelItem2;
@property(retain, nonatomic) UILabel *labelItem1; // @synthesize labelItem1=_labelItem1;
@property(retain, nonatomic) UIButton *buttonClose; // @synthesize buttonClose=_buttonClose;

- (void)closeAction:(id)arg1;
- (void)dismiss;
- (void)presentModallyFromViewController:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (int)preferredStatusBarStyle;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

