//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface WAMediaPickerAlbumTableViewCell : UITableViewCell
{
    NSMutableArray *_assetViews;
    BOOL _allowsMultipleSelection;
    int _maximumAssetsPerRow;
    id <WAMediaPickerAlbumTableViewCellDelegate> _delegate;
}

+ (id)cellWithReuseIdentifier:(id)arg1;
+ (int)assetsCountForRowOfWidth:(float)arg1;
@property(readonly, nonatomic) NSMutableArray *assetViews; // @synthesize assetViews=_assetViews;
@property(nonatomic) BOOL allowsMultipleSelection; // @synthesize allowsMultipleSelection=_allowsMultipleSelection;
@property(nonatomic) id <WAMediaPickerAlbumTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int maximumAssetsPerRow; // @synthesize maximumAssetsPerRow=_maximumAssetsPerRow;

- (void)assetViewTapped:(id)arg1;
- (void)configureWithMediaPickerAssets:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

