//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSError, WAMediaUploadOperationBase;

@protocol WAMediaUploadOperationDelegate <NSObject>
- (void)mediaUploadOperation:(WAMediaUploadOperationBase *)arg1 uploadProgressChanged:(float)arg2;
- (void)mediaUploadOperation:(WAMediaUploadOperationBase *)arg1 didFailWithError:(NSError *)arg2;
- (void)mediaUploadOperationDidFinish:(WAMediaUploadOperationBase *)arg1;
@end

