//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSNumber, NSString, WAMessage;

__attribute__((visibility("hidden")))
@interface WAMediaItem : NSManagedObject
{
    BOOL _networkActivity;
    BOOL _mediaSaved;
}

@property(nonatomic) BOOL mediaSaved; // @synthesize mediaSaved=_mediaSaved;
@property(nonatomic) BOOL networkActivity; // @synthesize networkActivity=_networkActivity;
@property(readonly, nonatomic) NSString *placeDetails;
@property(retain, nonatomic) NSString *fileHash;
@property(retain, nonatomic) NSString *mediaLocalPath; // @dynamic mediaLocalPath;

// Remaining properties
@property(retain, nonatomic) NSString *authorName; // @dynamic authorName;
@property(retain, nonatomic) NSString *collectionName; // @dynamic collectionName;
@property(retain, nonatomic) NSString *featureInfo; // @dynamic featureInfo;
@property(retain, nonatomic) NSNumber *fileSize; // @dynamic fileSize;
@property(retain, nonatomic) NSNumber *latitude; // @dynamic latitude;
@property(retain, nonatomic) NSNumber *longitude; // @dynamic longitude;
@property(retain, nonatomic) NSNumber *mediaOrigin; // @dynamic mediaOrigin;
@property(retain, nonatomic) NSString *mediaURL; // @dynamic mediaURL;
@property(retain, nonatomic) WAMessage *message; // @dynamic message;
@property(retain, nonatomic) NSNumber *movieDuration; // @dynamic movieDuration;
@property(retain, nonatomic) NSString *thumbnailLocalPath; // @dynamic thumbnailLocalPath;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSString *vCardName; // @dynamic vCardName;
@property(retain, nonatomic) NSString *vCardString; // @dynamic vCardString;
@property(retain, nonatomic) NSString *xmppThumbPath; // @dynamic xmppThumbPath;

@end

