//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class WAMediaPlayerTransportControlView;

@protocol WAMediaPlayerTransportControlViewDelegate <NSObject>
- (void)mediaPlayerTransportControlViewDidChangeCurrentTime:(WAMediaPlayerTransportControlView *)arg1;
- (void)mediaPlayerTransportControlViewDidEndScrubbing:(WAMediaPlayerTransportControlView *)arg1;
- (void)mediaPlayerTransportControlViewDidBeginScrubbing:(WAMediaPlayerTransportControlView *)arg1;
@end

