//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class WAMediaPickerAlbumController;

@protocol WAMediaPickerAlbumControllerDelegate <NSObject>
- (void)mediaPickerAlbumController:(WAMediaPickerAlbumController *)arg1 didFinishLoadingAlbumWithOutcome:(BOOL)arg2;
- (void)mediaPickerAlbumControllerWillBeginLoadingAlbum:(WAMediaPickerAlbumController *)arg1;
@end

