//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "WABubbleViewDelegate.h"
#import "WAMediaProgressDelegate.h"

@class UIButton, UIImage, UIImageView, UIProgressView, UIView, WAChatCellData;

__attribute__((visibility("hidden")))
@interface WAMessageCell : UITableViewCell <WABubbleViewDelegate, WAMediaProgressDelegate>
{
    WAChatCellData *_cellData;
    UIView *_bubbleView;
    UIImageView *_imageViewBubble;
    UIImageView *_imageViewCheckmark;
    UIButton *_buttonAlert;
    UIButton *_buttonView;
    UIButton *_buttonDownload;
    UIButton *_buttonForward;
    UIButton *_buttonCancel;
    UIProgressView *_progressView;
    UIImageView *_progressViewBox;
    UIImage *_checkMarkNormal;
    UIImage *_checkMarkChecked;
    struct _cellFlags {
        unsigned int showAlertButton:1;
        unsigned int showMessageStatus:1;
        unsigned int showProgressBar:1;
        unsigned int showDownloadButton:1;
        unsigned int showViewButton:1;
        unsigned int showForwardButton:1;
        unsigned int showCancelButton:1;
        unsigned int cellSelected:1;
    } _flags;
    BOOL _permanentThumbnail;
    id <WAMessageCellDelegate> _delegate;
    BOOL _singleTapDisabled;
    int _contentHorizontalAlignment;
}

+ (float)maxBubbleWidthForCellWidth:(float)arg1 editing:(BOOL)arg2 showAlert:(BOOL)arg3;
+ (float)heightForCellData:(id)arg1 width:(float)arg2 editing:(BOOL)arg3;
+ (id)cellReuseIdentifier;
+ (Class)cellClassForCellData:(id)arg1;
@property(nonatomic) BOOL singleTapDisabled; // @synthesize singleTapDisabled=_singleTapDisabled;
@property(nonatomic) id <WAMessageCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int contentHorizontalAlignment; // @synthesize contentHorizontalAlignment=_contentHorizontalAlignment;
@property(readonly, nonatomic) UIView *bubbleView; // @synthesize bubbleView=_bubbleView;
@property(readonly, nonatomic) WAChatCellData *cellData; // @synthesize cellData=_cellData;

- (void)setProgress:(float)arg1 forMessage:(id)arg2;
- (void)replyMessageSenderFromBubbleView:(id)arg1;
- (void)addMessageSenderInBubbleView:(id)arg1;
- (void)deleteMessageInBubbleView:(id)arg1;
- (void)forwardMessageInBubbleView:(id)arg1;
- (void)copyMessageInBubbleView:(id)arg1;
- (void)openURL:(id)arg1 fromBubbleView:(id)arg2;
- (void)handleDoubleTapActionInBubbleView:(id)arg1;
- (void)handleSingleTapActionInBubbleView:(id)arg1;
- (BOOL)canPerformDoubleTapActionInBubbleView:(id)arg1;
- (BOOL)canPerformSingleTapActionInBubbleView:(id)arg1;
- (BOOL)canDimBubbleView:(id)arg1;
- (BOOL)bubbleView:(id)arg1 canPerformAction:(SEL)arg2 withSender:(id)arg3;
- (void)setHighlightState:(BOOL)arg1 forBubbleView:(id)arg2 animated:(BOOL)arg3;
- (id)shortNameForBubbleView:(id)arg1;
- (void)layoutSubviews;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)referenceViewForPopupMenu;
- (struct CGRect)targetRectForPopupMenu;
- (void)resetAppearance;
- (void)setProgress:(float)arg1;
- (BOOL)cellSelected;
- (void)setCellSelected:(BOOL)arg1;
- (void)setShowsProgressBar:(BOOL)arg1;
- (void)setShowCancelButton:(BOOL)arg1;
- (void)setShowForwardButton:(BOOL)arg1;
- (void)setShowViewButton:(BOOL)arg1;
- (void)setShowDownloadButton:(BOOL)arg1;
- (void)setShowAlertButton:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setShowMessageStatus:(BOOL)arg1;
- (void)setBubbleHighlighted:(BOOL)arg1;
- (void)setDimmed:(BOOL)arg1;
- (BOOL)isAnimating;
- (void)showPopupMenu;
- (void)setCellData:(id)arg1 delegate:(id)arg2;
- (BOOL)selectable;
- (void)refreshUI;
- (id)buttonCancel;
- (id)buttonForward;
- (id)buttonView;
- (id)buttonDownload;
- (id)buttonAlert;
- (void)cancelButtonTapped:(id)arg1;
- (void)forwardButtonTapped:(id)arg1;
- (void)viewButtonTapped:(id)arg1;
- (void)downloadButtonTapped:(id)arg1;
- (void)alertButtonTapped:(id)arg1;
- (void)updateCellBackground;
- (void)configureCellUpdatingAllContents:(BOOL)arg1 animated:(BOOL)arg2;
- (void)updateDownloadButtonTitle;
- (void)updateViewButtonTitle;
- (id)checkMarkChecked;
- (id)checkMarkNormal;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

