//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSString, WAMessage;

__attribute__((visibility("hidden")))
@interface WAMessageWord : NSManagedObject
{
}


// Remaining properties
@property(retain, nonatomic) WAMessage *message; // @dynamic message;
@property(retain, nonatomic) NSString *word; // @dynamic word;
@end

