//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ALAsset, UIImageView, WAMediaPickerVideoAssetOverlayView;

__attribute__((visibility("hidden")))
@interface WAMediaPickerAssetView : UIView
{
    UIImageView *_imageView;
    UIImageView *_checkmarkImageView;
    UIView *_dimmingView;
    WAMediaPickerVideoAssetOverlayView *_videoOverlayView;
    BOOL _isVideo;
    ALAsset *_currentAsset;
    BOOL _showsCheckmarkWhenSelected;
    BOOL _selected;
    BOOL _imageDimmed;
}

@property(nonatomic) BOOL imageDimmed; // @synthesize imageDimmed=_imageDimmed;
@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(nonatomic) BOOL showsCheckmarkWhenSelected; // @synthesize showsCheckmarkWhenSelected=_showsCheckmarkWhenSelected;

- (void)performSelectionRefusedAnimation;
- (id)accessibilityLabel;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)configureWithMediaPickerAsset:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

