//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMediaPickerLibraryTableViewCell.h"

__attribute__((visibility("hidden")))
@interface WAMediaPickerLibraryTableViewCell6 : WAMediaPickerLibraryTableViewCell
{
}

+ (int)preferredSeparatorStyle;
+ (float)preferredHeight;
- (id)assetCountLabelTextForCount:(int)arg1;
- (void)configureWithAssetsGroup:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

