//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "NSCoding.h"

@class NSDate;

__attribute__((visibility("hidden")))
@interface WAMediaDownloadPolicy : NSObject <NSCoding>
{
    BOOL _isDefaultPolicy;
    NSDate *_imageDownloadEnabledAtTime;
    NSDate *_audioDownloadEnabledAtTime;
    NSDate *_videoDownloadEnabledAtTime;
    int _autoDownloadPolicyImages;
    int _autoDownloadPolicyVideos;
    int _autoDownloadPolicyAudio;
}

+ (id)defaultPolicy;
@property(nonatomic) int autoDownloadPolicyAudio; // @synthesize autoDownloadPolicyAudio=_autoDownloadPolicyAudio;
@property(nonatomic) int autoDownloadPolicyVideos; // @synthesize autoDownloadPolicyVideos=_autoDownloadPolicyVideos;
@property(nonatomic) int autoDownloadPolicyImages; // @synthesize autoDownloadPolicyImages=_autoDownloadPolicyImages;

- (void)configureAutoDownloadRequest:(id)arg1 forMessage:(id)arg2;
- (int)shouldAutoDownloadMessage:(id)arg1;
- (void)save;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)resetToDefaults;
- (id)init;

@end

