//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WAMediaPlayerDelegate.h"
#import "WAMediaPlayerTransportControlViewDelegate.h"

@class NSString, UIImageView, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView, WAMediaPlayer, WAMediaPlayerTransportControlView, WAMessage;

__attribute__((visibility("hidden")))
@interface WAMediaScrollView : UIScrollView <WAMediaPlayerTransportControlViewDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate, WAMediaPlayerDelegate>
{
    UIImageView *_imageView;
    float _initialZoomScale;
    UIImageView *_audioOnlyBackgroundImageView;
    UIImageView *_audioOnlyLogoImageView;
    WAMessage *_currentMediaMessage;
    NSString *_errorMessageToShowOnNextPlayAttempt;
    WAMediaPlayerTransportControlView *_playerTransportBar;
    UILongPressGestureRecognizer *_longPressGesture;
    UITapGestureRecognizer *_doubleTapGesture;
    BOOL _mediaControlsHidden;
    id <WAMediaScrollViewDelegate> _mediaDelegate;
    unsigned int _index;
    float _topLayoutEdge;
    float _offset;
    WAMediaPlayer *_mediaPlayer;
}

@property(readonly, nonatomic) WAMediaPlayer *mediaPlayer; // @synthesize mediaPlayer=_mediaPlayer;
@property(nonatomic) BOOL mediaControlsHidden; // @synthesize mediaControlsHidden=_mediaControlsHidden;
@property(nonatomic) float offset; // @synthesize offset=_offset;
@property(nonatomic) float topLayoutEdge; // @synthesize topLayoutEdge=_topLayoutEdge;
@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(nonatomic) id <WAMediaScrollViewDelegate> mediaDelegate; // @synthesize mediaDelegate=_mediaDelegate;

- (void)mediaPlayerTransportControlViewDidChangeCurrentTime:(id)arg1;
- (void)mediaPlayerTransportControlViewDidEndScrubbing:(id)arg1;
- (void)mediaPlayerTransportControlViewDidBeginScrubbing:(id)arg1;
- (void)mediaPlayerDidEndScrubbing:(id)arg1;
- (void)mediaPlayerDidBeginScrubbing:(id)arg1;
- (void)mediaPlayerDidPlayToEndTime:(id)arg1;
- (void)mediaPlayerDidFinishLoading:(id)arg1;
- (void)mediaPlayerDidChangeCurrentTime:(id)arg1;
- (void)mediaPlayerStatusDidChange:(id)arg1;
- (void)handlePlaybackError;
- (void)displayMediaInMessage:(id)arg1;
@property(readonly, nonatomic, getter=isPlayable) BOOL playable;
- (void)mediaPlayerDidRequestPlaybackStart:(id)arg1;
- (void)pause;
- (void)playInitiatedByAutoPlay:(BOOL)arg1;
- (void)displayQTLogo;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
@property(readonly, nonatomic) BOOL isLongPressing;
- (void)handleLongPress:(id)arg1;
- (void)handleDoubleTap:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)showPopupMenuAtPoint:(struct CGPoint)arg1;
- (void)copy:(id)arg1;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)configureZooming;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)toggleZoomInOutAtPoint:(struct CGPoint)arg1;
- (void)setMediaControlsHidden:(BOOL)arg1 animationDuration:(double)arg2;
- (void)animateOutImageView:(id)arg1 completion:(id)arg2;
- (void)animateDeletionWithCompletionHandler:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIView *contentView;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

