//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ALAssetsGroup, UILabel;

__attribute__((visibility("hidden")))
@interface WAMediaPickerLibraryTableViewCell : UITableViewCell
{
    ALAssetsGroup *_currentAssetsGroup;
    UILabel *_assetCountLabel;
}

+ (int)preferredSeparatorStyle;
+ (float)preferredHeight;
+ (id)cellWithReuseIdentifier:(id)arg1;
@property(readonly, nonatomic) UILabel *assetCountLabel; // @synthesize assetCountLabel=_assetCountLabel;

- (void)updateWithAssetCount:(int)arg1;
- (id)assetCountLabelTextForCount:(int)arg1;
- (void)configureWithAssetsGroup:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

