//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WATableViewController.h"

@class WADoneWithSpinnerBarButtonItem;

__attribute__((visibility("hidden")))
@interface WAMediaPickerBaseViewController : WATableViewController
{
    WADoneWithSpinnerBarButtonItem *_doneButton;
    BOOL _showDoneButton;
    id <WAMediaPickerDataSource> _mediaPickerDataSource;
}

@property(nonatomic) BOOL showDoneButton; // @synthesize showDoneButton=_showDoneButton;
@property(nonatomic) id <WAMediaPickerDataSource> mediaPickerDataSource; // @synthesize mediaPickerDataSource=_mediaPickerDataSource;

- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (id)toolbarItems;
- (BOOL)scrollEnabled;
- (void)done:(id)arg1;
- (void)updateDoneButton;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)mediaPickerLibraryControllerDidUpdateAssetsGroups:(id)arg1;
- (void)mediaPickerLibraryControllerDidFinishLoadingLibrary:(id)arg1;
- (void)mediaPickerLibraryControllerWillBeginLoadingLibrary:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;

@end

