//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "ForwardPickerDelegate.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WAImageToImageTransitioning.h"
#import "WAMediaGalleryControllerDelegate.h"
#import "WAMediaScrollViewDelegate.h"

@class NSMutableSet, NSTimer, UIBarButtonItem, UILabel, UIScrollView, UIToolbar, UIView, WAMediaManager, WAMessage, WAProgressHUD;

__attribute__((visibility("hidden")))
@interface WAMediaViewController : WAViewController <UIScrollViewDelegate, UINavigationControllerDelegate, ABPeoplePickerNavigationControllerDelegate, ForwardPickerDelegate, MFMailComposeViewControllerDelegate, WAMediaScrollViewDelegate, WAMediaGalleryControllerDelegate, WAImageToImageTransitioning>
{
    NSMutableSet *_recycledPages;
    NSMutableSet *_visiblePages;
    BOOL _suppressRelayoutInScrollViewDidScroll;
    BOOL _tiling;
    NSTimer *_hideBarsTimer;
    WAProgressHUD *_progressHUD;
    BOOL _shouldAutoPlay;
    BOOL _shouldResumePlayback;
    BOOL _fullScreenMode;
    float _lastStatusBarHeight;
    UIBarButtonItem *_showAllButton;
    UIBarButtonItem *_actionButton;
    UIBarButtonItem *_trashButton;
    UIBarButtonItem *_playButton;
    UIBarButtonItem *_pauseButton;
    UIBarButtonItem *_previousButton;
    UIBarButtonItem *_nextButton;
    NSTimer *_holdingTimer;
    BOOL _holding;
    BOOL _mediaManagerUpdateInProgress;
    WAMessage *_currentMessage;
    BOOL _reloadCurrentMessageOnAppear;
    WAMediaManager *_mediaManager;
    int _currentPageIndex;
    UIScrollView *_pagingScrollView;
    UIToolbar *_toolbar;
    UIView *_viewMediaInfo;
    UILabel *_labelMediaInfo;
}

@property(retain, nonatomic) UILabel *labelMediaInfo; // @synthesize labelMediaInfo=_labelMediaInfo;
@property(retain, nonatomic) UIView *viewMediaInfo; // @synthesize viewMediaInfo=_viewMediaInfo;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIScrollView *pagingScrollView; // @synthesize pagingScrollView=_pagingScrollView;
@property(nonatomic) int currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) WAMediaManager *mediaManager; // @synthesize mediaManager=_mediaManager;

- (void)applicationWillPresentCallScreen:(id)arg1;
- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (BOOL)shouldUseImageToImageTransitionForOperation:(int)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)setCurrentPageIndex:(int)arg1 scrollToPage:(BOOL)arg2;
- (void)refreshInterfaceOnPageChange;
- (void)mediaGalleryController:(id)arg1 didSelectMediaAtIndexPath:(id)arg2;
- (void)forwardPickerDidCancel:(id)arg1;
- (void)forwardPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)assignImage:(id)arg1 toContactID:(int)arg2;
- (void)dismissPickerAndContinueWithPerson:(void *)arg1;
- (void)assignImageToContact;
- (void)saveCurrentVideo;
- (void)saveCurrentImage;
- (void)showFailedToSaveMediaAlertView;
- (void)showTransitoryHUDMessage:(id)arg1;
- (void)mediaScrollViewDidEndScrubbing:(id)arg1;
- (void)mediaScrollViewDidBeginScrubbing:(id)arg1;
- (struct UIEdgeInsets)mediaScrollViewLayoutInset:(id)arg1;
- (BOOL)mediaScrollViewCanShowErrorAlertView:(id)arg1;
- (void)mediaScrollViewWantsFullscreenTimerInvalidated:(id)arg1;
- (void)mediaScrollViewDidFinishLongPress:(id)arg1;
- (void)mediaScrollViewDidReceiveSingleTap:(id)arg1;
- (void)mediaScrollViewPlaybackDidFinish:(id)arg1;
- (void)mediaScrollViewPlaybackStateDidChange:(id)arg1;
- (void)mediaScrollViewLoadStateDidChange:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)rotatingFooterView;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (BOOL)shouldAutorotate;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)deleteCurrentMedia:(id)arg1;
- (void)showAllMedia:(id)arg1;
- (void)navigateToNextPage:(id)arg1;
- (void)beginSeekingForward:(id)arg1;
- (void)handleNextButtonTouchDown:(id)arg1;
- (void)handleNextButtonTouchUp:(id)arg1;
- (void)navigateToPreviousPage:(id)arg1;
- (void)beginSeekingBackward:(id)arg1;
- (void)handlePreviousButtonTouchDown:(id)arg1;
- (void)handlePreviousButtonTouchUp:(id)arg1;
- (void)showMediaActions:(id)arg1;
- (void)togglePlayPause:(id)arg1;
- (void)reallyDeleteCurrentMedia;
- (void)tilePages;
- (void)configurePage:(id)arg1 forIndex:(unsigned int)arg2;
- (id)pageForIndex:(unsigned int)arg1;
- (BOOL)isDisplayingPageForIndex:(unsigned int)arg1;
- (void)recyclePage:(id)arg1;
- (id)dequeueRecycledPage;
- (void)forwardMediaViaEmail;
- (void)forwardMediaViaWhatsAppToContact:(id)arg1;
- (void)showPersonPickerForMediaForwardViaWhatsApp;
- (void)removeHUD;
- (void)showHUD:(id)arg1;
- (void)setProfilePhoto;
- (void)assignCurrentImageToGroup;
- (void)hideBarsTimer:(id)arg1;
- (void)cancelHideBarsTimer;
- (void)startHideBarsTimer;
- (BOOL)prefersStatusBarHidden;
- (int)preferredStatusBarStyle;
- (void)setFullScreenMode:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setFullScreenMode:(BOOL)arg1;
- (BOOL)fullScreenModeAllowed;
- (void)updateToolbar;
- (void)updateUIWithOrientation:(int)arg1;
- (void)reloadPagingScrollView;
- (float)topLayoutEdge;
- (struct CGRect)frameForPageAtIndex:(unsigned int)arg1;
- (struct CGRect)frameForPagingScrollView;
- (void)mediaManagerDidChangeContent:(id)arg1;
- (void)mediaManagerWillChangeContent:(id)arg1;
- (void)reloadMediaViewer;
- (id)uniqueIdentifier;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

