//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class WAMediaPickerAlbumTableViewCell;

@protocol WAMediaPickerAlbumTableViewCellDelegate <NSObject>
- (BOOL)mediaPickerAlbumTableViewCell:(WAMediaPickerAlbumTableViewCell *)arg1 didReceiveTapAtIndex:(int)arg2;
@end

