//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMediaUploadOperationBase.h"

#import "NSURLConnectionDelegate.h"

@class NSDate, NSMutableData, NSString, NSURLConnection;

__attribute__((visibility("hidden")))
@interface WAMediaUploadOperation : WAMediaUploadOperationBase <NSURLConnectionDelegate>
{
    NSString *_fileName;
    NSDate *_startDate;
    NSURLConnection *_urlConnection;
    BOOL _isExecuting;
    BOOL _isFinished;
    NSString *_uploadURL;
    NSMutableData *_postData;
    NSMutableData *_receiveData;
    NSString *_mediaPath;
    unsigned long long _fileSize;
    int _bodySize;
    int _tailSize;
}


- (void)uploadRequestDidFailWithError:(id)arg1 userInfo:(id)arg2;
- (void)uploadRequestSucceeded:(id)arg1 userInfo:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(int)arg2 totalBytesWritten:(int)arg3 totalBytesExpectedToWrite:(int)arg4;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)startHTTPUploadFrom:(int)arg1;
- (id)hashOfMedia;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (void)cancel;
- (void)finish;
- (void)start;
- (void)dealloc;

@end

