//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class UIImageView, UILongPressGestureRecognizer, UIPanGestureRecognizer, UITapGestureRecognizer;

__attribute__((visibility("hidden")))
@interface WAMultiSendThumbnailBrowserItemView : UIView <UIGestureRecognizerDelegate>
{
    UIImageView *_overlayView;
    BOOL _selected;
    struct CGPoint _centerBeforeDraggingInSuperSuperviewCoordinates;
    UIPanGestureRecognizer *_panGesture;
    UITapGestureRecognizer *_singleTapGesture;
    UILongPressGestureRecognizer *_longPressGesture;
    int _index;
    unsigned int _state;
    id <WAMultiSendThumbnailBrowserItemViewDelegate> _delegate;
    UIImageView *_backgroundImageView;
}

+ (void)addWobbleAnimationToView:(id)arg1;
@property(readonly, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(readonly, nonatomic) UIImageView *overlayView; // @synthesize overlayView=_overlayView;
@property(nonatomic) id <WAMultiSendThumbnailBrowserItemViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
@property(nonatomic) int index; // @synthesize index=_index;

- (void)viewDidDrag:(id)arg1;
- (void)viewWasTapped:(id)arg1;
- (void)viewWasLongPressed:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)stopWobble;
- (void)startWobble;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)animateOutWithCompletionHandler:(id)arg1;
- (void)moveToCenter:(struct CGPoint)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

