//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "WAMediaPickerControllerDelegate.h"
#import "WAMultiSendPreviewViewControllerDelegate.h"
#import "WAVideoPreviewViewControllerDelegate.h"

@class NSDate, UIImagePickerController, WAMediaPickerController, WAMediaPickerLibraryController;

__attribute__((visibility("hidden")))
@interface WAMultiSendMediaPickerController : NSObject <WAMediaPickerControllerDelegate, UINavigationControllerDelegate, WAMultiSendPreviewViewControllerDelegate, UIImagePickerControllerDelegate, WAVideoPreviewViewControllerDelegate>
{
    WAMediaPickerController *_initialMediaPickerController;
    NSDate *_imagePickerDelayStartTime;
    double _imagePickerDelay;
    WAMediaPickerLibraryController *_libraryController;
    UIImagePickerController *_systemImagePickerController;
    id <WAMultiSendMediaPickerControllerDelegate> _delegate;
    unsigned int _pickerMode;
}

+ (BOOL)useNativePicker;
+ (void)initialize;
@property(readonly, nonatomic) unsigned int pickerMode; // @synthesize pickerMode=_pickerMode;
@property(nonatomic) id <WAMultiSendMediaPickerControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (void)videoPreviewViewControllerDidCancel:(id)arg1;
- (void)videoPreviewViewController:(id)arg1 didFailWithError:(id)arg2;
- (void)videoPreviewViewControllerDidConfirmVideo:(id)arg1;
- (void)nativePickerDidCancel;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)showPreviewViewControllerWithImage:(id)arg1 onNavigationController:(id)arg2;
- (void)showPreviewViewControllerUsingInterstitialWithImage:(id)arg1 onNavigationController:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishTakingPhotoWithInfo:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishSelectingImageFromCameraRollWithInfo:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)cleanUp;
- (void)cancelWithStats:(id)arg1;
- (id)initialStats;
- (void)multiSendPreviewViewControllerDidCancel:(id)arg1;
- (void)multiSendPreviewViewController:(id)arg1 didConfirmImages:(id)arg2;
- (void)mediaPickerControllerDidFinishPresenting:(id)arg1;
- (void)mediaPickerController:(id)arg1 didFinishWithSelectedAssetURLs:(id)arg2;
- (void)presentCustomPickerFromViewController:(id)arg1;
- (void)presentNativePickerFromViewController:(id)arg1;
- (void)presentCameraFromViewController:(id)arg1;
- (void)presentFromViewController:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (id)initWithPickerMode:(unsigned int)arg1;

@end

