//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMultiSendThumbnailBrowserItemView.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface WAMultiSendThumbnailBrowserAddItemButton : WAMultiSendThumbnailBrowserItemView
{
    UIButton *_button;
    unsigned int _buttonType;
}

@property(nonatomic) unsigned int buttonType; // @synthesize buttonType=_buttonType;

- (void)updateButtonHighlight:(id)arg1;
@property(nonatomic, getter=isHighlighted) BOOL highlighted;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)addTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned int)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

