//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "WAMultiSendThumbnailBrowserItemViewDelegate.h"

@class NSMutableArray, UIButton, UIImageView, UIToolbar, WAMultiSendThumbnailBrowserAddItemButton;

__attribute__((visibility("hidden")))
@interface WAMultiSendThumbnailBrowserView : UIView <WAMultiSendThumbnailBrowserItemViewDelegate, UIGestureRecognizerDelegate>
{
    UIImageView *_topBorderImageView;
    UIImageView *_backgroundImageView;
    NSMutableArray *_itemViews;
    UIButton *_viewBlocker;
    BOOL _draggingInProgress;
    BOOL _ignoreDragging;
    BOOL _footerHidden;
    int _maxItemsPerRow;
    BOOL _editingModeBeforeRotationAnimation;
    int _rowCount;
    float _itemWidth;
    UIView *_dimmingView;
    UIToolbar *_blurToolbarView;
    BOOL _editing;
    BOOL _dimmed;
    id <WAMultiSendThumbnailBrowserViewDelegate> _delegate;
    UIView *_headerView;
    int _currentIndex;
    int _maximumNumberOfItems;
    WAMultiSendThumbnailBrowserAddItemButton *_addItemButton;
    UIView *_footerView;
    UIButton *_sortMediaButton;
}

@property(retain, nonatomic) UIButton *sortMediaButton; // @synthesize sortMediaButton=_sortMediaButton;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) BOOL dimmed; // @synthesize dimmed=_dimmed;
@property(readonly, nonatomic) WAMultiSendThumbnailBrowserAddItemButton *addItemButton; // @synthesize addItemButton=_addItemButton;
@property(nonatomic) int maximumNumberOfItems; // @synthesize maximumNumberOfItems=_maximumNumberOfItems;
@property(nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_editing;
@property(nonatomic) int currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) id <WAMultiSendThumbnailBrowserViewDelegate> delegate; // @synthesize delegate=_delegate;

- (void)setDimmed:(BOOL)arg1 animated:(BOOL)arg2;
- (void)superViewDidEndRotationAnimation;
- (void)superViewWillBeginRotationAnimation;
- (void)updateFooterView;
- (BOOL)areItemsSorted;
- (void)sortMediaByDate:(id)arg1;
- (void)setFooterHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)swipeDown:(id)arg1;
- (void)swipeUp:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)multiSendThumbnailBrowserItemViewWasTapped:(id)arg1;
- (void)changeIndexOfItemView:(id)arg1 to:(int)arg2;
- (void)multiSendThumbnailBrowserItemViewCenterDidChange:(id)arg1;
- (void)multiSendThumbnailBrowserItemViewDidEndDragging:(id)arg1;
- (void)multiSendThumbnailBrowserItemViewDidBeginDragging:(id)arg1;
- (void)multiSendThumbnailBrowserItemViewWantsToEnterEditMode:(id)arg1;
- (void)sortItemViewsByIndex;
- (void)windowBlockerTouched:(id)arg1;
- (void)layoutViewBlocker;
- (void)removeViewBlocker;
- (void)addViewBlocker;
- (void)didMoveToWindow;
- (void)reloadThumbnailAtIndex:(int)arg1;
- (void)removeItemAtIndex:(int)arg1;
- (void)reload;
- (void)setCurrentIndex:(int)arg1 animated:(BOOL)arg2;
- (void)send:(id)arg1;
- (void)addItem:(id)arg1;
- (int)bestIndexForItemViewWithCenter:(struct CGPoint)arg1;
- (int)mapIndexToLogicalIndex:(int)arg1 ignoringOutsideItems:(BOOL)arg2;
- (struct CGPoint)centerForItemViewAtIndex:(int)arg1 ignoringOutsideItems:(BOOL)arg2;
- (void)relayoutThumbnailsWithAnimation:(BOOL)arg1;
- (void)layoutSubviews;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)configureFooterView;
@property(nonatomic) unsigned int addItemButtonType;
- (void)dealloc;
- (void)commonInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

