//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, WAMultiSendMediaItem, WAMultiSendThumbnailBrowserView;

@protocol WAMultiSendThumbnailBrowserViewDelegate <NSObject>
- (void)multiSendThumbnailBrowserViewDidRequestItemSort:(WAMultiSendThumbnailBrowserView *)arg1;
- (void)multiSendThumbnailBrowserViewDidChangeEditingMode:(WAMultiSendThumbnailBrowserView *)arg1;
- (void)multiSendThumbnailBrowserView:(WAMultiSendThumbnailBrowserView *)arg1 didMoveItemAtIndex:(int)arg2 toIndex:(int)arg3;
- (void)multiSendThumbnailBrowserView:(WAMultiSendThumbnailBrowserView *)arg1 didRequestSelectionOfItemAtIndex:(int)arg2;
- (void)multiSendThumbnailBrowserView:(WAMultiSendThumbnailBrowserView *)arg1 didRequestRemovalOfItemAtIndex:(int)arg2;
- (void)multiSendThumbnailBrowserViewDidRequestSend:(WAMultiSendThumbnailBrowserView *)arg1;
- (void)multiSendThumbnailBrowserViewDidRequestAddItem:(WAMultiSendThumbnailBrowserView *)arg1;
- (BOOL)areMultiSendMediaItemsSorted;
- (NSArray *)indicesOfMultiSendMediaItemsSortedByDate;
- (WAMultiSendMediaItem *)multiSendMediaItemAtIndex:(int)arg1;
- (int)multiSendThumbnailBrowserViewItemCount;
@end

