//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "WAImageToImageTransitioning.h"
#import "WAMediaPickerControllerDelegate.h"
#import "WAMultiSendThumbnailBrowserViewDelegate.h"
#import "WAPageableItemBrowserViewDelegate.h"

@class NSArray, NSDate, NSMutableArray, NSURL, UIImageView, UILabel, UIView, WAMediaPickerLibraryController, WAMultiSendMediaPickerControllerStats, WAMultiSendThumbnailBrowserView, WAPageableItemBrowserView;

__attribute__((visibility("hidden")))
@interface WAMultiSendPreviewViewController : WAViewController <WAPageableItemBrowserViewDelegate, WAMultiSendThumbnailBrowserViewDelegate, WAMediaPickerControllerDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, WAImageToImageTransitioning>
{
    int _selectedIndex;
    NSMutableArray *_mediaItems;
    NSURL *_selectedAssetURLBeforePresentingPicker;
    NSArray *_allAssetURLsBeforePresentingPicker;
    NSDate *_imagePickerDelayStartTime;
    int _imagePickerDelaySampleCount;
    double _minimumImagePickerDelay;
    double _maximumImagePickerDelay;
    double _totalImagePickerDelay;
    WAMediaPickerLibraryController *_libraryController;
    id <WAMultiSendPreviewViewControllerDelegate> _delegate;
    unsigned int _pickerMode;
    UIView *_hintView;
    WAMultiSendThumbnailBrowserView *_thumbnailBrowserView;
    WAPageableItemBrowserView *_pagingBrowserView;
    UILabel *_hintLabel;
    UIImageView *_hintBackgroundImageView;
}

@property(retain, nonatomic) UIImageView *hintBackgroundImageView; // @synthesize hintBackgroundImageView=_hintBackgroundImageView;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) WAPageableItemBrowserView *pagingBrowserView; // @synthesize pagingBrowserView=_pagingBrowserView;
@property(retain, nonatomic) WAMultiSendThumbnailBrowserView *thumbnailBrowserView; // @synthesize thumbnailBrowserView=_thumbnailBrowserView;
@property(retain, nonatomic) UIView *hintView; // @synthesize hintView=_hintView;
@property(nonatomic) unsigned int pickerMode; // @synthesize pickerMode=_pickerMode;
@property(nonatomic) id <WAMultiSendPreviewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAMediaPickerLibraryController *libraryController; // @synthesize libraryController=_libraryController;

- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (BOOL)shouldUseImageToImageTransitionForOperation:(int)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)moveThumbnailBrowserViewToBottom;
- (void)multiSendThumbnailBrowserViewDidRequestItemSort:(id)arg1;
- (BOOL)areMultiSendMediaItemsSorted;
- (id)indicesOfMultiSendMediaItemsSortedByDate;
- (void)multiSendThumbnailBrowserViewDidChangeEditingMode:(id)arg1;
- (void)multiSendThumbnailBrowserView:(id)arg1 didMoveItemAtIndex:(int)arg2 toIndex:(int)arg3;
- (void)multiSendThumbnailBrowserView:(id)arg1 didRequestSelectionOfItemAtIndex:(int)arg2;
- (id)multiSendMediaItemAtIndex:(int)arg1;
- (int)multiSendThumbnailBrowserViewItemCount;
- (void)multiSendThumbnailBrowserViewDidRequestAddItem:(id)arg1;
- (void)multiSendThumbnailBrowserView:(id)arg1 didRequestRemovalOfItemAtIndex:(int)arg2;
- (void)multiSendThumbnailBrowserViewDidRequestSend:(id)arg1;
- (void)pageableItemBrowserViewDidEndFocusedTask:(id)arg1;
- (void)pageableItemBrowserViewWillBeginFocusedTask:(id)arg1;
- (void)pageableItemBrowserView:(id)arg1 didFinishEditingItemAtIndex:(int)arg2;
- (void)pageableItemBrowserView:(id)arg1 didUpdateItemAtIndex:(int)arg2;
- (void)pageableItemBrowserView:(id)arg1 wantsToDeleteItemAtIndex:(int)arg2;
- (void)pageableItemBrowserViewCurrentIndexDidChange:(id)arg1;
- (int)pageableItemCount:(id)arg1;
- (id)pageableItemBrowserView:(id)arg1 itemAtIndex:(int)arg2;
- (Class)pageableItemBrowserView:(id)arg1 itemViewClassForPageableItem:(id)arg2;
- (void)setInitialStats:(id)arg1;
@property(readonly, nonatomic) WAMultiSendMediaPickerControllerStats *stats;
- (double)averageImagePickerDelay;
- (void)mediaPickerControllerDidFinishPresenting:(id)arg1;
- (void)mediaPickerController:(id)arg1 didFinishWithSelectedAssetURLs:(id)arg2;
- (void)addImageFromCamera:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (id)mediaItemWithURL:(id)arg1;
- (void)sendImages:(id)arg1;
- (void)removeImageAtIndex:(int)arg1;
- (void)takeAnotherPhoto;
- (void)selectAnotherImageFromPhotoLibrary;
- (void)selectAnotherImage;
- (void)cancel:(id)arg1;
- (void)setSelectedIndex:(int)arg1 animated:(BOOL)arg2;
- (id)addImageWithURL:(id)arg1 image:(id)arg2;
- (unsigned int)indexOfMediaItemWithURL:(id)arg1;
- (void)updateInterface;
- (void)notifyVoiceOverOfPageChange;
- (void)reload;
- (void)updateHintLabel;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)resetStats;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

