//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface WAMultiSendMediaPickerControllerStats : NSObject
{
    int _numberOfPhotosInCameraRoll;
    int _sampleCount;
    double _minimumDelay;
    double _averageDelay;
    double _maximumDelay;
}

@property(nonatomic) double maximumDelay; // @synthesize maximumDelay=_maximumDelay;
@property(nonatomic) double averageDelay; // @synthesize averageDelay=_averageDelay;
@property(nonatomic) double minimumDelay; // @synthesize minimumDelay=_minimumDelay;
@property(nonatomic) int sampleCount; // @synthesize sampleCount=_sampleCount;
@property(nonatomic) int numberOfPhotosInCameraRoll; // @synthesize numberOfPhotosInCameraRoll=_numberOfPhotosInCameraRoll;
- (void)reportStatsToServer;
- (id)description;

@end

