//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface WAMultiSendEditButton : UIButton
{
    UIImage *_originalImage;
    UIImage *_templateImage;
    BOOL _activated;
}

+ (id)buttonWithImage:(id)arg1;
@property(nonatomic) BOOL activated; // @synthesize activated=_activated;


@end

