//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMultiSendThumbnailBrowserItemView.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface WAMultiSendThumbnailBrowserImageView : WAMultiSendThumbnailBrowserItemView
{
    UIImageView *_thumbnailView;
}

+ (id)viewWithMediaItem:(id)arg1;

- (void)configureWithMediaItem:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

