//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface WANotificationSoundPickerCell : UITableViewCell
{
    UIView *_separator;
    BOOL _soundSelected;
    BOOL _doubleSeparator;
}

@property(nonatomic) BOOL doubleSeparator; // @synthesize doubleSeparator=_doubleSeparator;
@property(nonatomic) BOOL soundSelected; // @synthesize soundSelected=_soundSelected;

- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

