//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class CTCallCenter, NSArray, NSString, SoundEffect;

__attribute__((visibility("hidden")))
@interface WANotificationCenter : NSObject
{
    CTCallCenter *_callCenter;
    SoundEffect *_incomingSoundEffect;
    SoundEffect *_outgoingSoundEffect;
    BOOL _playOfflineMessageSound;
    BOOL _chatSoundsEnabled;
    BOOL _chatVibrateEnabled;
    BOOL _showMessagePreview;
    BOOL _personalMessageAlertsEnabled;
    BOOL _groupMessageAlertsEnabled;
    BOOL _callAlertsEnabled;
    unsigned int _inAppAlertStyle;
    NSString *_personalMessageSound;
    NSString *_groupMessageSound;
    NSString *_callSound;
    NSArray *_pushSoundSets;
    NSArray *_ringtoneSets;
}

@property(readonly, nonatomic) NSArray *ringtoneSets; // @synthesize ringtoneSets=_ringtoneSets;
@property(readonly, nonatomic) NSArray *pushSoundSets; // @synthesize pushSoundSets=_pushSoundSets;
@property(nonatomic) BOOL callAlertsEnabled; // @synthesize callAlertsEnabled=_callAlertsEnabled;
@property(copy, nonatomic) NSString *callSound; // @synthesize callSound=_callSound;
@property(nonatomic) BOOL groupMessageAlertsEnabled; // @synthesize groupMessageAlertsEnabled=_groupMessageAlertsEnabled;
@property(copy, nonatomic) NSString *groupMessageSound; // @synthesize groupMessageSound=_groupMessageSound;
@property(nonatomic) BOOL personalMessageAlertsEnabled; // @synthesize personalMessageAlertsEnabled=_personalMessageAlertsEnabled;
@property(copy, nonatomic) NSString *personalMessageSound; // @synthesize personalMessageSound=_personalMessageSound;
@property(nonatomic) BOOL showMessagePreview; // @synthesize showMessagePreview=_showMessagePreview;
@property(nonatomic) unsigned int inAppAlertStyle; // @synthesize inAppAlertStyle=_inAppAlertStyle;
@property(nonatomic) BOOL chatVibrateEnabled; // @synthesize chatVibrateEnabled=_chatVibrateEnabled;
@property(nonatomic) BOOL chatSoundsEnabled; // @synthesize chatSoundsEnabled=_chatSoundsEnabled;
@property BOOL playOfflineMessageSound; // @synthesize playOfflineMessageSound=_playOfflineMessageSound;

- (void)playOutgoingSoundEffect;
- (void)playIncomingSoundEffect;
- (void)playOutgoingSoundEffectIfAllowed;
- (void)playIncomingSoundEffectForWAMessage:(id)arg1;
- (void)loadNotificationSounds;
- (void)resetToDefaults;
- (void)migrateSettings;
- (void)loadSettings;
- (void)initializeDefaults;
- (id)init;

@end

