//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"
#import "WAPageableItemViewDelegate.h"

@class NSMutableSet, UIScrollView, WAPageableItemView;

__attribute__((visibility("hidden")))
@interface WAPageableItemBrowserView : UIView <UIScrollViewDelegate, WAPageableItemViewDelegate>
{
    UIScrollView *_pagingScrollView;
    NSMutableSet *_visiblePages;
    NSMutableSet *_recycledPages;
    BOOL _ignoreScrollViewDidScroll;
    BOOL _disableDelegateCallbacksDuringScrollingAnimation;
    id <WAPageableItemBrowserViewDelegate> _delegate;
    int _currentIndex;
}

@property(nonatomic) int currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) id <WAPageableItemBrowserViewDelegate> delegate; // @synthesize delegate=_delegate;

- (void)setViewStateOfCurrentPage:(id)arg1;
- (id)viewStateOfCurrentPage;
- (void)resetViewStates;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)pageableItemViewDidEndFocusedTask:(id)arg1;
- (void)pageableItemViewWillBeginFocusedTask:(id)arg1;
- (void)pageableItemViewDidFinishEditingItem:(id)arg1;
- (void)pageableItemViewDidUpdateItem:(id)arg1;
- (void)pageableItemViewDidReceiveTapOnDeleteButton:(id)arg1;
- (id)dequeueOrCreateViewForItem:(id)arg1;
- (void)configurePage:(id)arg1 atIndex:(int)arg2;
- (struct CGRect)frameForPageAtIndex:(int)arg1;
- (id)visiblePageAtIndex:(int)arg1;
@property(readonly, nonatomic) WAPageableItemView *currentItemView;
- (id)displayPageAtIndex:(int)arg1;
- (void)updateVisibilityOfPage:(id)arg1;
- (void)updateVisibilityOfAllVisiblePages;
- (void)tilePages;
- (void)removeItemAtIndex:(int)arg1 animated:(BOOL)arg2;
- (void)insertItemAtIndex:(int)arg1 animated:(BOOL)arg2;
- (void)recycleView:(id)arg1;
- (void)setCurrentIndex:(int)arg1 animated:(BOOL)arg2;
- (void)reloadItemAtIndex:(int)arg1;
- (void)reload;
- (void)layoutSubviews;
- (void)commonInit;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

