//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WAImageCropToolViewDelegate.h"
#import "WAMultiSendEditButtonPresenterViewDelegate.h"

@class UIButton, UITapGestureRecognizer, WACropAwareImageView, WAEditableImage, WAImageCropToolView, WAMultiSendEditButton, WAMultiSendEditButtonPresenterView;

__attribute__((visibility("hidden")))
@interface WAPageableImageScrollView : UIScrollView <WAImageCropToolViewDelegate, UIGestureRecognizerDelegate, WAMultiSendEditButtonPresenterViewDelegate, UIScrollViewDelegate>
{
    WACropAwareImageView *_imageView;
    float _scaleToRestoreAfterResize;
    struct CGPoint _pointToCenterAfterResize;
    BOOL _zoomingInProgress;
    BOOL _suppressLayout;
    WAImageCropToolView *_cropToolView;
    BOOL _interactiveCroppingInProgress;
    UITapGestureRecognizer *_singleTapGesture;
    UITapGestureRecognizer *_doubleTapGesture;
    struct CGRect _previousCropRect;
    WAMultiSendEditButtonPresenterView *_editButtonPresenterView;
    WAMultiSendEditButton *_rotateEditButton;
    WAMultiSendEditButton *_cropEditButton;
    BOOL _allowsEditing;
    WAEditableImage *_editableImage;
    UIButton *_deleteButton;
    float _contentWidth;
    id <WAPageableImageScrollViewEditingDelegate> _editingDelegate;
    float _editButtonsAlpha;
    struct UIEdgeInsets _edgeInsetsForMinimumZoom;
}

@property(nonatomic) float editButtonsAlpha; // @synthesize editButtonsAlpha=_editButtonsAlpha;
@property(nonatomic) id <WAPageableImageScrollViewEditingDelegate> editingDelegate; // @synthesize editingDelegate=_editingDelegate;
@property(nonatomic) BOOL allowsEditing; // @synthesize allowsEditing=_allowsEditing;
@property(nonatomic) float contentWidth; // @synthesize contentWidth=_contentWidth;
@property(readonly, nonatomic) WACropAwareImageView *imageView; // @synthesize imageView=_imageView;
@property(readonly, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) struct UIEdgeInsets edgeInsetsForMinimumZoom; // @synthesize edgeInsetsForMinimumZoom=_edgeInsetsForMinimumZoom;
@property(retain, nonatomic) WAEditableImage *editableImage; // @synthesize editableImage=_editableImage;

- (void)setInteractiveCroppingEnabled:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setZoomingEnabled:(BOOL)arg1;
- (void)configureImageViewWithCropping:(BOOL)arg1;
- (id)rotatedFullScreenImage;
- (void)setUpFullImageView:(id)arg1 croppedImageView:(id)arg2 withReferenceFrame:(struct CGRect)arg3 referenceFrameIsCropped:(BOOL)arg4;
@property(nonatomic) BOOL interactiveCroppingEnabled;
- (void)imageCropToolViewNormalizedCropRectDidFinishChanging:(id)arg1;
- (void)imageCropToolViewNormalizedCropRectDidChange:(id)arg1;
- (void)imageCropToolViewNormalizedCropRectWillBeginChanging:(id)arg1;
- (void)rotateViews:(id)arg1 byAngle:(float)arg2 aroundPoint:(struct CGPoint)arg3 scaleChange:(float)arg4 animationDuration:(double)arg5 animationBlock:(id)arg6 completion:(id)arg7;
- (void)rotateView:(id)arg1 byAngle:(float)arg2 aboutCenter:(struct CGPoint)arg3 scalingBy:(float)arg4;
- (void)setImageOrientation:(int)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)toggleZoomInOutAtPoint:(struct CGPoint)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)calculateForImageOfSize:(struct CGSize)arg1 displaySize:(struct CGSize *)arg2 minimumZoomScale:(float *)arg3 maximumZoomScale:(float *)arg4 initialZoomScale:(float *)arg5;
- (void)recalculateZoom;
- (void)didChangeFrameSize;
- (void)willChangeFrameSize;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutEditingButtonsAroundRect:(struct CGRect)arg1;
- (void)multiSendEditButtonPresenterViewDidChangeState:(id)arg1;
- (void)updateEditButtonsAlpha;
- (void)layoutSubviews;
- (BOOL)shouldShowEditButtons;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)doubleTapReceived:(id)arg1;
- (void)singleTapReceived:(id)arg1;
- (id)cloneButtonForRotationAnimation:(id)arg1;
@property(nonatomic) float visibility;
- (void)toggleCropMode:(id)arg1;
- (void)rotateButtonTapped:(id)arg1;
- (void)deleteButtonTapped:(id)arg1;
- (void)reset;
- (id)initWithFrame:(struct CGRect)arg1;

@end

