//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollViewDelegate.h"

@class WAPageableItemBrowserView;

@protocol WAPageableItemBrowserViewDelegate <UIScrollViewDelegate>
- (void)pageableItemBrowserViewDidEndFocusedTask:(WAPageableItemBrowserView *)arg1;
- (void)pageableItemBrowserViewWillBeginFocusedTask:(WAPageableItemBrowserView *)arg1;
- (void)pageableItemBrowserView:(WAPageableItemBrowserView *)arg1 didFinishEditingItemAtIndex:(int)arg2;
- (void)pageableItemBrowserView:(WAPageableItemBrowserView *)arg1 didUpdateItemAtIndex:(int)arg2;
- (void)pageableItemBrowserView:(WAPageableItemBrowserView *)arg1 wantsToDeleteItemAtIndex:(int)arg2;
- (void)pageableItemBrowserViewCurrentIndexDidChange:(WAPageableItemBrowserView *)arg1;
- (int)pageableItemCount:(WAPageableItemBrowserView *)arg1;
- (Class)pageableItemBrowserView:(WAPageableItemBrowserView *)arg1 itemViewClassForPageableItem:(id <WAPageable>)arg2;
- (id <WAPageable>)pageableItemBrowserView:(WAPageableItemBrowserView *)arg1 itemAtIndex:(int)arg2;
@end

