//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class WAPageableItemView;

@protocol WAPageableItemViewDelegate <NSObject>
- (void)pageableItemViewDidFinishEditingItem:(WAPageableItemView *)arg1;
- (void)pageableItemViewDidUpdateItem:(WAPageableItemView *)arg1;
- (void)pageableItemViewDidReceiveTapOnDeleteButton:(WAPageableItemView *)arg1;
- (void)pageableItemViewDidEndFocusedTask:(WAPageableItemView *)arg1;
- (void)pageableItemViewWillBeginFocusedTask:(WAPageableItemView *)arg1;
@end

