//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

__attribute__((visibility("hidden")))
@interface WAPageableItemView : UIView
{
    BOOL _spotlighted;
    BOOL _allowsEditing;
    int _index;
    Class _pageableItemClass;
    id <WAPageableItemViewDelegate> _delegate;
    float _visibility;
    float _contentWidth;
}

@property(nonatomic) BOOL allowsEditing; // @synthesize allowsEditing=_allowsEditing;
@property(nonatomic) float contentWidth; // @synthesize contentWidth=_contentWidth;
@property(nonatomic) BOOL spotlighted; // @synthesize spotlighted=_spotlighted;
@property(nonatomic) float visibility; // @synthesize visibility=_visibility;
@property(nonatomic) id <WAPageableItemViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) Class pageableItemClass; // @synthesize pageableItemClass=_pageableItemClass;
@property(nonatomic) int index; // @synthesize index=_index;

- (id)contentView;
- (void)resetViewStateWithAnimation:(BOOL)arg1;
- (void)setViewState:(id)arg1;
- (id)viewState;
- (void)prepareForReuse;
- (void)configureWithItem:(id)arg1;

@end

