//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface WAPhoneNumberGeocoder : NSObject
{
    NSDictionary *_maps;
}

+ (id)sharedGeocoder;

- (void)collectAvailableMaps;
- (void)renameGeocodingFiles;
- (id)locationTextForPhoneNumber:(id)arg1;
- (id)init;

@end

