//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "UITextFieldDelegate.h"

__attribute__((visibility("hidden")))
@interface WAPhoneNumberTextFieldHelper : NSObject <UITextFieldDelegate>
{
}

+ (BOOL)isStringADecimalNumber:(id)arg1;
+ (id)stringByKeepingOnlyDecimalDigits:(id)arg1;
+ (void)initialize;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (struct _NSRange)expandRange:(struct _NSRange)arg1 inTextFieldToIncludeNumber:(id)arg2;
- (unsigned int)endPositionOfPrefix:(id)arg1 inFormattedString:(id)arg2;

@end

