//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIScrollViewDelegate.h"

@class UIActivityIndicatorView, UIButton, UIImage, UIImageView, UILabel, UIScrollView, UIView, WAPhotoMoveAndScaleCropView;

__attribute__((visibility("hidden")))
@interface WAPhotoMoveAndScaleViewController : WAViewController <UIScrollViewDelegate>
{
    WAPhotoMoveAndScaleCropView *_cropView;
    UIActivityIndicatorView *_spinner;
    BOOL _statusBarWasHidden;
    BOOL _mustScaleToFill;
    BOOL _adjustsStatusBarAutomatically;
    unsigned int _mode;
    UIImage *_originalImage;
    float _minimumWidth;
    float _maximumWidth;
    id <WAPhotoMoveAndScaleViewControllerDelegate> _delegate;
     _completionHandler;
    UIScrollView *_scrollView;
    UILabel *_titleLabel;
    UIButton *_cancelButton;
    UIButton *_doneButton;
    UIImageView *_imageView;
    UIView *_bottomView;
    UIImageView *_bottomViewBackgroundView;
    UIImageView *_bottomViewShadowView;
    UIView *_footerContentView;
    UIImageView *_staticImageView;
}

@property(retain, nonatomic) UIImageView *staticImageView; // @synthesize staticImageView=_staticImageView;
@property(retain, nonatomic) UIView *footerContentView; // @synthesize footerContentView=_footerContentView;
@property(retain, nonatomic) UIImageView *bottomViewShadowView; // @synthesize bottomViewShadowView=_bottomViewShadowView;
@property(retain, nonatomic) UIImageView *bottomViewBackgroundView; // @synthesize bottomViewBackgroundView=_bottomViewBackgroundView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) BOOL adjustsStatusBarAutomatically; // @synthesize adjustsStatusBarAutomatically=_adjustsStatusBarAutomatically;
@property(copy, nonatomic)  completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) id <WAPhotoMoveAndScaleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(nonatomic) float minimumWidth; // @synthesize minimumWidth=_minimumWidth;
@property(nonatomic) BOOL mustScaleToFill; // @synthesize mustScaleToFill=_mustScaleToFill;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(nonatomic) unsigned int mode; // @synthesize mode=_mode;

- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (id)rotatingHeaderView;
- (id)rotatingFooterView;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)configureScrollViewForZooming;
- (id)imageForCurrentZoomRect;
- (void)cancel:(id)arg1;
- (void)done:(id)arg1;
- (void)layoutFooter;
- (void)relayout;
- (void)updateInterfaceForMode;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (int)preferredStatusBarStyle;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

