//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface WAPhoneNumberMap : NSObject
{
    NSString *_path;
    NSDictionary *_prefixMap;
    unsigned int _maxPrefixLength;
    unsigned int _minPrefixLength;
    NSString *_countryCode;
    NSString *_locale;
}

@property(readonly, nonatomic) NSString *locale; // @synthesize locale=_locale;
@property(readonly, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;

- (void)dealloc;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)loadIfNeeded;
- (id)locationForPhoneNumber:(id)arg1;
- (id)initWithPath:(id)arg1;

@end

