//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "MKAnnotation.h"

@class CLLocation, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface WAPlace : NSObject <MKAnnotation>
{
    struct dispatch_group_s *_infoLoadingGroup;
    NSString *_placeId;
    NSString *_name;
    NSString *_shortAddress;
    NSString *_fullAddress;
    NSString *_urlString;
    NSString *_iconURLString;
    CLLocation *_location;
    UIImage *_loResMapThumbnail;
    UIImage *_hiResMapThumbnail;
    unsigned int _source;
    double _distance;
}

+ (void)fetchAppleMapsThumbnailWithScale:(float)arg1 forLocation:(id)arg2 completion:(id)arg3;
+ (void)fetchGoogleMapsThumbnailWithScale:(float)arg1 forLocation:(id)arg2 completion:(id)arg3;
@property(readonly, nonatomic) unsigned int source; // @synthesize source=_source;
@property(retain, nonatomic) UIImage *hiResMapThumbnail; // @synthesize hiResMapThumbnail=_hiResMapThumbnail;
@property(retain, nonatomic) UIImage *loResMapThumbnail; // @synthesize loResMapThumbnail=_loResMapThumbnail;
@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) NSString *iconURLString; // @synthesize iconURLString=_iconURLString;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain, nonatomic) NSString *fullAddress; // @synthesize fullAddress=_fullAddress;
@property(retain, nonatomic) NSString *shortAddress; // @synthesize shortAddress=_shortAddress;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *placeId; // @synthesize placeId=_placeId;

- (void)fetchHiResThumbnailWithCompletion:(id)arg1;
- (BOOL)hiResThumbnailFetchNeeded;
- (void)fetchLoResThumbnailWithCompletion:(id)arg1;
- (BOOL)loResThumbnailFetchNeeded;
- (void)fetchGooglePlaceDetailsWithCompletion:(id)arg1;
- (BOOL)placeDetailsFetchNeeded;
@property(readonly, nonatomic) CDStruct_c3b9c2ee coordinate;
@property(readonly, nonatomic) NSString *subtitle;
@property(readonly, nonatomic) NSString *title;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (int)compare:(id)arg1;
- (id)initWithSource:(unsigned int)arg1;

@end

