//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIWebViewDelegate.h"

@class UIWebView, WAPlace;

__attribute__((visibility("hidden")))
@interface WAPlaceDetailsViewController : WAViewController <UIWebViewDelegate>
{
    BOOL _pageLoaded;
    WAPlace *_waPlace;
    id <ShareLocationControllerDelegate> _delegate;
    UIWebView *_webView;
}

@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) id <ShareLocationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAPlace *waPlace; // @synthesize waPlace=_waPlace;

- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)hideActivityIndicator;
- (void)showActivityIndicator;
- (void)loadPlacePageWithURLString:(id)arg1;
- (void)sendPlaceAction:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithWAPlace:(id)arg1 delegate:(id)arg2;

@end

