//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WAPlaceIconCache : NSObject
{
    NSMutableDictionary *_callbackBlocks;
}

+ (id)sharedCache;

- (id)placeIconImageForWAPlace:(id)arg1 completion:(id)arg2;
- (id)fsqCategoryIconFromImage:(id)arg1;
- (id)googleCategoryIconFromImage:(id)arg1;
- (void)saveImage:(id)arg1 withFilename:(id)arg2;
- (id)imageWithFilename:(id)arg1;
- (id)filenameForImageAtURLPath:(id)arg1;

@end

