//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSCache, NSManagedObjectContext, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WAProfilePictureManager : NSObject
{
    struct dispatch_queue_s *_thumbnailingQueue;
    struct dispatch_queue_s *_personalPictureProcessingQueue;
    NSManagedObjectContext *_contactsStorageContext;
     _contactsContextReleaseBlock;
    struct dispatch_queue_s *_groupPictureProcessingQueue;
    NSManagedObjectContext *_chatStorageContext;
     _chatContextReleaseBlock;
    NSMutableDictionary *_groupPictureRequestDates;
    NSCache *_profilePictureCache;
}

+ (id)groupPictureRequestDatesFilePath;
+ (BOOL)validateProfilePicture:(id)arg1 errorMessage:(id)arg2;
+ (id)sanitizedProfilePictureFromImage:(id)arg1;
+ (id)thumbnailForProfilePicture:(id)arg1;
+ (id)jpegDataForProfileThumbnail:(id)arg1;
+ (id)jpegDataForProfilePicture:(id)arg1;
+ (void)disallowProfilePictureRequests;
+ (BOOL)profilePictureRequestsAllowed;
+ (id)thumbnailFromProfilePicture:(id)arg1;
+ (id)groupPicturePlaceholder;
+ (id)personalPicturePlaceholder;
+ (id)fullPathToProfilePictureThumbnailForJID:(id)arg1;
+ (id)thumnbailFilenameForJID:(id)arg1;
+ (void)cancelBlock:(id)arg1;
+ (id)performBlock:(id)arg1 onQueue:(struct dispatch_queue_s *)arg2 afterDelay:(double)arg3;
+ (id)sharedManager;

- (void)reuploadMyProfilePictureOnlyIfNeeded:(BOOL)arg1;
- (void)requestMyProfilePictureIfNeeded;
- (void)deleteMyProfilePicture;
- (void)saveMyProfilePicture:(id)arg1;
- (void)saveMyProfilePictureData:(id)arg1 thumbnailData:(id)arg2;
- (id)myProfilePictureThumbnailData;
- (id)myProfilePictureData;
- (id)myProfilePictureThumbnail;
- (id)myProfilePictureReturningFullsizeImageAvailability:(char *)arg1;
- (void)requestProfilePictureDeleteForJID:(id)arg1 completion:(id)arg2;
- (void)setPictureData:(id)arg1 thumbnailData:(id)arg2 pictureID:(id)arg3 forWAChatSession:(id)arg4;
- (void)requestProfilePictureSetForJID:(id)arg1 picture:(id)arg2 completion:(id)arg3;
- (void)requestProfilePictureSetForJID:(id)arg1 withPictureData:(id)arg2 thumbnailData:(id)arg3 completion:(id)arg4;
- (void)deleteProfilePictureForWAStatus:(id)arg1;
- (void)processPictureChangeNotificationForContactWithJID:(id)arg1 pictureIdentifier:(id)arg2;
- (void)requestProfilePictureThumbnailForWAStatus:(id)arg1 onlyIfNecessary:(BOOL)arg2;
- (void)deleteGroupPictureForWAChatSession:(id)arg1;
- (void)processPictureChangeNotificationForGroupWithJID:(id)arg1 pictureIdentifier:(id)arg2 changeAuthorJID:(id)arg3 timestamp:(id)arg4;
- (void)requestGroupPictureThumbnailForWAChatSession:(id)arg1 onlyIfNecessary:(BOOL)arg2 completion:(id)arg3;
- (void)generateProfilePictureThumbnailFromPicture:(id)arg1 withCompletion:(id)arg2;
- (void)fetchGroupPictureForWAChatSession:(id)arg1 withCompletion:(id)arg2;
- (void)fetchPersonalProfilePictureForWAStatus:(id)arg1 withCompletion:(id)arg2;
- (void)createProfilePictureThumbnailForJID:(id)arg1 withCompletion:(id)arg2 returnImmediately:(BOOL)arg3;
- (void)resetGroupPictureRequestDateForJID:(id)arg1;
- (void)updateGroupPictureRequestDateForJID:(id)arg1;
- (BOOL)shouldRequestGroupPictureForWAStatus:(id)arg1;
- (BOOL)shouldRequestGroupPictureForJID:(id)arg1;
- (void)resetProfilePictureThumbnailCacheForJID:(id)arg1;
- (id)cachedProfilePictureThumbnailForWAGroupMember:(id)arg1;
- (id)cachedProfilePictureThumbnailForWAChatSession:(id)arg1;
- (id)cachedProfilePictureThumbnailForJID:(id)arg1;
- (id)profilePictureThumbnailForJID:(id)arg1 placeholderAllowed:(BOOL)arg2;
- (id)profilePictureThumbnailForJID:(id)arg1 returnImmediately:(BOOL)arg2 placeholderAllowed:(BOOL)arg3;
- (void)requestFullsizeProfilePictureForJID:(id)arg1 forced:(BOOL)arg2 withCompletion:(id)arg3;
- (id)bestAvailablePictureForJID:(id)arg1 fullsizeAvailable:(char *)arg2;
- (void)copyGroupPictureCachedThumbnailsFromJID:(id)arg1 toJID:(id)arg2;
- (void)deleteTemporaryGroupPictureForJID:(id)arg1;
- (id)temporaryGroupPictureForJID:(id)arg1;
- (void)storeTemporaryGroupPicture:(id)arg1 forWAChatSession:(id)arg2;
- (void)deleteProfilePictureThumbnailForJID:(id)arg1;
- (void)saveProfilePictureThumbnailPlaceholderForJID:(id)arg1;
- (id)profilePictureThumnbailForJID:(id)arg1 isPlaceholder:(char *)arg2;
- (void)saveProfilePictureThumbnail:(id)arg1 forJID:(id)arg2;
- (void)releaseContactsMOC;
- (id)acquireContactsMOC;
- (void)releaseChatMOC;
- (id)acquireChatMOC;
- (void)dealloc;
- (id)init;

@end

