//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAMessageCell.h"

@class NSTimer, UIButton, UIImageView, UILabel, UISlider;

__attribute__((visibility("hidden")))
@interface WAPushToTalkCell : WAMessageCell
{
    UIButton *_buttonPushToTalkAction;
    UISlider *_pttPlayerScrubber;
    UISlider *_pttUploadScrubber;
    UIImageView *_micIndicator;
    UIImageView *_personImage;
    UILabel *_audioDurationLabel;
    BOOL _playerWasPlaying;
    NSTimer *_uploadScrubberTimer;
    int _uploadScrubberPosition;
}

+ (float)heightForCellData:(id)arg1 width:(float)arg2 editing:(BOOL)arg3;

- (void)pttSliderActionEditDone:(id)arg1;
- (void)pttSliderActionStartEditing:(id)arg1;
- (void)uploadScrubberUpdate:(id)arg1;
- (void)setProgress:(float)arg1;
- (void)showPopupMenu;
- (void)setDimmed:(BOOL)arg1;
- (BOOL)isAnimating;
- (void)setHighlightState:(BOOL)arg1 forBubbleView:(id)arg2 animated:(BOOL)arg3;
- (BOOL)selectable;
- (void)updatePlayedIndication;
- (void)configureCellUpdatingAllContents:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setCellData:(id)arg1 delegate:(id)arg2;
- (void)updateDurationLabel;
- (void)updatePushToTalkControls;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

