//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface WAPushSoundSet : NSObject
{
    NSString *_name;
    NSArray *_sounds;
}

+ (id)findSoundByFilename:(id)arg1 inSoundSets:(id)arg2 returningSetIndex:(unsigned int *)arg3 returningSoundIndex:(unsigned int *)arg4;
+ (id)setWithName:(id)arg1 sounds:(id)arg2;
@property(readonly, nonatomic) NSArray *sounds; // @synthesize sounds=_sounds;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;

- (unsigned int)indexOfPushSoundWithFilename:(id)arg1;
- (id)pushSoundAtIndex:(unsigned int)arg1;
- (id)initWithName:(id)arg1 sounds:(id)arg2;

@end

