//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class WARepairDatabaseViewController;

@protocol WARepairDatabaseViewControllerDelegate <NSObject>
- (void)repairDatabaseViewControllerDidFail:(WARepairDatabaseViewController *)arg1;
- (void)repairDatabaseViewControllerDidSucceed:(WARepairDatabaseViewController *)arg1;
@end

