//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class UIButton, UIImageView, UILabel, UIProgressView, UIView;

__attribute__((visibility("hidden")))
@interface WARepairDatabaseViewController : UIViewController
{
    id <WARepairDatabaseViewControllerDelegate> _delegate;
    UILabel *_paragraphLabel;
    UILabel *_warningLabel;
    UIButton *_beginButton;
    UIProgressView *_progressView;
    UILabel *_completionLabel;
    UIImageView *_warningImageView;
    UIView *_topHairlineView;
    UIView *_bottomHairlineView;
    UIView *_buttonBackgroundView;
    UIView *_contentView;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *buttonBackgroundView; // @synthesize buttonBackgroundView=_buttonBackgroundView;
@property(retain, nonatomic) UIView *bottomHairlineView; // @synthesize bottomHairlineView=_bottomHairlineView;
@property(retain, nonatomic) UIView *topHairlineView; // @synthesize topHairlineView=_topHairlineView;
@property(retain, nonatomic) UIImageView *warningImageView; // @synthesize warningImageView=_warningImageView;
@property(retain, nonatomic) UILabel *completionLabel; // @synthesize completionLabel=_completionLabel;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIButton *beginButton; // @synthesize beginButton=_beginButton;
@property(retain, nonatomic) UILabel *warningLabel; // @synthesize warningLabel=_warningLabel;
@property(retain, nonatomic) UILabel *paragraphLabel; // @synthesize paragraphLabel=_paragraphLabel;
@property(nonatomic) id <WARepairDatabaseViewControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)handleRepairOutcome:(unsigned int)arg1;
- (void)performRecovery:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

