//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, UITableView, WAShareContactTableHeaderView, WAVCardNameSharingUnit, WAVCardProfilePhotoSharingUnit;

__attribute__((visibility("hidden")))
@interface WAShareContactViewController : WAViewController <UITableViewDataSource, UITableViewDelegate>
{
    void *_contact;
    NSArray *_sharingGroups;
    NSArray *_allSharingUnits;
    WAVCardNameSharingUnit *_nameSharingUnit;
    WAVCardProfilePhotoSharingUnit *_profilePhotoSharingUnit;
    WAShareContactTableHeaderView *_tableHeaderView;
    id <WAShareContactViewControllerDelegate> _delegate;
    UITableView *_tableView;
}

+ (id)controllerForContact:(void *)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) id <WAShareContactViewControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)sendContact:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)rebuildSharingGroups;
- (void)setContact:(void *)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

