//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIBezierPath, UIColor;

__attribute__((visibility("hidden")))
@interface WAShapeView : UIView
{
}

+ (Class)layerClass;
@property(retain, nonatomic) UIBezierPath *path;
@property(copy, nonatomic) NSString *lineCap;
@property(nonatomic) float lineWidth;
@property(retain, nonatomic) UIColor *strokeColor;
@property(retain, nonatomic) UIColor *fillColor;

@end

