//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIView;

__attribute__((visibility("hidden")))
@interface WAShareContactTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    UILabel *_bodyLabel;
    UIView *_bottomEdgeView;
}

+ (float)heightForSharingUnit:(id)arg1 displayWidth:(float)arg2;
+ (id)bodyFont;
+ (id)titleFont;
+ (id)cellWithReuseIdentifier:(id)arg1;
@property(retain, nonatomic) UIView *bottomEdgeView; // @synthesize bottomEdgeView=_bottomEdgeView;
@property(readonly, nonatomic) UILabel *bodyLabel; // @synthesize bodyLabel=_bodyLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@property(nonatomic) BOOL showBottomEdge;
@property(nonatomic) BOOL checked;
- (void)configureWithSharingUnit:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

