//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class UIImage, WASinglePhotoPickerController;

@protocol WASinglePhotoPickerControllerDelegate <NSObject>
- (void)singlePhotoPickerController:(WASinglePhotoPickerController *)arg1 didFinishWithImage:(UIImage *)arg2;
- (void)singlePhotoPickerControllerDidCancel:(WASinglePhotoPickerController *)arg1;
@end

