//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "UINavigationControllerDelegate.h"
#import "WAMediaPickerControllerDelegate.h"
#import "WAVideoPreviewViewControllerDelegate.h"

@class WAMediaPickerController;

__attribute__((visibility("hidden")))
@interface WASingleVideoPickerController : NSObject <WAMediaPickerControllerDelegate, UINavigationControllerDelegate, WAVideoPreviewViewControllerDelegate>
{
    WAMediaPickerController *_mediaPickerController;
    id <WASingleVideoPickerControllerDelegate> _delegate;
}

+ (id)controller;
+ (void)initialize;
@property(nonatomic) id <WASingleVideoPickerControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (void)videoPreviewViewControllerDidCancel:(id)arg1;
- (void)videoPreviewViewController:(id)arg1 didFailWithError:(id)arg2;
- (void)videoPreviewViewControllerDidConfirmVideo:(id)arg1;
- (BOOL)movieFileAtURL:(id)arg1 hasSameDurationAsMovieFileAtURL:(id)arg2;
- (void)mediaPickerController:(id)arg1 didFinishWithSelectedAssetURLs:(id)arg2;
- (void)mediaPickerControllerDidFinishPresenting:(id)arg1;
- (void)presentFromViewController:(id)arg1;
- (void)cleanUp;

@end

