//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "WAPhotoMoveAndScaleViewControllerDelegate.h"

@class UIImagePickerController;

__attribute__((visibility("hidden")))
@interface WASinglePhotoPickerController : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate, WAPhotoMoveAndScaleViewControllerDelegate>
{
    int _lastStatusBarStyle;
    BOOL _lastStatusBarHidden;
    UIImagePickerController *_pickerController;
    BOOL _mustScaleToFill;
    id <WASinglePhotoPickerControllerDelegate> _delegate;
    int _sourceType;
    float _minimumWidth;
    float _maximumWidth;
}

+ (id)controller;
+ (void)initialize;
@property(nonatomic) float maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(nonatomic) float minimumWidth; // @synthesize minimumWidth=_minimumWidth;
@property(nonatomic) BOOL mustScaleToFill; // @synthesize mustScaleToFill=_mustScaleToFill;
@property(nonatomic) int sourceType; // @synthesize sourceType=_sourceType;
@property(nonatomic) id <WASinglePhotoPickerControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (void)performCustomPushTransitionOnNavigationController:(id)arg1 toViewController:(id)arg2;
- (void)photoMoveAndScaleViewController:(id)arg1 didFinishWithImage:(id)arg2;
- (void)cleanUp;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)presentFromViewController:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

@end

