//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSURL, WASingleVideoPickerController;

@protocol WASingleVideoPickerControllerDelegate <NSObject>
- (void)singleVideoPickerControllerDidCancel:(WASingleVideoPickerController *)arg1;
- (void)singleVideoPickerController:(WASingleVideoPickerController *)arg1 didPickVideoAtURL:(NSURL *)arg2 referenceURL:(NSURL *)arg3;
@end

