//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface WASQLiteDebugger : NSObject
{
}

+ (id)SQLResultStringFromInteger:(int)arg1;
+ (void)checkIntegrityOfDatabaseAtPath:(id)arg1 completion:(id)arg2;
+ (id)contactsDatabaseFilePath;
+ (id)chatDatabaseFilePath;
+ (struct dispatch_queue_s *)processingQueue;
+ (void)runSQLiteMetaCommand:(id)arg1 output:(struct __sFILE *)arg2;
+ (void)closeSQLiteShell;
+ (void)openSQLiteShellForDatabaseAtPath:(id)arg1 readOnly:(BOOL)arg2;
+ (void)initialize;

@end

