//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface WASupportEmailComposer : NSObject
{
}

+ (void)composeEmailWithProblemDescription:(id)arg1 context:(id)arg2 attachment:(id)arg3 parentController:(id)arg4 mailDelegate:(id)arg5;

@end

