//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class WASyncManager;

@protocol WASyncManagerDelegate <NSObject>
- (void)syncManager:(WASyncManager *)arg1 didFinishSyncWithResult:(unsigned int)arg2;
@end

