//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class UITableViewCell;

__attribute__((visibility("hidden")))
@interface WATableRow : NSObject
{
    BOOL _disabled;
     _handler;
    UITableViewCell *_cell;
}

@property(nonatomic) BOOL disabled; // @synthesize disabled=_disabled;
@property(retain, nonatomic) UITableViewCell *cell; // @synthesize cell=_cell;
@property(copy, nonatomic)  handler; // @synthesize handler=_handler;


@end

