//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSMutableDictionary, UIColor, UIFont, UIImage;

__attribute__((visibility("hidden")))
@interface WATheme : NSObject
{
    UIImage *_wallpaperImage;
    UIImage *_grayWallpaperImage;
    UIImage *_blurredWallpaperImage;
    UIImage *_blurredGrayWallpaperImage;
    NSMutableDictionary *_contactNameColors;
    int _groupedTableViewCellSeparatorStyle;
    float _genericTableRowHeight;
    float _chatsTableRowHeight;
    UIColor *_tableViewTextFieldTextColor;
    int _tableViewCellActionTextAlignment;
    UIColor *_tableViewCellTextColor;
    UIColor *_tableViewCellTextColorSelected;
    UIColor *_tableViewCellActionTextColor;
    UIColor *_tableViewCellDestructiveTextColor;
    UIColor *_tableViewCellHighlightedBackgroundColor;
    UIColor *_tableViewCellSeparatorColor;
    UIFont *_tableViewFooterFont;
    UIColor *_tableViewFooterTextColor;
    UIColor *_tableViewFooterTextShadowColor;
    int _tableViewFooterTextAlignment;
    UIColor *_tintColor;
    UIColor *_accentColor;
    UIColor *_disabledTintColor;
    UIColor *_highlightedTintColor;
    UIColor *_helperTextColor;
    UIColor *_helperTextBackgroundColor;
    float _contactsTableRowHeight;
    float _waContactTableRowHeight;
    float _favoritesTableRowHeight;
    float _forwardPickerTableRowHeight;
    UIFont *_contactNameFont;
    UIFont *_contactNameFontItalic;
    UIFont *_waContactNameFont;
    UIColor *_contactNameColor;
    UIColor *_contactNameColorHighlighted;
    UIFont *_contactStatusFont;
    UIFont *_contactStatusFontItalic;
    UIColor *_contactStatusColor;
    UIColor *_contactStatusColorHighlighted;
    UIFont *_contactDetailsFont;
    UIColor *_contactDetailsColor;
    UIColor *_contactDetailsColorHighlighted;
    UIFont *_chatNameFont;
    UIFont *_chatMessageFont;
    UIFont *_bubbleContactNameFont;
    UIFont *_bubblePushNameFont;
    UIFont *_bubbleEventFont;
    UIFont *_bubbleDateFont;
    UIFont *_bubbleMessageFont;
    UIFont *_bubbleTimestampFont;
    UIFont *_bubbleVCardFont;
    UIColor *_messageTextColor;
    UIColor *_messageUrlColor;
    UIColor *_messageHighlightedUrlColor;
    UIFont *_tooltipFont;
    UIColor *_chatTimestampColor;
    UIColor *_chatTimestampColorHighlighted;
    struct CGSize _tableViewFooterTextShadowOffset;
}

+ (id)colorPalette;
+ (id)defaultTheme;
@property(readonly, nonatomic) UIColor *chatTimestampColorHighlighted; // @synthesize chatTimestampColorHighlighted=_chatTimestampColorHighlighted;
@property(readonly, nonatomic) UIColor *chatTimestampColor; // @synthesize chatTimestampColor=_chatTimestampColor;
@property(readonly, nonatomic) UIFont *tooltipFont; // @synthesize tooltipFont=_tooltipFont;
@property(readonly, nonatomic) UIColor *messageHighlightedUrlColor; // @synthesize messageHighlightedUrlColor=_messageHighlightedUrlColor;
@property(readonly, nonatomic) UIColor *messageUrlColor; // @synthesize messageUrlColor=_messageUrlColor;
@property(readonly, nonatomic) UIColor *messageTextColor; // @synthesize messageTextColor=_messageTextColor;
@property(readonly, nonatomic) UIFont *bubbleVCardFont; // @synthesize bubbleVCardFont=_bubbleVCardFont;
@property(readonly, nonatomic) UIFont *bubbleTimestampFont; // @synthesize bubbleTimestampFont=_bubbleTimestampFont;
@property(readonly, nonatomic) UIFont *bubbleMessageFont; // @synthesize bubbleMessageFont=_bubbleMessageFont;
@property(readonly, nonatomic) UIFont *bubbleDateFont; // @synthesize bubbleDateFont=_bubbleDateFont;
@property(readonly, nonatomic) UIFont *bubbleEventFont; // @synthesize bubbleEventFont=_bubbleEventFont;
@property(readonly, nonatomic) UIFont *bubblePushNameFont; // @synthesize bubblePushNameFont=_bubblePushNameFont;
@property(readonly, nonatomic) UIFont *bubbleContactNameFont; // @synthesize bubbleContactNameFont=_bubbleContactNameFont;
@property(readonly, nonatomic) UIFont *chatMessageFont; // @synthesize chatMessageFont=_chatMessageFont;
@property(readonly, nonatomic) UIFont *chatNameFont; // @synthesize chatNameFont=_chatNameFont;
@property(readonly, nonatomic) UIColor *contactDetailsColorHighlighted; // @synthesize contactDetailsColorHighlighted=_contactDetailsColorHighlighted;
@property(readonly, nonatomic) UIColor *contactDetailsColor; // @synthesize contactDetailsColor=_contactDetailsColor;
@property(readonly, nonatomic) UIFont *contactDetailsFont; // @synthesize contactDetailsFont=_contactDetailsFont;
@property(readonly, nonatomic) UIColor *contactStatusColorHighlighted; // @synthesize contactStatusColorHighlighted=_contactStatusColorHighlighted;
@property(readonly, nonatomic) UIColor *contactStatusColor; // @synthesize contactStatusColor=_contactStatusColor;
@property(readonly, nonatomic) UIFont *contactStatusFontItalic; // @synthesize contactStatusFontItalic=_contactStatusFontItalic;
@property(readonly, nonatomic) UIFont *contactStatusFont; // @synthesize contactStatusFont=_contactStatusFont;
@property(readonly, nonatomic) UIColor *contactNameColorHighlighted; // @synthesize contactNameColorHighlighted=_contactNameColorHighlighted;
@property(readonly, nonatomic) UIColor *contactNameColor; // @synthesize contactNameColor=_contactNameColor;
@property(readonly, nonatomic) UIFont *waContactNameFont; // @synthesize waContactNameFont=_waContactNameFont;
@property(readonly, nonatomic) UIFont *contactNameFontItalic; // @synthesize contactNameFontItalic=_contactNameFontItalic;
@property(readonly, nonatomic) UIFont *contactNameFont; // @synthesize contactNameFont=_contactNameFont;
@property(readonly, nonatomic) float forwardPickerTableRowHeight; // @synthesize forwardPickerTableRowHeight=_forwardPickerTableRowHeight;
@property(readonly, nonatomic) float favoritesTableRowHeight; // @synthesize favoritesTableRowHeight=_favoritesTableRowHeight;
@property(readonly, nonatomic) float waContactTableRowHeight; // @synthesize waContactTableRowHeight=_waContactTableRowHeight;
@property(readonly, nonatomic) float contactsTableRowHeight; // @synthesize contactsTableRowHeight=_contactsTableRowHeight;
@property(readonly, nonatomic) UIColor *helperTextBackgroundColor; // @synthesize helperTextBackgroundColor=_helperTextBackgroundColor;
@property(readonly, nonatomic) UIColor *helperTextColor; // @synthesize helperTextColor=_helperTextColor;
@property(readonly, nonatomic) UIColor *highlightedTintColor; // @synthesize highlightedTintColor=_highlightedTintColor;
@property(readonly, nonatomic) UIColor *disabledTintColor; // @synthesize disabledTintColor=_disabledTintColor;
@property(readonly, nonatomic) UIColor *accentColor; // @synthesize accentColor=_accentColor;
@property(readonly, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(readonly, nonatomic) int tableViewFooterTextAlignment; // @synthesize tableViewFooterTextAlignment=_tableViewFooterTextAlignment;
@property(readonly, nonatomic) struct CGSize tableViewFooterTextShadowOffset; // @synthesize tableViewFooterTextShadowOffset=_tableViewFooterTextShadowOffset;
@property(readonly, nonatomic) UIColor *tableViewFooterTextShadowColor; // @synthesize tableViewFooterTextShadowColor=_tableViewFooterTextShadowColor;
@property(readonly, nonatomic) UIColor *tableViewFooterTextColor; // @synthesize tableViewFooterTextColor=_tableViewFooterTextColor;
@property(readonly, nonatomic) UIFont *tableViewFooterFont; // @synthesize tableViewFooterFont=_tableViewFooterFont;
@property(readonly, nonatomic) UIColor *tableViewCellSeparatorColor; // @synthesize tableViewCellSeparatorColor=_tableViewCellSeparatorColor;
@property(readonly, nonatomic) UIColor *tableViewCellHighlightedBackgroundColor; // @synthesize tableViewCellHighlightedBackgroundColor=_tableViewCellHighlightedBackgroundColor;
@property(readonly, nonatomic) UIColor *tableViewCellDestructiveTextColor; // @synthesize tableViewCellDestructiveTextColor=_tableViewCellDestructiveTextColor;
@property(readonly, nonatomic) UIColor *tableViewCellActionTextColor; // @synthesize tableViewCellActionTextColor=_tableViewCellActionTextColor;
@property(readonly, nonatomic) UIColor *tableViewCellTextColorSelected; // @synthesize tableViewCellTextColorSelected=_tableViewCellTextColorSelected;
@property(readonly, nonatomic) UIColor *tableViewCellTextColor; // @synthesize tableViewCellTextColor=_tableViewCellTextColor;
@property(readonly, nonatomic) int tableViewCellActionTextAlignment; // @synthesize tableViewCellActionTextAlignment=_tableViewCellActionTextAlignment;
@property(readonly, nonatomic) UIColor *tableViewTextFieldTextColor; // @synthesize tableViewTextFieldTextColor=_tableViewTextFieldTextColor;
@property(readonly, nonatomic) float chatsTableRowHeight; // @synthesize chatsTableRowHeight=_chatsTableRowHeight;
@property(readonly, nonatomic) float genericTableRowHeight; // @synthesize genericTableRowHeight=_genericTableRowHeight;
@property(readonly, nonatomic) int groupedTableViewCellSeparatorStyle; // @synthesize groupedTableViewCellSeparatorStyle=_groupedTableViewCellSeparatorStyle;

- (void)resetContactNameColors;
- (id)contactNameColorForJID:(id)arg1;
- (id)colorListFilePath;
- (void)set;
@property(readonly, nonatomic) UIImage *blurredGrayWallpaperImage;
@property(readonly, nonatomic) UIImage *blurredWallpaperImage;
@property(readonly, nonatomic) UIImage *grayWallpaperImage;
@property(readonly, nonatomic) UIImage *wallpaperImage;
- (void)generateBlurredWallpaper;
- (void)loadWallpaper;
- (void)setNeedsReloadWallpaper;
- (void)wallpaperDidChange:(id)arg1;
- (void)reloadFonts;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (void)reloadDynamicTypeFontSize;
- (void)setFontSize:(float)arg1;
- (int)fontIndexForSize:(int)arg1;
- (int)fontSizeForIndex:(int)arg1;
- (id)fontNameForIndex:(int)arg1;
- (int)numberOfFonts;
- (int)defaultFontSize;
- (int)fontSize;
- (id)fontName;
- (void)dealloc;
- (id)init;

@end

