//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "WAScrollTracking.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface WATranslucentTableViewCell : UITableViewCell <WAScrollTracking>
{
    UIImageView *_blurMaskImageView;
    BOOL _blurEnabled;
    UIImageView *_blurOverlayImageView;
    id <WATranslucentTableViewCellDelegate> _delegate;
}

@property(readonly, nonatomic) BOOL blurEnabled; // @synthesize blurEnabled=_blurEnabled;
@property(nonatomic) id <WATranslucentTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIImageView *blurOverlayImageView; // @synthesize blurOverlayImageView=_blurOverlayImageView;

- (void)didMoveToWindow;
- (void)setFrame:(struct CGRect)arg1;
- (void)setDidScroll;
@property(nonatomic) float translucency;
- (void)updateBlurredBackground;
- (void)tintColorDidChange;
- (id)blurMaskTrackingView;
- (id)blurImageMask;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

