//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABubbleView.h"

@class NSString, UIImage;

__attribute__((visibility("hidden")))
@interface WAVCardBubbleView : WABubbleView
{
    NSString *_contactName;
    UIImage *_contactImage;
}

+ (struct CGSize)sizeForMaxWidth:(float)arg1 timestampString:(id)arg2 messageStatus:(unsigned int)arg3 fromName:(id)arg4 pushName:(id)arg5 showListIcon:(BOOL)arg6 isIncoming:(BOOL)arg7;
+ (float)heightForName:(id)arg1;
@property(retain, nonatomic) UIImage *contactImage; // @synthesize contactImage=_contactImage;
@property(retain, nonatomic) NSString *contactName; // @synthesize contactName=_contactName;

- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setDimmed:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithIncomingState:(BOOL)arg1 delegate:(id)arg2;

@end

