//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAVCardSharingUnit.h"

__attribute__((visibility("hidden")))
@interface WAVCardStreetAddressSharingUnit : WAVCardSharingUnit
{
}

+ (id)vCardValueForStreetAddressInfo:(id)arg1;
+ (id)displayStringForStreetAddressInfo:(id)arg1;
- (id)stringForVCard;
- (id)initWithRecord:(void *)arg1 index:(long)arg2;

@end

