//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIToolbarDelegate.h"
#import "WAVideoScrubberThumbnailBarDataSource.h"
#import "WAVideoScrubberTrimmerDelegate.h"

@class UIToolbar, WAGradientView, WAVideoScrubberSloMoBar, WAVideoScrubberThumbnailBar, WAVideoScrubberTrimmer;

__attribute__((visibility("hidden")))
@interface WAVideoScrubber : UIView <WAVideoScrubberTrimmerDelegate, WAVideoScrubberThumbnailBarDataSource, UIToolbarDelegate>
{
    WAVideoScrubberTrimmer *_trimmer;
    UIToolbar *_blurView;
    WAGradientView *_bottomShadowView;
    WAVideoScrubberThumbnailBar *_thumbnailBar;
    WAVideoScrubberSloMoBar *_sloMoBar;
    BOOL _slowMotionEnabled;
    BOOL _trimmingEnabled;
    BOOL _isTrimmingVideo;
    BOOL _isAdjustingSlowMotion;
    id <WAVideoScrubberDelegate> _delegate;
    struct CGSize _assetPresentationSize;
    CDStruct_1b6d18a9 _maximumDuration;
    CDStruct_1b6d18a9 _assetDuration;
    CDStruct_1b6d18a9 _currentTime;
    CDStruct_e83c9415 _trimmedTimeRange;
    CDStruct_e83c9415 _slowMotionTimeRange;
}

+ (float)preferredHeight;
@property(readonly, nonatomic) BOOL isAdjustingSlowMotion; // @synthesize isAdjustingSlowMotion=_isAdjustingSlowMotion;
@property(readonly, nonatomic) BOOL isTrimmingVideo; // @synthesize isTrimmingVideo=_isTrimmingVideo;
@property(nonatomic) CDStruct_1b6d18a9 currentTime; // @synthesize currentTime=_currentTime;
@property(nonatomic) CDStruct_e83c9415 slowMotionTimeRange; // @synthesize slowMotionTimeRange=_slowMotionTimeRange;
@property(readonly, nonatomic) CDStruct_e83c9415 trimmedTimeRange; // @synthesize trimmedTimeRange=_trimmedTimeRange;
@property(nonatomic) BOOL trimmingEnabled; // @synthesize trimmingEnabled=_trimmingEnabled;
@property(nonatomic) BOOL slowMotionEnabled; // @synthesize slowMotionEnabled=_slowMotionEnabled;
@property(readonly, nonatomic) struct CGSize assetPresentationSize; // @synthesize assetPresentationSize=_assetPresentationSize;
@property(readonly, nonatomic) CDStruct_1b6d18a9 assetDuration; // @synthesize assetDuration=_assetDuration;
@property(readonly, nonatomic) CDStruct_1b6d18a9 maximumDuration; // @synthesize maximumDuration=_maximumDuration;
@property(nonatomic) id <WAVideoScrubberDelegate> delegate; // @synthesize delegate=_delegate;

- (void)videoScrubberTrimmerDidEndDraggingThumb:(id)arg1;
- (void)videoScrubberTrimmerDidChangeThumbValue:(id)arg1;
- (void)videoScrubberTrimmerDidBeginDraggingThumb:(id)arg1;
- (void)videoScrubberPrecisionRangeSlider:(id)arg1 mayPresentRangeFrom:(float)arg2 to:(float)arg3;
- (void)videoScrubberPrecisionRangeSlider:(id)arg1 willPresentRangeFrom:(float)arg2 to:(float)arg3 around:(float)arg4 animationDuration:(double)arg5;
- (void)videoScrubberPrecisionRangeSliderDidEndDraggingHandle:(id)arg1;
- (void)videoScrubberPrecisionRangeSliderDidDragHandle:(id)arg1;
- (void)videoScrubberPrecisionRangeSliderDidBeginDraggingHandle:(id)arg1;
- (void)videoScrubberThumbnailBar:(id)arg1 videoFramesAtTimes:(id)arg2 size:(struct CGSize)arg3 tolerance:(CDStruct_1b6d18a9)arg4 block:(id)arg5;
- (void)configureWithAssetDuration:(CDStruct_1b6d18a9)arg1 presentationSize:(struct CGSize)arg2 maximumDuration:(CDStruct_1b6d18a9)arg3;
- (void)setThumbHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (int)positionForBar:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

