//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAVideoScrubberPrecisionRangeSlider.h"

@class UIImageView, _WAVideoScrubberStripedBar;

__attribute__((visibility("hidden")))
@interface WAVideoScrubberSloMoBar : WAVideoScrubberPrecisionRangeSlider
{
    _WAVideoScrubberStripedBar *_leftBar;
    _WAVideoScrubberStripedBar *_centerBar;
    _WAVideoScrubberStripedBar *_rightBar;
    float _centerValue;
    UIImageView *_leftHandle;
    UIImageView *_rightHandle;
}


- (void)getFramesForLeftHandle:(struct CGRect *)arg1 atPosition:(float)arg2 rightHandle:(struct CGRect *)arg3 atPosition:(float)arg4 leftMostVisiblePosition:(float)arg5 rightMostVisiblePosition:(float)arg6;
- (id)rightHandleView;
- (id)leftHandleView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

