//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAVideoPreviewViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "WAImageToImageTransitioning.h"
#import "WAMediaPlayerDelegate.h"
#import "WAVideoScrubberDelegate.h"

@class AVAssetImageGenerator, AVAssetTrack, AVMutableComposition, AVMutableVideoComposition, AVURLAsset, UIBarButtonItem, UIToolbar, UIView, WAMediaPlayer, WAVideoScrubber;

__attribute__((visibility("hidden")))
@interface WAVideoEditorController : WAVideoPreviewViewController <WAMediaPlayerDelegate, WAVideoScrubberDelegate, UIGestureRecognizerDelegate, WAImageToImageTransitioning>
{
    WAMediaPlayer *_mediaPlayer;
    WAVideoScrubber *_videoScrubber;
    UIView *_videoScrubberContainerView;
    BOOL _videoScrubberHidden;
    AVMutableComposition *_composition;
    AVMutableVideoComposition *_videoComposition;
    AVURLAsset *_originalAsset;
    AVAssetTrack *_videoTrack;
    AVAssetTrack *_audioTrack;
    struct CGSize _videoPresentationSize;
    int _slowMotionFactor;
    BOOL _fullscreenMode;
    UIBarButtonItem *_playButtonItem;
    UIBarButtonItem *_pauseButtonItem;
    UIBarButtonItem *_spaceButtonItem;
    AVAssetImageGenerator *_lastImageGenerator;
    UIToolbar *_toolbar;
    CDStruct_1b6d18a9 _sourceTimeToSeekOnPlayerLoad;
    CDStruct_e83c9415 _compositionSlowMotionTimeRange;
    BOOL _playerWasPlayingBeforeScrubbingBegan;
    BOOL _waitingToReprocessVideo;
    BOOL _initialTranscodeStarted;
}


- (void)finishTransitionWithView:(id)arg1 context:(id)arg2;
- (id)viewForTransitionAnimationWithContext:(id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1;
- (BOOL)shouldUseImageToImageTransitionForOperation:(int)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
- (void)mediaPlayerDidEndScrubbing:(id)arg1;
- (void)mediaPlayerDidBeginScrubbing:(id)arg1;
- (void)mediaPlayerDidFinishLoading:(id)arg1;
- (void)mediaPlayerDidPlayToEndTime:(id)arg1;
- (void)mediaPlayerDidChangeCurrentTime:(id)arg1;
- (void)mediaPlayerStatusDidChange:(id)arg1;
- (void)mediaPlayerDidRequestPlaybackStart:(id)arg1;
- (void)videoScrubber:(id)arg1 videoFramesAtTimes:(id)arg2 size:(struct CGSize)arg3 tolerance:(CDStruct_1b6d18a9)arg4 block:(id)arg5;
- (void)videoScrubberDidEndScrubbing:(id)arg1 resumePlayback:(BOOL)arg2;
- (void)videoScrubberDidChangeCurrentTime:(id)arg1;
- (void)videoScrubberDidBeginScrubbing:(id)arg1;
- (void)videoScrubberDidChangeSlowMotionTimeRange:(id)arg1;
- (void)videoScrubberDidChangeTrimmedTimeRange:(id)arg1;
- (CDStruct_1b6d18a9)sourceTimeFromPlayerTime:(CDStruct_1b6d18a9)arg1;
- (CDStruct_1b6d18a9)playerTimeFromSourceTime:(CDStruct_1b6d18a9)arg1;
- (void)pauseButtonTapped:(id)arg1;
- (void)playButtonTapped:(id)arg1;
- (void)updateThumb;
- (void)updateSendButton;
- (void)sendVideo:(id)arg1;
- (id)videoCompositionForTranscode;
- (id)assetToTranscode;
- (CDStruct_e83c9415)timeRangeToExport;
- (BOOL)internalRequiresTranscoding;
- (void)reprocessVideo;
- (void)cancelReprocessVideoAfterDelay;
- (void)reprocessVideoAfterDelay;
- (void)updateMediaPlayerPlaybackTimeRange;
- (void)rebuildCompositionSeekingToSourceTime:(CDStruct_1b6d18a9)arg1;
- (BOOL)isOriginalAssetValid;
- (void)setVideoScrubberHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutInterface;
- (void)loadOriginalAssetWithCompletionHandler:(id)arg1;
- (void)setFullscreenMode:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setFullscreenMode:(BOOL)arg1;
- (void)viewTapped:(id)arg1;
- (id)statusBarView;
- (void)viewDidLayoutSubviews;
- (void)updateBottomToolbar;
- (id)rotatingFooterView;
- (id)shadowViewInView:(id)arg1;
- (void)setNavigationBarShadowHidden:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)configureVideoScrubber;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

