//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>

__attribute__((visibility("hidden")))
@interface WAViewController : UIViewController
{
}

+ (void)handleCorruptedNavigationStack;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)logMethodCall:(SEL)arg1;
- (id)uniqueIdentifier;

@end

