//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

@class NSTimer, NSURL, UILabel, UIProgressView, UIView, WADoneWithSpinnerBarButtonItem, WAVideoTranscoder;

__attribute__((visibility("hidden")))
@interface WAVideoPreviewViewController : WAViewController
{
    WAVideoTranscoder *_transcoder;
    NSTimer *_progressTimer;
    struct dispatch_group_s *_transcodeDispatchGroup;
    BOOL _progressViewHidden;
    int _transcodeJobID;
    BOOL _requiresTranscoding;
    BOOL _sendButtonTapped;
    NSURL *_videoURL;
    NSURL *_outputFileURL;
    NSURL *_referenceURL;
    NSURL *_assetLibraryURL;
    id <WAVideoPreviewViewControllerDelegate> _delegate;
    UIView *_progressView;
    WADoneWithSpinnerBarButtonItem *_sendButton;
    UIProgressView *_progressBarView;
    UILabel *_progressLabel;
    unsigned long long _videoFileSize;
}

+ (id)controller;
@property(retain, nonatomic) UILabel *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(retain, nonatomic) UIProgressView *progressBarView; // @synthesize progressBarView=_progressBarView;
@property(readonly, nonatomic) BOOL sendButtonTapped; // @synthesize sendButtonTapped=_sendButtonTapped;
@property(readonly, nonatomic) WADoneWithSpinnerBarButtonItem *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UIView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) id <WAVideoPreviewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSURL *assetLibraryURL; // @synthesize assetLibraryURL=_assetLibraryURL;
@property(copy, nonatomic) NSURL *referenceURL; // @synthesize referenceURL=_referenceURL;
@property(copy, nonatomic) NSURL *outputFileURL; // @synthesize outputFileURL=_outputFileURL;
@property(nonatomic) BOOL requiresTranscoding; // @synthesize requiresTranscoding=_requiresTranscoding;
@property(nonatomic) unsigned long long videoFileSize; // @synthesize videoFileSize=_videoFileSize;
@property(copy, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;

- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)didProcessVideo;
- (void)willProcessVideo;
- (void)processTranscodedVideoOfDuration:(double)arg1 atURL:(id)arg2 referenceURL:(id)arg3;
- (id)videoCompositionForTranscode;
- (id)assetToTranscode;
- (void)reallyProcessVideo;
- (void)setNeedsVideoProcessing;
- (void)cancelVideoProcessing;
- (CDStruct_e83c9415)timeRangeToExport;
- (BOOL)internalRequiresTranscoding;
- (void)waitForVideoProcessingToFinish;
- (void)sendVideo:(id)arg1;
- (void)updateSendButton;
- (void)updateProgress:(id)arg1;
- (void)layoutProgressView;
- (void)setProgressViewHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)cancel:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

