//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class UIView, WAVoiceCallViewController;

@protocol WAVoiceCallViewControllerDelegate <NSObject>
- (void)voiceCallViewControllerWantsToShowChatViewForOtherParty:(WAVoiceCallViewController *)arg1;
- (UIView *)voiceCallViewControllerNeedsUpdatedSnapshot:(WAVoiceCallViewController *)arg1;
- (void)voiceCallViewControllerWillResignActive:(WAVoiceCallViewController *)arg1;
- (void)voiceCallViewControllerDidFinish:(WAVoiceCallViewController *)arg1;
@end

