//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, UIButton, UIImage, UIImageView, UIMotionEffectGroup, UIScrollView, UITableView, UIView;

__attribute__((visibility("hidden")))
@interface WAWallpaperPreviewController : WAViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UIView *_bottomView;
    UIScrollView *_pagingScrollView;
    NSMutableArray *_scrollViewPages;
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    UITableView *_tableViewMessages;
    UIButton *_buttonParallaxOnOff;
    UIMotionEffectGroup *_parallaxEffect;
    BOOL _parallaxEnabled;
    NSArray *_messagesLeft;
    NSArray *_messagesMiddle;
    NSArray *_messagesRight;
    NSArray *_messagesSinglePhoto;
    BOOL _libraryMode;
    id <WAWallpaperPreviewControllerDelegate> _delegate;
    int _libraryImageIndex;
    UIImage *_image;
}

+ (id)controllerWithLibraryImageIndex:(unsigned int)arg1;
+ (id)controllerWithImage:(id)arg1;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) int libraryImageIndex; // @synthesize libraryImageIndex=_libraryImageIndex;
@property(nonatomic) BOOL libraryMode; // @synthesize libraryMode=_libraryMode;
@property(nonatomic) id <WAWallpaperPreviewControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowWithCellData:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)sampleChatMessagesForTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)updateScrollViewAfterEnablingMotion:(BOOL)arg1;
- (void)checkIfMotionShouldBeDisabledUnintentionally;
- (void)updateParallaxOnOffButtonState;
- (void)setParallaxEffectEnabled:(BOOL)arg1;
- (void)parallaxOnOffAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)doneAction:(id)arg1;
- (id)imageForCurrentZoomRect;
- (void)reloadSingleImage;
- (void)tilePages;
- (void)setCurrentPageIndex:(unsigned int)arg1;
- (void)scrollToPageAtIndex:(int)arg1 animated:(BOOL)arg2;
- (void)unloadScrollViewPageAtIndex:(int)arg1;
- (void)loadScrollViewPageAtIndex:(int)arg1 asynchronously:(BOOL)arg2;
- (id)parallaxOnOffButton;
- (id)sampleConversationTable;
- (void)presentFromViewController:(id)arg1 animated:(BOOL)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)init;

@end

