//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSCache;

__attribute__((visibility("hidden")))
@interface WAWallpaperLibrary : NSObject
{
    NSArray *_imagePaths;
    NSCache *_fullsizeImages;
    NSCache *_thumbnails;
}

+ (struct CGSize)thumbnailSize;
+ (id)sharedLibrary;

- (void)fetchFullsizeImageAtIndex:(unsigned int)arg1 completion:(id)arg2;
- (void)fetchThumbnailForImageAtIndex:(unsigned int)arg1 completion:(id)arg2;
- (id)imageAtIndex:(unsigned int)arg1;
- (unsigned int)numberOfItems;
- (id)init;

@end

