//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, UIWebView;

__attribute__((visibility("hidden")))
@interface WebContentViewController : WAViewController <UIWebViewDelegate>
{
    UIWebView *_webView;
    BOOL _shouldGoBack;
    NSString *_urlString;
}

+ (id)controllerWithTitle:(id)arg1 urlString:(id)arg2;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;

- (void)hideActivityIndicator;
- (void)showActivityIndicator;
- (void)goBackIfNecessary;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;

@end

