//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "ImageSearchControllerDelegate.h"
#import "WAPhotoMoveAndScaleViewControllerDelegate.h"

@class GTMHTTPFetcher, ImageSearchController, NSString, WAPhotoMoveAndScaleViewController;

__attribute__((visibility("hidden")))
@interface WebImagePicker : UINavigationController <ImageSearchControllerDelegate, WAPhotoMoveAndScaleViewControllerDelegate>
{
    ImageSearchController *_imageSearchController;
    id <WebImagePickerDelegate> _pickerDelegate;
    GTMHTTPFetcher *_httpFetcher;
    WAPhotoMoveAndScaleViewController *_moveAndScaleViewController;
}


- (void)fetcher:(id)arg1 receivedData:(id)arg2;
- (void)fetcher:(id)arg1 finishedWithData:(id)arg2 error:(id)arg3;
- (void)downloadImageAtURL:(id)arg1;
- (void)photoMoveAndScaleViewController:(id)arg1 didFinishWithImage:(id)arg2;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)imageSearchControllerDidCancel:(id)arg1;
- (void)imageSearchController:(id)arg1 didSelectImageWithURL:(id)arg2;
@property(retain, nonatomic) NSString *preloadedSearchText;
- (id)initWithPickerDelegate:(id)arg1;

@end

