//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DecFile.h"

@class XMPPRC4Coder;

__attribute__((visibility("hidden")))
@interface XMPPEncryption : NSObject
{
    XMPPRC4Coder *_incoming;
    XMPPRC4Coder *_outgoing;
}

+ (id)MACWithKey:(id)arg1 andData:(id)arg2 sequence:(int)arg3;
+ (id)PBKDF2WithPassword:(id)arg1 andSalt:(id)arg2 derivedKeyLength:(int)arg3 rounds:(int)arg4;
@property(readonly, nonatomic) XMPPRC4Coder *outgoing; // @synthesize outgoing=_outgoing;
@property(readonly, nonatomic) XMPPRC4Coder *incoming; // @synthesize incoming=_incoming;
- (id)init;

@end

