//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DecFile.h"

@class NSMutableArray, NSNumber, NSString, NSThread;

__attribute__((visibility("hidden")))
@interface XMPPContactsSyncContext : NSObject
{
    unsigned int _mode;
    unsigned int _context;
    NSString *_sid;
    unsigned int _index;
    unsigned int _count;
    NSNumber *_timeout;
    id _delegate;
    NSThread *_thread;
    SEL _finishedSelector;
    SEL _failedSelector;
    id _userData;
    NSMutableArray *_contacts;
    NSMutableArray *_result;
}

@property(retain, nonatomic) NSMutableArray *result; // @synthesize result=_result;
@property(retain, nonatomic) NSMutableArray *contacts; // @synthesize contacts=_contacts;
@property(retain, nonatomic) id userData; // @synthesize userData=_userData;
@property(nonatomic) SEL failedSelector; // @synthesize failedSelector=_failedSelector;
@property(nonatomic) SEL finishedSelector; // @synthesize finishedSelector=_finishedSelector;
@property(retain, nonatomic) NSThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSNumber *timeout; // @synthesize timeout=_timeout;
@property(nonatomic) unsigned int count; // @synthesize count=_count;
@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(retain, nonatomic) NSString *sid; // @synthesize sid=_sid;
@property(nonatomic) unsigned int context; // @synthesize context=_context;
@property(nonatomic) unsigned int mode; // @synthesize mode=_mode;

@end

