//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DecFile.h"

@class NSData, NSMutableArray, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface XMPPStanzaElement : NSObject
{
    NSMutableDictionary *_attributes;
    NSMutableArray *_children;
    BOOL _compressed;
    NSString *_name;
    NSData *_value;
}

@property(retain, nonatomic) NSData *value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) BOOL compressed; // @synthesize compressed=_compressed;
- (id)children;
- (id)attributes;
- (id)log;
- (id)description;
- (id)childArrayByName:(id)arg1;
- (id)childByName:(id)arg1 attribute:(id)arg2 value:(id)arg3;
- (id)childByName:(id)arg1;
- (id)childByIndex:(unsigned int)arg1;
- (unsigned int)childCount;
- (void)removeChild:(id)arg1;
- (void)addChild:(id)arg1;
- (id)allAttributes;
- (id)attributeByName:(id)arg1;
- (void)setAttributeWithName:(id)arg1 value:(id)arg2;
- (id)initWithName:(id)arg1;

@end

