//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DecFile.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface XMPPRequestVOIPCallabilityStatus : NSObject
{
    NSString *_jid;
    int _callability;
}

+ (int)stringToType:(id)arg1;
@property(nonatomic) int callability; // @synthesize callability=_callability;
@property(retain, nonatomic) NSString *jid; // @synthesize jid=_jid;

@end

