//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DecFile.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface XMPPContact : NSObject
{
    BOOL _whatsapp;
    NSString *_number;
    NSString *_jid;
}

@property(nonatomic) BOOL whatsapp; // @synthesize whatsapp=_whatsapp;
@property(retain, nonatomic) NSString *jid; // @synthesize jid=_jid;
@property(retain, nonatomic) NSString *number; // @synthesize number=_number;
- (id)description;

@end

