//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DecFile.h"
#import "XMPPRequest.h"

__attribute__((visibility("hidden")))
@interface XMPPRequestUploadURL : XMPPRequest
{
}

- (void)failed:(id)arg1;
- (void)success:(id)arg1;
- (id)initWithBlock:(id)arg1 fileHash:(id)arg2 origHash:(id)arg3 filetype:(unsigned int)arg4 filesize:(unsigned long long)arg5 mediaIndex:(int)arg6 totalMediaCount:(int)arg7;

// Remaining properties
@property(copy, nonatomic) id block;

@end

